### ISSUE TITLE
[Documentation] Commandline-based installation?

### ISSUE THREAD

**Issue by rubyFeedback** [mhogomchungu/media-downloader#1]
Hey there,

Would it be possible to add to the README how to install this
project quickly via the commandline?

Other projects have e. g. "curl | sh" or something like that.

It would be nice if we could have this for the project here
too. (Here we can assume that the user has a sane compile
chain already, as newbies will rarely use a compile-based
variant.)

This suggestion is made mostly for simplicity, to let people
try the project faster.

**Comment by mhogomchungu** [comment]
The README now has info on how to install binary packages and build from source using command line.

Closing this one as fixed but feel free to comment if anything comes up.
