### ISSUE TITLE
Multi-threaded download function

### ISSUE THREAD

**Issue by SONGjiemo** [mhogomchungu/media-downloader#100]
The downloader always downloads slowly. I expect to be able to download it multi-threaded, so that it can be downloaded quickly.
![QQ截图20220303172645](https://user-images.githubusercontent.com/46627639/156536100-31a9cc9a-d75f-4670-9753-dc63d7d234c9.png)
![image](https://user-images.githubusercontent.com/46627639/156536457-e15df7bd-4cbb-4670-8188-9c883fa56783.png)

下载测试地址：
https://v3.cdtlas.com/20220302/N6HEAmYv/1100kb/hls/index.m3u8

https://new.iskcd.com/20220301/jydgKeds/1100kb/hls/playlist_up.m3u8

https://sluiceyf.titan.mgtv.com/c1/2019/02/11_0/3830FC669867895CEA39E6D51B6B92F2_20190211_1_1_504_mp4/47217EBC5D726FE6A6FCB8D8F1B49D9B.m3u8?arange=0&pm=rF7nPkc3esvTD2q3zvrFGM2DlxDl5JF2FCbXu_HUWSpJST6GncsAQUZIyCwYzW92X4epGJqD52ozl5dL5gsBRl2ueZbvp8zJPiukuMr45NOqpkIAtZjtR1eV7CVa36UOQVa6BrgEXARcBI5XlGnaStY~HwBG8LmpZJFFTVc0~ImRICUFl1IidgOlwbLikoItcDZU_fRijIaaLWtpKxaz1_ZK3cqsZYjOEG0ff8_Vgwo4gZEw4kqMh8PFX4XqgRaRC3hto_qd_D3UDvB4pPcWRzsHb7ryHqjMTFr7SduMcrneo9QLCPr2rfhw_0jg7rsjvxtAeamDmkmT6TQm8ZC~c56xCei4N7ihxcjNICVgzOcRwJ5BEBf3AlebgiDAYqtasA2wEXQe_jtdoNql5I1jJFnGbMk-&drmFlag=0&isTrial=0&vcdn=0&scid=25117&ruid=bbcd9ebee7ff4e35&sh=1

**Comment by mhogomchungu** [comment]
Use yt-dlp-aria2c extension[1] for faster downloads.

You can read more about aria2c from here[2]

[1] https://github.com/mhogomchungu/media-downloader/wiki/Extensions#3-yt-dlp-aria2c

[2] https://linuxaria.com/recensioni/speed-up-your-download-with-aria2

**Comment by SONGjiemo** [comment]
> 使用yt-技术-aria2c扩展[1]对于更快下载。
> 
> 你可以读取更多关于aria2c从这里[2].
> 
> 关于如何安装的扩展是这里[3].
> 
> [1] https://github.com/mhogomchungu/media-downloader/wiki/Extensions#3-yt-dlp-aria2c
> 
> [2] https://linuxaria.com/recensioni/speed-up-your-download-with-aria2
> 
> [3] https://github.com/mhogomchungu/media-downloader/wiki/Extensions#how-to-install-extensions

Hello, I have checked and configured successfully. Let me first ask you if there is a parameter for how many threads can be configured in the json configuration. Hope to answer, I want to configure the number of threads myself.
