### ISSUE TITLE
Support for you-get and lux gadgets

### ISSUE THREAD

**Issue by SONGjiemo** [mhogomchungu/media-downloader#101]
I am a Chinese user, you may not understand these two gadgets. But it is more practical for Chinese users. I hope to support him.

you-get address
https://github.com/soimort/you-get
lux address
https://github.com/iawia002/lux

**Comment by mhogomchungu** [comment]
Support for lux is almost done.

Its output is too unpredictable and i opened a feature here[1] to ask them to make its output predictable and easier to use.

If i will add a support for lux will depend on how they will respond to this feature request.

[1] https://github.com/iawia002/lux/issues/1054

**Comment by SONGjiemo** [comment]
>对勒克斯的支持几乎完成了。>>其输出太不可预测了，我打开了一个功能[1]，要求他们使其输出可预测且易于使用。>>我将添加对lux的支持，这取决于他们如何响应此功能请求。>> [1] [iawia002/lux#1054]（https://github.com/iawia002/lux/issues/1054）

Thank you very much 🙏

**Comment by mhogomchungu** [comment]
Go to here[1] and then:-
1. Download "lux.json" file.
2. Download and install "MediaDownloader-DEV-March-16-2022.setup.exe".
3. Start it.
4. Install the lux extension dowloaded in step 1 above using instructions from here[2].
5.  After lux binary is installed, "lux" extension show now be present in the list of "Engine names". If it is not then restart.

I have not tested lux's playlist functionality and it probably does not work.

Try it and tell me how it works.
[1] https://github.com/mhogomchungu/media-downloader/releases/tag/2.2.1
[2] https://github.com/mhogomchungu/media-downloader/wiki/Extensions#how-to-install-extensions

**Comment by mhogomchungu** [comment]
Copy the whole output and paste it here, the error message that say what it failed is somewhere at the beginning of the output.

**Comment by SONGjiemo** [comment]
> Copy the whole output and paste it here, the error message that say what it failed is somewhere at the beginning of the output.

[media-downloader] cmd: "D:/MediaDownloader-2.2.0/local/bin/lux.exe" "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
已用时间: 00:00:23
Downloading https://www.youtube.com/watch?v=dQw4w9WgXcQ error:



Get "https://youtube.com/embed/dQw4w9WgXcQ?hl=en": dial tcp 174.37.175.229:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
github.com/iawia002/lux/extractors/youtube.(*extractor).Extract
	/Users/iawia002/go/src/github.com/iawia002/lux/extractors/youtube/youtube.go:39
github.com/iawia002/lux/extractors.Extract
	/Users/iawia002/go/src/github.com/iawia002/lux/extractors/extractors.go:52
github.com/iawia002/lux/app.download
	/Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:278
github.com/iawia002/lux/app.New.func1
	/Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:255
github.com/urfave/cli/v2.(*App).RunContext
	/Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
	/Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main
	/Users/iawia002/go/src/github.com/iawia002/lux/main.go:13
runtime.main
	/usr/local/Cellar/go/1.17.5/libexec/src/runtime/proc.go:255
runtime.goexit
	/usr/local/Cellar/go/1.17.5/libexec/src/runtime/asm_amd64.s:1581
github.com/iawia002/lux/extractors.Extract
	/Users/iawia002/go/src/github.com/iawia002/lux/extractors/extractors.go:54
github.com/iawia002/lux/app.download
	/Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:278
github.com/iawia002/lux/app.New.func1
	/Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:255
github.com/urfave/cli/v2.(*App).RunContext
	/Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
	/Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main
	/Users/iawia002/go/src/github.com/iawia002/lux/main.go:13
runtime.main
	/usr/local/Cellar/go/1.17.5/libexec/src/runtime/proc.go:255
runtime.goexit
	/usr/local/Cellar/go/1.17.5/libexec/src/runtime/asm_amd64.s:1581

**Comment by SONGjiemo** [comment]
> 

Okay, thank you very much.

**Comment by mhogomchungu** [comment]
CLosing this one as "done".

I can not support "you-get" because they are not offering binaries that are easy to download from github like the rest of supported backends.

**Comment by mhogomchungu** [comment]
New version is out and lux is now officially supported

https://github.com/mhogomchungu/media-downloader/releases/tag/2.3.0
