### ISSUE TITLE
Best audio download

### ISSUE THREAD

**Issue by ricardouk** [mhogomchungu/media-downloader#107]
Hi, great work with media-downloader, small footprint and "straight to the point/downloads", i tried to download some audio from youtube and selected best audio option and i ended up with an mp3 file, as far as i know youtube doesnt use mp3 so im guessing the aac or opus original audio is being converted to mp3, since its being converted it will loose quality, therefore mp3 is no longer the best audio...any chance of enabling "original audio" either aac or opus in the GUI?

Thanks

**Comment by ricardouk** [comment]
just noticed that by selecting "get list" you can select different audio formats using the corresponding code (140 or 251), but i still think the best audio option should download the original audio and not an mp3 conversion of those streams, perhaps a submenu ...original audio and then submenus with aac or opus, for mp3 in my opinion there should be a preset called "mp3 (converted)".

**Comment by mhogomchungu** [comment]
You can do it yourself by following the instructions from here[1]
Steps to do it are:-
1. Go to configure tab.
2. Go to preset option.
3. In the ```UiName``` field, add ```Original Best Audio``` or any other string of your choice.
4. In the ```Options``` field, add ```bestaudio```.
5. Click ```Add```.
6. Finally, click ```Save```.
7. Go back to ```Basic``` or ```Batch``` downloader tab and click ```Options``` and select your preset option.

[1] https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#2-how-to-add-custom-commands-to-preset-list
