### ISSUE TITLE
Open source extension

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#109]
Hello, I found this video open source extension which has a preset to send links automatically to youtube dl download manager , maybe this extension can be associated with Media-Downloader for more simplicity for beginners:

https://github.com/rowrawer/stream-detector/

I also found this open source extension to send download links directly to the download manager:

https://github.com/FreeDownloadManagerTeam/fdm-addons-docs

**Comment by trimechee** [comment]
The description ot this open source extension says : "Also assembles readymade youtube-dl (yt-dlp)/FFmpeg/Streamlink/hlsdl/N_m3u8DL-CLI commands which (should) include all of the necessary cookies and headers."

**Comment by mhogomchungu** [comment]
The FAQ has this[1] entry that explains how to quickly send url to MediaDownloader from a web browser.

[1] https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#7-how-do-i-create-a-context-menu-on-chrome-or-firefox-to-open-links-in-media-downloader

**Comment by trimechee** [comment]
Thanks, but I thought maybe these extensions have a simpler process for the newbies!

I was wondering if Media-Downloader can natively integrate and perhaps modify this extension for better integration and efficiency because many video extensions are not open source and are full of ads, for more efficiency, integrate this extension to embeded download videos from streaming sites by integrating this open-source extension? because yt-dlp cannot download certain embedded videos from streaming sites, for example these streaming and sports replay sites:


https://wiflix.city/serie-en-streaming/19929-attack-of-the-titans-saison-4.html


https://ourmatch.me/


http://livetv.sx/enx/video/

https://myfootball.top/index/0-2

**Comment by trimechee** [comment]
I find also this open source extesnion, Bulk Media Downloader is integrated to external download managers and to detect and download media resources from online video embeded streaming sites  : 

https://github.com/inbasic/bulk-media-downloader/

**Comment by trimechee** [comment]
and also

https://github.com/downthemall/downthemall

**Comment by trimechee** [comment]
and also : https://github.com/Unrud/video-downloader

**Comment by mhogomchungu** [comment]
> and also : https://github.com/Unrud/video-downloader

This is a GUI tool, cant have a GUI tool as a front end to another GUI tool.

**Comment by trimechee** [comment]
Yes , excuse me, i was thinking it is web browser extension addon lol

**Comment by trimechee** [comment]
i find a new extension, may be Media-Dowloader may use the same mechanism to add a streaming detection extension and send it to media-downloader:

Free Download Manager removes support for YouTube downloads because apparently google asked them to remove youtube support so a user invented a new open-source extension for FDM which can download youtube:


https://github.com/meowcateatrat/elephant

https://www.ghacks.net/2021/10/21/free-download-manager-removes-support-for-youtube-downloads/


https://www.freedownloadmanager.org/board/viewtopic.php?f=1&t=18630

**Comment by trimechee** [comment]
Hello, in case our beloved Media-Downloader will make a new generation of extension, i discover this awesome and incredible scripts of hoothin, among his scripts, there are these scripts, maybe Media-Downloader can add these scripts to extend even more other download features, thank you !

-DownloadAllContent
Fetch and download main content on current page, provide special support for chinese novel

-Easy Offline
Find out all magnet links and torrents and video links in current page, and stream them from cloud storage automatically.


-True URL downloads
Decryption and Display the real URL of the download links and then manage them.(thunder,flashget,qqdl)




-DownloadAllContent
Fetch and download main content on current page, provide special support for chinese novel

Script for download novel or text content on page.

Lightweight crawling script, used to download the main text content of the webpage, theoretically suitable for any non-Ajax novel website, forum, etc. without writing any rules for that.

The script will automatically retrieve the main content on the page and download it.

If you are in the novel catalog page, it will traverse all the chapters, sort and save them as a TXT file.




https://greasyfork.org/en/scripts/25068-downloadallcontent



https://greasyfork.org/en/scripts/7362-true-url-downloads


https://greasyfork.org/en/scripts/22590-easy-offline


https://github.com/dodying/UserJs/tree/master/novel/novelDownloader

https://greasyfork.org/en/users/8227-hoothin


https://github.com/hoothin/UserScripts

**Comment by trimechee** [comment]
I find new script : Download any thing

https://greasyfork.org/en/scripts/446385-download-any-thing

**Comment by trimechee** [comment]
I discover very very powerful amazing scripts to donwload all types of videos or discover media source extension tools :

https://greasyfork.org/fr/scripts/445751-unlimited-downloader


https://github.com/Momo707577045/m3u8-downloader/blob/master/README-EN.md


https://greasyfork.org/en/scripts/18671-inject2download



https://github.com/acolwell/mse-tools


 ArtPlayer.js is a modern and full featured HTML5 video player

https://github.com/zhw2590582/ArtPlayer

https://artplayer.org/



https://www.v2ex.com/t/856510



https://github.com/zhw2590582/bilibili-live-recorder



https://github.com/dabaisuv/Tampermonkey-Script/commit/d10978268b1bda38fcbe1a75e0aaa2665409ac6f



https://segmentfault.com/a/1190000025182822




https://github.com/zhw2590582/live-video-study-notes



https://github.com/zhw2590582/FlvPlayer

https://flvplayer.js.org/

**Comment by trimechee** [comment]
Hello, many and many video and streaming sites use HLS m3u8,  our beloved Media-Downloader can become even more powerful by adding natif support of these extension to detect embeded hided crypted streams  and download  HLS streams, these ope source extensions to download crypted HLS streams may help may be, thank you very much !


https://github.com/chandler-stimson/live-stream-downloader

https://github.com/zaidka/cliget


https://github.com/globocom/m3u8

https://github.com/HeiSir2014/M3U8-Downloader


https://github.com/hestyle/m3u8_downloader

https://github.com/kz26/gohls

https://github.com/Last-Order/Minyami

https://github.com/Momo707577045/m3u8-downloader

https://github.com/Momo707577045/media-source-extract

https://github.com/nilaoda/N_m3u8DL-RE

https://github.com/puemos/hls-downloader

https://github.com/Spark-NF/hls-downloader


https://chrome.google.com/webstore/detail/m3u8-finder-and-hls-playe/gijhpnmjcpbddpedmmdihijogkkejfgj?hl=en

https://www.hlsloader.com/


https://github.com/rowrawer/stream-detector

**Comment by trimechee** [comment]
I found another open source extension that may be can have integration with Media-downloader :

https://github.com/puemos/hls-downloader
https://puemos.gitbook.io/hls-downloader/

**Comment by trimechee** [comment]
And 

EDIT : and :
https://github.com/AminBhst/brisk-browser-extension

**Comment by mhogomchungu** [comment]
Media Downloader has a CLI interface and extensions can use it to give Media Downloader media to download.

Stream detector for example is well supported in Media Downloader.

**Comment by trimechee** [comment]
Great ! Thank you so much :) 🥇
