### ISSUE TITLE
Download books

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#110]
Hello, is there a way that Media-downloader can fetch and download hndreds of these books of these online huge libraries ? it is useful if we would like to download all the books of the same author in one click.

https://www.pdfdrive.com/

and 

https://fr.z-lib.org/

**Comment by mhogomchungu** [comment]
Media Downloader is just a GUI front end to other tools that do the actual downloading.

If you want support for this websites, first find a CLI based program that can download their link and then ask Media Downloader to sadd upport for the program

**Comment by trimechee** [comment]
Interesting, thank you very much :)

**Comment by trimechee** [comment]
Hello, tou said "Media Downloader is just a GUI front end to other tools that do the actual downloading. If you want support for this websites, first find a CLI based program", if I understood correctly, Media-Downloader is not just a GUI for yt-dlp and aira2 ?

there is this popular software, Streamlink is a command-line utility which pipes video streams from various services into a video player, such as VLC.....

I confess I have never tried this program because it seems difficult to use but I would like to use it because the web browser could be heavy and the video jerks..... so our beloved Media-Dowloader can make this work CLI based program?

https://streamlink.github.io/
