### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#111]
Hello, sometimes i download too big file using yt dlp and not aria2, so it takes a lot of time to download, and i go to surf in another websites and after some time, I find another videoS to download but i can't anymore add them to Media-Downloader because it is already downloading another video and the add button are greyed out, so it will be amazingly and useful to allow Media-Downloader to have multiple instances so we will be able to add new videos to Download-Manager, thanks a lot !

**Comment by mhogomchungu** [comment]
You are using windows, right?

To make Media Downloader using multiple instances do, use of the two below methods:-

Method One.
1.Right click the application icon on the desktop and then select ```properties```.
2. Go to shortcut tab and then in the "Target" text field, add a space character and then add ```-s```. This ```-s``` option tells Media Downloader to start up without checking if there is another instance or not.

Method 2.
1. Open Media Downloader settings file and then change ```SingleInstance``` option to false. One of your comments earlier suggests you know where the settings file is so i am not explaining how to locate it.

**Comment by trimechee** [comment]
Wouahh that's awesome and easy ! Thank you very much !
