### ISSUE TITLE
Facebook watch link format

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#112]
Hello, i have multiple facebook videos to donwload, i use batch donwloader to add this link : 
https://www.facebook.com/watch/?v=733475611144776

but it doesn't work, there is no download in batch donwloader, so I tried basic dowloader and it works, i can donwload the same video : 

https://www.facebook.com/watch/?v=733475611144776

i go back to batch donwloader and I add this link of the same video  by clicking on the three dots under the facebook video and clicking on "copy link", finally I was able to download this facebook video using this link;

https://fb.watch/cDPOh4B4zD/

and so, what is the difference between the two links? is it possible to add the classic facebook links to the batch donwloader please? because it's easier, in the address bar of chromium and chrome, there is a "copy link" box which allows me to quickly copy the dacebook links but I can't use them in batch downloader... ..

**Comment by mhogomchungu** [comment]
What error did you get when the link did not work in batch downloader?

I suspect the reason is because "Enter Options" field had an entry that does not work with facebook links. Make sure the text field is empty and try again.

**Comment by trimechee** [comment]
Yess i tried again with another facebook link and it works ! Thank you veru much !👍
