### ISSUE TITLE
Unify and merge"paste from clip board" and "Download"

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#114]
Hello, Please I have an important suggestion, I finally discover the button "paste from clipboard" and it is wonderful magnificent !! thank you ! please it will be great to make the button "download" next to the "paste from clipboard" button for more speed, and also it will be amazing to merge and unify the "paste from clipboard" and "download" buttons into a single button with memorization of the "worstaudio" preset, so we can download audio or video just by clicking on a one and only unified button and we no longer need anymore to click on 2 distant buttons "paste from clip board" and "Download"!

I would also like to share this magnificent program with my friends and my family but many do not understand computers, it will be easier for them if the amazing Media-Downloader add the "worstaudio" and "worstvideo" option because it is necessary for those who have a weak internet connection....

**Comment by mhogomchungu** [comment]
A normal use case is adding a number of entries to download and then clicking "download" button when done adding and combining "paste from clipboard and start downloading"  means adding another button that combines these two operations to support this extra usecase.

Making the "paste from clipboard" next to "download" button will alter the UI in a way i do not like.

For now, i do not think this convenience warrants cluttering further the UI.
