### ISSUE TITLE
Scale factor

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#115]
Hello, I set scale factor to the value "3", and when I wanted to restore the default value "1", I could not access the scale factor parameter because the window was too large and the parameter inaccessible, so I I had to uninstall the program and search in the hidden folders of windows appdata ...... to delete and reset Media-Dowloader, it will be good if this process becomes easier or the window becomes scrollable, or have the "reset" button " at the very top of the main window....

**Comment by rollodroid** [comment]
I wanted to try 0.5 and now the UI is completely broken and I can't change the setting back. The UI is buggy as hell. The window is not even resizeable. Causing problems for users with low resolution.

**Comment by mhogomchungu** [comment]
Will remove this option from the UI because its not easy to reverse it from the UI when a user put an option that messes up the UI too much.

The main window not resizable is by design.

**Comment by trimechee** [comment]
My laptop broke down recently so I am currently using a small laptop from 2012 and I have no scaling problem with the default settings of Media-downloader!

i can't watch videos in supermium, thorium legacy, catsxp because streaming video lag even youtube because video lag in my old laptop so media downloader becomes vital for me and surely for other millions of people and machines who still use 32 bit windows 7 os and I was relieved to see that our beloved Media downloader is compatible with windows 7 32 bit and I hope that will always be the case please Mr Mhogomchungu  :)
