### ISSUE TITLE
Watch while donwloading

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#117]
Hello, some video ar too big, and we want to watch the beginning of the video which has already been downloaded, it will be great to add this option for more simplicity and if this option is selected, Media-Downloader should use only one thread ti download the beginning of the video and for smoother viewing....

**Comment by mhogomchungu** [comment]
Yt-dlp has this behavior by default, it opens a single connection and download the file from the beginning to the end.

If you give yt-dlp a youtube Url without any options, it will first download the best video only file and then the best audio only file and then combine them locally to an audio+video file.

Download a video with audio+video already combined(they usually have an id of 18 or 22) and you should be able to watch it as you are downloading it.
