### ISSUE TITLE
Audio book and torrent books podcast

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#118]
Hello, does Media-Downloader support downloading audio books and podcast ? and the p2p torrent download of audio books torrent like on this site ?

https://librivox.org/

https://www.digitalbook.io/

**Comment by mhogomchungu** [comment]
Both those links offer their audio books as a zip file or a torrent file.

Media Downloader supports aria2c[1] and you can use it to download regular files from internet and torrents. I have not tested Media Downloader running aria2c to download a torrent so i do not know what output Media Downloader will display but it should work. 

For convenience, you can configure Media Downloader to autoset aria2c as a downloading engine everytime it sees a Url with a .zip extension or a Url from "https://librivox.org/"

[1] https://aria2.github.io/

**Comment by trimechee** [comment]
Awesome ! Thank you so much for your advices !
