### ISSUE TITLE
Proxy vpn 

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#119]
Hello, sometime i watch sone foreign tv shows, i use, psiphon....or may be  proton vpn, or SoftEther VPN Gate Client Plugin....does Media-downloader support downloading through proxy and vpn ?

**Comment by mhogomchungu** [comment]
Media Downloader does not do the actual downloading, that part is done by yt-dlp and you will have to consult its documentation for more info.

I have never used VPN so i do not know how well it works with them.

Yt-dlp project page is here:- https://github.com/yt-dlp/yt-dlp
