### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#120]
I found this commentary in videohelp website, what do you think ? qt is better than java ?

"A straight-to-the-point GUI, without bells and whistles.
Built upon Qt 5, therefore it works under Windows 7.
But it would be better if the GUI was written in Java, because the Qt framework turns any application into bloatware."

https://www.videohelp.com/software/media-downloader/reviews

**Comment by trimechee** [comment]
Thank you for these clarifications! i heard that qt6 is getting paid and not open source anymore and it angered linux community and kde based distro whose development is in danger, and Media-Downloader is using qt5, i am not expert but it  seems that qt5 is old, can Media- Donwloader could consider using python instead of qt ? ok i love qt because it's fast light but maybe python applications are more efficient....

**Comment by mirh** [comment]
https://github.com/crystalidea/qt6windows7

**Comment by trimechee** [comment]
@mirh Very interesting ! Thank you for sharing this interesting infrmations ! :) 👍 💯
