### ISSUE TITLE
Option suggestions

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#123]
Hello, it will be great if there is these options : prompt when finishing warning to signal the end of downloads, show notfication when fiish dowloading, show non resumable donwloading file, show warning when disabling ssl verification, auto rename files if same name exists in dowload folder, network option with proxy prefix : htttps, socks4, socks5, websites authentification option user password, workarounds cookies file, custom user agent, ignore ssl certificate validation....

all these options are inspired by the "FireDM" download manager options, and it will be great and we are grateful if Media-Downlaoder gradually integrate them....

another question please, are you considering to changing the name of Media-Dowloader ?

**Comment by mhogomchungu** [comment]
1. What is a "non resumable download"? Media Downloader can not know in advance and it will be up to a CLI tool to say so and its error message should be enough to inform the user of Media Downloader.
2. What type of notification do  you expect to see? a pop up window?a tray icon pop up ? a system sound?
3. It already possible to set those network options, cookies and passwords in configure->engine default options.
4. I think i will change the name at some point in the future and i am not sure when.

**Comment by trimechee** [comment]
I often use windows 10 night light to disable blue light , the screen becomes very orange color and I have enabled Media-Downloader dark theme, so sometimes it's not obvious when Media-Downloader finished downloading several files, I have to read "donwload completed" to be able to close the program, so it will be great to add a warning, a popup or a blink, or a warning sound so we can close Media-Downloader directly without having to read a small writing in size especially if the Media-Downloader window is small, and above all, the most important thing is to add a manual update button, beginners don't know how to do it, myself I don't know how to update Media- Downloader so I had to go to the Media-Downloader github page and download Media-Downloader again to get the new version, the "updated" button should also update yt-dlp, because sometimes it is difficult for beginners to go dig into the settings and find where the yt-dlp engine is to update it, it will be nice to have automatic updates every week as soon as the program starts and a manual update option, thank you a lot !

when you pause a download, and quit it, then open the download manager, some files are downloaded from the start, forgetting what was downloaded previously, some download maager display the mention "non resumable download" so we know wh shoud not stop or pause the download of the file.....

**Comment by mhogomchungu** [comment]
Its been years now and most of the suggestions here are already implemented.
