### ISSUE TITLE
The end of FireDM , a threat for open-source projects ? urgent need to preserve source code

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#124]
Hello, I was using FireDM dowload manager which had a lot of options, then the repository strangely disappeared from github a few days ago that's why I searched for alternatives and found Media-Downloader...... I'm went to his site and there was an update and i didn't install it, and i was right because people say in this reddit post

https://www.reddit.com/r/Python/comments/u44t8y/firedm_repos_no_longer_exist/

 that the latest update deleted all functions related to "youtube_dl". Apparently somethings happened before the author made such a huge change. Maybe DMCA or the author is pissed off by YouTube.
 here some comments:
So, it is dead.

Was wondering why my FireDM didn't work anymore after I update it. Oh well, lesson learned, always backup before committing to update.

There was an update today which I blindly accepted. But it didn't work anymore after the update. So I rolled back to an older version binary:

https://www.videohelp.com/software/pyIDM/old-versions

forked repositories get deleted alongside the original repository in case of copyright violation or Term of Service policy violation

Doesn't seem to be the case here. Forks of it do exist. May be an error on GitHub's end - or FireDM may have gone private.

https://github.com/GurucharanSavanth/FireDM

I wonder if Media-Downlader can archive and preserve the source code of this magnificent project on sourceforge, or gitlab or archive.org.....because maybe DMCA bans such projects and asks github to ban them, c already happened to youtube-dl which was banned from github and its code rewritten to remove the DRM part.....

**Comment by mhogomchungu** [comment]
It does not make sense why he decided to delete it and most people simply walk away without saying anything or leave a note asking for somebody else to take over the project when they no longer want to work on it.

youtube-dl subreddit has a list of open source projects that deal with media downloading and the list is [here](https://www.reddit.com/r/youtubedl/wiki/info-guis).

Old tools drop out for various reasons and new ones come in all the time and i am sure there will always be tools people can use to download media.

**Comment by trimechee** [comment]
yes it's strange surprising this sudden disappearance, maybe the project was becoming more and more popular and the press was talking about this program and some people don't like it and the developer has received threats ..... some managed to save the source code anyway:

https://github.com/afzl-wtu/firedm


https://www.reddit.com/r/Python/comments/u44t8y/firedm_repos_no_longer_exist/?sort=new



here what github says about the come back of youtube-dl : 

https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/
