### ISSUE TITLE
Impact of the war in Ukraine on open-source projects

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#125]
Hello, can the Mredia-Downloader project be affected by the terrible war in Ukraine?

this article says "GitHub can't be trusted. However, how suspending Russian accounts deleted project history and pull requests"

"That should definitely be reasoning in the merge commit.

PRs are a tool to handle change requests and reviews. They are not the code history documentation and persistence. (They may be used for additional in-depth context and argumentation - history of how you came to decisions and understandings.)

If you include PRs in your inner documentation scope, that means you will always have to navigate between the two systems. I hate that when I see it in projects.

I hate projects where I see a release, have to look up commits, the changes list or commits point to PRs, the PRs to tickets, and the tickets are highly context specific, without a summary at the start or end. So I have no way to reasonably evaluate what changed in a version, and evaluate risk.

The git commits should be enough to understand changes. Reasons, side effects, and risk or accepted short comings should be documented in them.

Maybe not in your small personal projects, but it becomes more and more important with other collaborators, and especially so when other people and projects depend on yours."

https://old.reddit.com/r/programming/comments/u7yf0q/github_cant_be_trusted_or_how_suspending_russian/

**Comment by mhogomchungu** [comment]
I am an African who lives in Africa and the only way i can think of the war affecting me at a personal level is maybe in higher prices for good and services in my country.

Media Downloader can be affected only through the Russia language translator stopping providing translations and he is still providing them and the last time he provided translations was about two weeks ago:.

In Summary, i do not think this project will be affected by the war in Ukraine.
