### ISSUE TITLE
Qt

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#126]
Hello, you have the kindness to explain to us earlier that you prefer to use qt5 because it is compatible with windows 7, it's very good and excellent for those who use windows 7, thank you very much !

but windows 7 is no longer officially supported by microsoft and it may have outdated security and update issues and many have migrated to windows 10 or windows11, can you please add a new special version of Media-Downloader using the new Qt6 which seems to have introduced several improvements and options ?

**Comment by mhogomchungu** [comment]
Here[1] we see a user of Media Downloader who is using windows 7. Yes, it is no longer in support but there are users who are using it.

I will continue to use Qt5 version 5.15.2 and here are my reasons:-
1. It is the last version of Qt that supports windows7
2. I use KDE on linux and it uses Qt version 5.15.2. Going to Qt6 on windows will means developing on two different MAJOR versions of Qt and that sound like unnecessary extra work for me.
3. 
[1] https://github.com/mhogomchungu/media-downloader/issues/134

**Comment by trimechee** [comment]
Yes we understand, thank you :)

**Comment by mhogomchungu** [comment]
There is now a Qt6 build for windows.

https://github.com/mhogomchungu/media-downloader-git/releases/tag/0.0.0

**Comment by trimechee** [comment]
Fantastic ! Thank you :) 🥇
