### ISSUE TITLE
Streamlink GUI 

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#127]
Hello, you expplain to us "Media Downloader is just a GUI front end to other tools that do the actual downloading. If you want support for this websites, first find a CLI based program", if I understood correctly, Media-Downloader is not just a GUI for yt-dlp and aira2 ?

there is this popular software, Streamlink is a command-line utility which pipes video streams from various services into a video player, such as VLC.....

I confess I have never tried this program because it seems difficult to use but I would like to use it because the web browser could be heavy and the video jerks..... so our beloved Media-Dowloader can make this work CLI based program please ?

Media-Downlaoder will become the only software in the world to make Gui for the streamlink software !

https://streamlink.github.io/

**Comment by mhogomchungu** [comment]
This tool takes a URL, extract a media URL and then starts another tool and give it the extracted media URL for the other tool to start playing it.

This tool does not do downloading and hence its outside the scope of Media Downloader.

**Comment by trimechee** [comment]
Interesting, thank you for your explications :) recently,  Mr vzhd1701 has added support for streaming URLs, which allows playing any URL that is supported by streamlink or yt-dlp plus mms, mmsh, rtp, rtsp and udp protocols to the beautiful Gridplayer https://github.com/vzhd1701/gridplayer
