### ISSUE TITLE
Automatically choose and download the standard video quality with one click without merge dash video and dash audio streams

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#129]
Hello, I think the most important option is that of being able to quickly and automatically choose and download the video in standard quality with one click without merge dash video and dash audio streams, it will be great if Media-Downlaoder adds a preset for newbies, a "medium" preset, i.e. Media-Dowloader automatically selects and downloads the standard medium quality from streaming platforms like mail.ru which offers 380p and 1080p videos....without using merge dash video and dash audio streams for faster downloading because for example, 480p quality requires downloading audio and video streams separately and merging them....while standard 380p quality does not require this process which requires extra cpu power

https://my.mail.ru/v/goal_net_ru/video/30/1259.html

**Comment by mhogomchungu** [comment]
The preset list is already too long and its not wise to add a default preset entry for every possible use case.

Youtube is special and this is why majority of preset options are for youtube. All other websites should be content with default preset options for other websites i just added. Anything extra and users should add their own preset option that suits their needs.

**Comment by trimechee** [comment]
Yes you have right, thank  you for your precious explanations :)
