### ISSUE TITLE
Youtube-dl scripts

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#130]
Hello, Youtube-dl scripts are helpful scripts that use youtube-dl (and some that don't, e.g. the livestream recording scripts, because they fulfill a need that youtube-dl and streamlink no longer is able to do), can Media-Downloader integrate these scripts ?

https://www.reddit.com/r/youtubedl/wiki/info-scripts

**Comment by mhogomchungu** [comment]
These are front ends to youtube-dl and some of them run in a web browser or file manager context menu.

As front ends, these scripts do the same thing Media Downloader does and it make no sense to go through them to do anything.

If their functionality is useful then the best thing to do is to add the functionality in Media Downloader itself.

**Comment by trimechee** [comment]
Interesting, thank you very much for these important clarifications :)
