### ISSUE TITLE
Reddit

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#131]
Hello, here is a reddit post that lists youtube-dl GUI's projects and I'm happy to discover that our beloved Media-Downloader is there, can Media-Downloader make a page on reddit to communicate with its users and for better exposure of this exceptional magnificent project ? maybe it will attract even more lots of people who can make a donation to support and sponsor the development of this awesome project !

https://www.reddit.com/r/youtubedl/wiki/info-guis#wiki_media_downloader_by_.2Fu.2Fmuungwana

**Comment by mhogomchungu** [comment]
Online forums requires time commitment to fend of spam mostly, rules and moderators.

I am ok with somebody else creating a subreddit for the program and i will do my best to be an active participant and answer questions but i don't think i will have the time to run it full time.

**Comment by trimechee** [comment]
That's understandable, thank you 👍

**Comment by trimechee** [comment]
Hello, after your agreement, I will try in sha Allah to make a Media-Downloader page on reddit but I would specify that I am not the developer and that you authorized me to make this page

**Comment by mhogomchungu** [comment]
Time has shown there is no interest in creating a dedicated reddit channel to talk about Media Downloader and i think this place is good enough.

**Comment by trimechee** [comment]
Apparently I forgot, or I gave up because if the Media-downloader page on reddit is not official and is not directly supervised by the developer, it would have little interest and angry users can insult me ​​by telling me what are you getting involved in and why make the page if the developer does not supervise it..... and so I thought it was not worth it... but I will try to do it :)
