### ISSUE TITLE
Preset description section

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#132]
Hello, we can use the awesome Media-Donwloader without difficulty but for even more simplicity and ease for newbies and beginners who don't understand anything in computer science, I propose to add directly in the "preset option" section of our benloved Media-Donwloader a list of the most important presets, for example the sponsorblock preset, preset to convert to another format, worst audio and wordst video preset, preset the fast medium video without dash format and merge and without conversion and use ffmpeg .....

I know there is a wonderful help section on github but people don't necessarily know how to search and read and understand English and these technical aspects and add these presets themselves, or make a github account to ask questions .....c why I think it will be useful and easier to directly add the most useful and popular presets directly in Media-Dowloader, not necessarily include them by default but just add the description of the presets in a special section of Media-Downloader and add by default the worst audio worsrt video and preset fastest medium video 360p without merge and without dash format...... because I noticed that even in the github help section of Media-Dowloader, there is no complete list of presets that can be added...... thank you very much !

**Comment by mhogomchungu** [comment]
The preset list is already too long and its not possible to add an entry for every possible use case.

The current list as it exists today i think covers all basic use cases and users should just be informed on how to add extra entries that suits their use cases.

**Comment by trimechee** [comment]
Yes, you have right, thank you :) 💯
