### ISSUE TITLE
Update mechanism

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#133]
Hello, I am glad to discover that there is a new outstanding release of Media-Downloader and I try to download it through the program but I can't, so I have to download Media-Dowloader again from its github releases page to get the last version ? in Media-Downloader, apparently there is a button to update yt -dlp maos not to put the whole program, if so, it will be great to add a button "check and install updates " which warns us and takes us to this github releases page in order to download new version of Media-Downloader :

https://github.com/mhogomchungu/media-downloader/releases/tag/2.3.0

I noticed that there are two versions MediaDownloader-2.3.0.setup.exe and MediaDownloader-2.3.0.setup.exe.asc, what is the difference between setup.exe. and setup.exe.asc please?

**Comment by mhogomchungu** [comment]
Explanation for the .asc file is here[1]. Basically, you can use the file to verify that the setup executable came from me.

[1] https://fileinfo.com/extension/asc#:~:text=An%20ASC%20file%20is%20an,binary%20information%20encoded%20as%20text.

**Comment by trimechee** [comment]
Very useful, thank you :)

**Comment by mhogomchungu** [comment]
Progress on this one, i just added code that has an option to checks on startup if running version is the latest one or not.

![Screenshot_20221003_201130](https://user-images.githubusercontent.com/3496115/193639185-1c0062fc-8432-4622-93e4-606bfd603eaa.png)

**Comment by trimechee** [comment]
Great ! thank you very much !! i think it may be sufffisient in order to update to  just to show pop-up ou make github button which takes us to the github releases page of the Media-Downloader so we can download the new version with just one click ! 

https://github.com/mhogomchungu/media-downloader/releases

**Comment by mhogomchungu** [comment]
The app can now auto update on windows.

![Screenshot_20230324_155738](https://user-images.githubusercontent.com/3496115/227529229-328ab71d-ce27-4a73-9a27-a5d1558d3fa5.png)

**Comment by trimechee** [comment]
Great !! Thank you very much !! i tried and discuss with many developers since the death of "firedm" downlaoder and always Media-downloader remains the best downloader and the great developer who listens to suggestions and improvements despite the difficult requests !! and since I have tried many downloaders and i discuss with many developers about bugs and features....Media-downloader is without a doubt the number one and the best downloader and it is the downloader with so many awesome options and outstanding amazing tools not found in other downloaders ! 🥇 💯 
I think it will be a good idea to open on github the possibility of sponsoring the project or via Ko-fi or buy me a coffee and making donations could guarantee the sustainability of this project !

**Comment by mhogomchungu** [comment]
1. I live in Tanzania and most if not all online based payment system do not work here.
2. Bitcoins works but not that may people have them.
3. Bank transfers/Western Union/Moneygram among other "traditional" money transfer options are too inconvenient and processing fees are too high.

**Comment by trimechee** [comment]
Ohhc it's sad :( this is problem even in other african country.... we hope that our African continent can be connected more easily to these international payment tools so that talented African developers can be rewarded for their work and can rework with big tech companies multinationals in sha Allah .....
I see that sometimes some developers ask users to click on advertisements and sponsored ads and this brings them an income, maybe make a blog where there will be links and descriptions of all the magnificent tools you are developing and ask users to  go there and click on the ads and watch the  videoads to support you....or make youtube videos about the new options of Media downloader and ask the users of Media downloader to watch many ads in youtube video in order to support the project...
