### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by JonnyThree** [mhogomchungu/media-downloader#134]
Hello i have found this tool and i think it's very well concepted, but i have some high cpu usage (around 25-30% on a old xeon e5450) by the main executable "media-downloader.exe" when i download hls-dash streams. I'm on Windows 7, and other tools doesnt have same high cpu usage when i try to download same stream. Is this a bug?

**Comment by mhogomchungu** [comment]
It should make no different what stream is getting downloaded since all the effort on Media Downloader side is getting yt-dlp output and process it for displaying in its GUI.

Can you download something else and observe if the CPU is the same or not.

**Comment by JonnyThree** [comment]
with other tools i dont have high cpu usage downloading the same dash stream, so i think the problem is related to media-downloader gui. i am not reporting the package name of the other tool only for preserving the publishing respect of this great package. p.s.: sorry for my bad english...

**Comment by mhogomchungu** [comment]
I have reworked how logs are processed and kept and performance should improve.

Closing this one as fixed.

**Comment by mhogomchungu** [comment]
New version is out and it should be less resource intensive now

https://github.com/mhogomchungu/media-downloader/releases/tag/2.4.0

**Comment by JonnyThree** [comment]
Thanks very much, i will try it

**Comment by mhogomchungu** [comment]
Are you using basic downloader tab or batch downloader tab?

Try again with batch downloader tab if you are using basic downloader tab.

**Comment by JonnyThree** [comment]
In the new version the high cpu usage problem is not present, thanks so much for your work. sorry for my answer that is coming a little late
