### ISSUE TITLE
Media-downloader 2.3.0 - translation issue

### ISSUE THREAD

**Issue by bovirus** [mhogomchungu/media-downloader#136]
@mhogomchungu 

I updated the italian language.
I made a PR.

https://github.com/mhogomchungu/media-downloader/pull/135

I found some issues in tranlstiopn about GUI

![image](https://user-images.githubusercontent.com/1262554/166210013-fdee6045-1078-4f99-9fb1-d5f12d75597e.png)

![image](https://user-images.githubusercontent.com/1262554/166210049-81539d8f-82a4-49ac-9e34-c6789721bf10.png)

![image](https://user-images.githubusercontent.com/1262554/166210066-5b38a093-34b0-4617-b68b-d21ab06105f6.png)

![image](https://user-images.githubusercontent.com/1262554/166210089-12238c49-3bca-48d2-8c2f-c8d40cd86f33.png)

After you add italian language (and add string to select "Italian (Italy)" in language list please add missing strings.

**Comment by bovirus** [comment]
@mhogomchungu 

When you made changes to source code please use in **_/src_** subfolder the command

**lupdate -no-obsolete -no- -disable-heuristic sametext -disable-heuristic similartext -disable-heuristic number languagefilename.ts**

this update all .ts language file to the latest list of striung
removing obsolete strings
disable adding heuristic translation for similartext, sametext, number

Cuurently the .ts language file seems not aligned (169 striungs instead 170).


Thanks.

**Comment by mhogomchungu** [comment]
How do you write "Default" in Italian?

**Comment by bovirus** [comment]
@mhogomchungu 

Please take care thta in italian (as in other languages) the same term in different context could be male or female.

1. Predefinita (if referred to resolution that is female)
2. Italiano (Italia)
3. Versione Qt

Note: if you have same term (like Default) in different context please use different strings because the translaton can be different.

**Comment by mhogomchungu** [comment]
Thank you.

Life took an unexpected turn and I will get back to this in about 10 days.

**Comment by mhogomchungu** [comment]
Git version has fixes for UI issues you have identified.

![Screenshot_20220515_122852](https://user-images.githubusercontent.com/3496115/168466281-ae1ce0cd-b2f6-4347-af1e-a0684b8903b5.png)
![Screenshot_20220515_122947](https://user-images.githubusercontent.com/3496115/168466289-257f9fe8-7e47-494b-bf89-abdd305d55b2.png)
![Screenshot_20220515_123024](https://user-images.githubusercontent.com/3496115/168466290-866ae098-762d-432d-bdca-8c3fa3d40458.png)

**Comment by bovirus** [comment]
@mhogomchungu 

Thanks for the update.
I will check in new reelase.

I made a PR for the italian lnaguage update.

**Comment by bovirus** [comment]
@mhogomchungu 

New PR for Italian language update

Please release a enw version to take care if all fixes are in place.

**Comment by mhogomchungu** [comment]
[New version is out](https://github.com/mhogomchungu/media-downloader/releases/tag/2.4.0) and thanks for your contributions.
