### ISSUE TITLE
White noise audio

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#141]
Hello, i found this rare exceptional sound which is the amazing combination of White Noise + Rain which cancels the ambient noise, i tried to download using yt dlp and video extensions like videodownloadhlper but i did not succeed, i did not I only managed to download a little piece of 30 seconds sound.....
can our beloved Media-Dowloader allow us to download this rare sound please? I just want to download this sound and not the other sounds on the site, this sound is free but I still have to be connected to the internet that's why I want to download it for offline use....thank you very much :)

https://mynoise.net/NoiseMachines/whiteRainNoiseGenerator.php

**Comment by mhogomchungu** [comment]
My understanding of the site says there are 20 different sounds that play and you hear different sounds depending on their respective volumes.

Looking at the website source code  and the urls to the 20 audio files are given with a below simple formular.

https://cdn.mynoise.net/Data/RAIN2/Xb.mp3
https://cdn.mynoise.net/Data/RAIN2/Ya.mp3

where X ranges from 0 to 9 and Y also ranges from 0 to 9

Once you have constructed a url, put in your web browser and your browser should be able to download it. Media Downloader should also be able to download them if you use aria2c or wget engines.

**Comment by trimechee** [comment]
Absolutely sensational ! thank you very much for your precious help !

**Comment by trimechee** [comment]
Audio or video format are not important because audio and video player on windiws 10 and on android can play any media codec like vlc, foobar2000 and many others....it is not a vital function and I understand to keep the program as smooth and clear and easy to use as possible, thank you very much :)
