### ISSUE TITLE
Sponsorblock

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#143]
Hello, many and many videos in youtube include talk about sponsors and ads.....it will be great to add a default preset to add the awesome sponsorblock option specially for the audio files  for exemple a preset with worstaudio sponsorblock....thank you !

**Comment by mhogomchungu** [comment]
One person's feature is another person's bloat they say.

You ask for "worst audio sponsorblock" in an audio format you did not specify.

Somebody else will ask for best audio sponsorblock in mp3 format and another person will come and complain the preset list is too long and confusing to noobs.

All of the current preset options could use a sponsorblock counterpart and it is not practical give each and every one of them a counterpart and the best thing to do i think is to not offer these sponsorbocks preset options.

**Comment by trimechee** [comment]
I undestand, audio or video format are not important and doesn't matter because audio and video player on windiws 10 and on android can play any media codec like vlc, foobar2000 and many others....it is not a vital function and I understand to keep the program as smooth and clear and easy to use as possible, thank you very much :)
