### ISSUE TITLE
After merge show done?

### ISSUE THREAD

**Issue by raelb** [mhogomchungu/media-downloader#144]
Hi,
Is it meant to show "done" after merging?
I have output like this:

    [download] 100% of 7.67MiB at NA ETA NA
    [media-downloader] Done downloading
    [Merger] Merging formats into ".....webm"

It seemed like it was done, but no message about that.
I would expect a message saying "done merging..." 
Thanks

**Comment by mhogomchungu** [comment]
The indicator that everything is done is the UI becoming enabled again.

Do you not notice the UI get disabled when you start downloading and it
gets enabled afterwards?

The "merger" line comes from yt-dlp it is not guaranteed that it is always
there.

**Comment by raelb** [comment]
☺. Well actually I didn't. DL was very slow so I went away from computer, and didn't notice when UI became enabled again. Also new to the program,
Maybe add a line: `Done processing..`
Anyway thanks for the explanation.

**Comment by mhogomchungu** [comment]
Will do that when I get access to my computer again in about a weeks time.

**Comment by raelb** [comment]
👍

**Comment by mhogomchungu** [comment]
Done
![Screenshot_20220520_180203](https://user-images.githubusercontent.com/3496115/169556686-c5716e72-f37e-4e0b-b60e-cca2174a1fe1.png)

**Comment by raelb** [comment]
👍
