### ISSUE TITLE
How do I number videos in a playlist (in order) as they download?

### ISSUE THREAD

**Issue by candrapersada** [mhogomchungu/media-downloader#147]
Hi again everyone. I'll get straight to the point. I want to download (for the sake of the post) this playlist, but as the videos download, I want them to be numbered. What I mean by this is as videos download, I want them to be numbered as video 1, then video 2, then video 3, so I don't have to rename them all when they finish downloading. I'm doing this for a bigger playlist but I don't want to have to rename all the files afterward. For example, it'd be great if I download the playlist above and as the videos are downloading in order (as shown on the playlist on youtube), that they'd be labeled 001 [name of video], 002 [name of video], 003 [name of video], so on and so forth for Tab `Playlist Downloader`

**Comment by mhogomchungu** [comment]
1. Go to configure tab.
2. Go to engine's default option subtab.
3. In the engine name drop down menu, select the engine you are using eg yt-dlp.
4. In the default download options, replace the string after "-o" with 
```"%(playlist_index)s %(title).200s-%(id)s.%(ext)s"```
5. Go to playlist download tab and start downloading and observe that all downloads with start with a number followed by a space and then the name of the downloaded file. There is currently no logic that supports showing the number with a user set numbers of digits. The option "%(playlist_index)s" comes from yt-dlp but media downloader hijacks it and replace it with the appropriate number.

Unfortunately, the above method will break when using other downloader tabs so remove the option when using other tabs or you can be creative and create a custom engine config file based on yt-dlp config file and then add the option and use the engine only with the playlist downloader tab.

**Comment by candrapersada** [comment]
why The option "%(playlist)s/" comes from yt-dlp not working e.g. Playlist name is xxx but what I download is NA?
`"%(playlist)s/%(playlist_index)s %(title).200s-%(id)s.%(ext)s"`

**Comment by mhogomchungu** [comment]
Because yt-dlp does not see the playlist, Media Downloader takes the playlist and then break it down to its individual entries and then run multiple instances of yt-dlp with playlist entries to do concurrent downloading.

For the option ```%(playlist)s``` to work, Media Downloader will have to handle it by itself and these playlist options are handled here:-

https://github.com/mhogomchungu/media-downloader/blob/51fd00f8ea2fc4aa489f36c3902821ea4a33477d/src/engines/yt-dlp.cpp#L657-L674

**Comment by candrapersada** [comment]
what I mean is download videos in respective directory like `"%(playlist)s/%(playlist_index)s %(title).200s-%(id)s.%(ext)s"`

**Comment by mhogomchungu** [comment]
The git version should now support those options. A full list of supported yt-dlp playlist options is here

https://github.com/mhogomchungu/media-downloader/blob/1d79e4e5a6f949e2e1a9637609471b6853f2085a/src/engines/yt-dlp.cpp#L667-L676

**Comment by candrapersada** [comment]
> Unfortunately, the above method will break when using other downloader tabs so remove the option when using other tabs or you can be creative and create a custom engine config file based on yt-dlp config file and then add the option and use the engine only with the playlist downloader tab.

how to create a custom engine config file based on yt-dlp config

**Comment by mhogomchungu** [comment]
1. Download this[1] extension and name it "yt-dlp-custom.json"(you can pick any other name but make sure the ".json" part stays).
2. Open the file with a text editor and change the "Name" field from "yt-dlp" to "yt-dlp-custom" (the name you choose here should match the name you choose in step 1).
3. Install the file by going to configure tab->general options->add a plugin and then select it.
4. Go to playlist downloader tab and set it as "engine name"(it should already be set).
5. Retake the steps i lay out in the first comment here.
6. Go to other tabs and change the engine name to "yt-dlp".
7. Start using playlist downloader tab with your custom plugin.

[1] https://github.com/mhogomchungu/media-downloader/wiki/Extensions#2-yt-dlp
