### ISSUE TITLE
Add support for N_m3u8DL-CLI

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#149]
Hello, since Media-Downloader is an awesome GUI front-end of command line tools , it well be great if our beloved Media-Downloader add support for m3u8 with adding support for this tool updated recently  N_m3u8DL-CLI :

https://github.com/nilaoda/N_m3u8DL-CLI

**Comment by mhogomchungu** [comment]
Can you give an example Url i can test.

**Comment by trimechee** [comment]
URI format:

m3u8dl://<base64 encoded client command line text>

URI example:

m3u8dl://Imh0dHBzOi8vZXhhbXBsZS5jb20vYWJjLm0zdTgiIC0td29ya0RpciAiJVVTRVJQUk9GSUxFJVxEb3dubG9hZHNcbTN1OGRsIiAtLXNhdmVOYW1lICJhYmMiIC0tZW5hYmxlRGVsQWZ0ZXJEb25lIC0tZGlzYWJsZURhdGVJbmZvIC0tbm9Qcm94eQ==



URI decoding result:

"https://example.com/abc.m3u8" --workDir "%USERPROFILE%\Downloads\m3u8dl" --saveName "abc" --enableDelAfterDone --disableDateInfo --noProxy

**Comment by trimechee** [comment]
About the m3u8dl:// protocol
Added command line parameters:

--registerUrlProtocol          注册m3u8dl链接协议
--unregisterUrlProtocol     取消注册m3u8dl链接协议


Support download m3u8 link or file as mp4 or ts format, and provide rich command line options.

Youku video decryption is not supported
Balloon cloud video decryption is not supported
Support AES-128-CBC encryption and automatic decryption
Support multi-threaded download
Support download speed limit
Supports resuming from a breakpoint
Support Master List
Support live stream recording (BETA)
Support for custom HTTP Headers
Supports automatic merging (binary merging or merging with ffmpeg)
Supports choosing to download the specified time period/shard content in m3u8
Supports the case where the download path is a network drive
Support download external subtitle track, audio track
Support merge as audio only
Support setting specific http proxy
Support automatic use of system proxy (default behavior, can be disabled)
Support m3u8dl link protocol (call native client through web link)
Provide SimpleG simple GUI to generate common parameters

N_m3u8DL-CLI

USAGE:

  N_m3u8DL-CLI <URL|JSON|FILE> [OPTIONS]

OPTIONS:

  --workDir sets the program working directory
  --saveName set save file name (excluding suffix)
  --baseUrl set Baseurl
  --headers Set the request header, the format key:value uses | to separate different key&value
  --maxThreads (Default: 32) set the maximum number of threads for the program
  --minThreads (Default: 16) Set the minimum number of threads for the program
  --retryCount (Default: 15) Set the number of retries for the program
  --timeOut (Default: 10) Set the timeout time (in seconds) for program network requests
  --muxSetJson use an external json file to define mux options
  --useKeyFile use an external 16-byte file to define the AES-128 decryption KEY
  --useKeyBase64 Use Base64 string to define AES-128 decryption KEY
  --useKeyIV use HEX string to define AES-128 decryption IV
  --downloadRange download only a portion or length of the video
  --liveRecDur When recording live, automatically exit the software when this length is reached (HH:MM:SS)
  --stopSpeed ​​retry when the speed is lower than this value (in KB/s)
  --maxSpeed ​​set download speed upper limit (unit is KB/s)
  --proxyAddress set HTTP/SOCKS5 proxy, such as http://127.0.0.1:8080
  --enableDelAfterDone Enables the ability to delete temporary folders after downloading
  --enableMuxFastStart Enable the FastStart feature of muxed mp4
  --enableBinaryMerge enable binary merge sharding
  --enableParseOnly Enable parsing-only mode (the program only goes to meta.json)
  --enableAudioOnly Encapsulate only audio tracks when merging
  --disableDateInfo disable date writing in mux
  --disableIntegrityCheck do not check if the number of shards is complete
  --noMerge disable automatic merging
  --noProxy do not automatically use system proxy
  --registerUrlProtocol register m3u8dl link protocol
  --unregisterUrlProtocol unregister m3u8dl link protocol
  --help Display this help screen.
  --version Display version information.

**Comment by mhogomchungu** [comment]
This is not a good backend to add because it has to be run interactively and media downloader has no support for this mode.

By interactively, i mean sometime after it is running, this tools ask questions from the terminal that needs to be answered before it continues and media downloader has no mechanism in place to show the user the asked question and send the response to the tool.

**Comment by trimechee** [comment]
Intesresting ! I think there is no urgent need for this program as our beloved Media-downloader can download from many many sites, thank you very much for taking the time and effort to consider my suggestion :)

**Comment by trimechee** [comment]
Hello @mhogomchungu , sorry to bother you again :( just to say that I discover surprinsing thing !!

After Media-Dowloander did not integrate "streamlink" because it was not possible, I overcame my fear and installed streamlink and it was difficult at first and I didn't understand anything and I didn't know what to do but finally I succeEd to use this program command line CLI , and after your answer, I said to myself come on I can perhaps succee to use N_m3u8DL-CLI without a graphical interface and there I go to the releases page and I find out this !!! :


N_m3u8DL-CLI-SimpleG.exe

so "N_m3u8DL-CLI" seems to have GUI grapical interface !!!

here its description :

"Considering that most of the users feel cumbersome operation experience when using the command line program, I developed it to automate the production of most parameters, which greatly improved the efficiency Download N_m3u8DL-CLI-SimpleG.exe

Description of the function
When the program starts, it will automatically search the clipboard for the URL and paste it into the textbox M3U8....."

https://nilaoda.github.io/N_m3u8DL-CLI/SimpleGUI.html

so I guess it's the same thing  for CLI command line, it's impossible to merge GUI graphical interface "N_m3u8DL-CLI-SimpleG.exe"  in Media-Downlaoder to use only one single program ?
Thank you !

**Comment by trimechee** [comment]
Another suggestion please, I am reading the documentation and i see that : "M3U8URL2File
A small software to help you download m3u8 links as m3u8 files."

https://github.com/nilaoda/M3U8URL2File/releases

https://nilaoda.github.io/N_m3u8DL-CLI/M3U8URL2File.html

Is it possible to integrate this interesting program in Media-downloader please ?

**Comment by trimechee** [comment]
I discover another progam to download from one drive cloud, i don't know if it can be included in Media-downloader : https://github.com/gaowanliang/OneDriveShareLinkPushAria2
