### ISSUE TITLE
Integrate/support m3u8 downloader

### ISSUE THREAD

**Issue by StrollStars** [mhogomchungu/media-downloader#154]
It is recommended to integrate/support m3u8 downloader [N_m3u8DL-CLI](https://github.com/nilaoda/N_m3u8DL-CLI).

**Comment by mhogomchungu** [comment]
Already requested.

https://github.com/mhogomchungu/media-downloader/issues/149

**Comment by mhogomchungu** [comment]
Post a link i can use to test. Ideally of a media that takes a few megabytes.

**Comment by StrollStars** [comment]
@mhogomchungu html: https://www.olevod.com/index.php/vod/play/id/35029/sid/1/nid/1.html
m3u8: https://europe.olemovienews.com/hls2timeofffmp4/20220409/xzytfeyA/mp4/xzytfeyA.mp4/index-v1-a1.m3u8

**Comment by trimechee** [comment]
Hello, N_m3u8DL-CLI seems to be chinese software and maybe we need a chinese ip address to test this software, and therefore we need vpn to have chinese ip address, maybe these free and unlimited vpn and often open source anti censorship can be used to access Chinese streaming sites and test this software:


https://github.com/krlvm/PowerTunnel



https://github.com/Jigsaw-Code/outline-client


https://riseup.net/en/vpn


https://www.nthlink.com/


https://tachyon.eco/


https://getlantern.org/en/index.html


https://psiphon.ca/


https://www.vpngate.net/en/download.aspx


https://www.vpngate.net/en/download.aspx


https://dongtaiwang.com/home_en.php?pm=y

https://www.tribler.org/


https://vpn-private.net/


https://www.itopvpn.com/vpn-windows?ref=homepage


https://hoxx.com/


https://cloudflarewarp.com/




https://www.your-freedom.net/index.php?id=home

**Comment by mhogomchungu** [comment]
>https://europe.olemovienews.com/hls2timeofffmp4/20220409/xzytfeyA/mp4/xzytfeyA.mp4/index-v1-a1.m3u8

The above link downloads a 415MB video. I need to see how a successful download looks like and i can not download a file this big just to see it.

I need a small video of about 10MB with 20MB being a hard limit.

**Comment by trimechee** [comment]
@StrollStars

**Comment by StrollStars** [comment]
@mhogomchungu @trimechee html: https://www.mgtv.com/b/457916/16904076.html
m3u8: https://pcvideoaliyun.titan.mgtv.com/c1/2022/07/09_0/83C4377FA76DD0A0BB5A6BCA7B78B07B_20220709_1_1_487_mp4/85EE3F748245C5DDDB468376DACCB9F1.m3u8?arange=0&pm=82SscHKfYQMEdDCiKIFILc_cWkEGLw7DQLGOw3UzmIrgEnhKwbof3rjaOH3INQymNzSexxKoAc22wx8cx3DlPrG5kCPbSfHsJfjktvEQHxOgqAzXax5VpXRWM5xxQmXeaQi0g8iaqUnUUR2iQRn10ExbaNmc3pwS4xJmsX2DvVgTa1c5CxWYVD0aB1oa9aA~b980IAlBU8bqEz9Vp6WCuTaDZD1v3uECnl~Dd2AFYDp8JrKI4UpUfSjPDnc3ith23GsfkwIKv9~yRsDlb3RjfsqZfFB6Z5cI3q9UELKzMd383irOLWNn7zRNw7m4tPRygrXHzCJO9ep2OGniiEukUkBYBxLeEfxNUor3M9qS4i5tnm4rnISCt_7hiT09lthGAGgV~BTBKNx8vPByo7jpZdzCv~2Jtow6E1O77_M~8ARkCMApmXQ3LS0tlngQwZ1G&mr=XHqjK3051cWglvcWu1OEIfFRj27fmnJYNT9fqmeHxXDFulmUSRTu8uDRB_w4udtZp4tjhpUrOfELc_P6l_krlYX8XygDRyzU4K1aA~RTRkx2h4piWRk0EvbkGenzcv0h4~Zbk8YHCgf23ml6HIOFZaRMw~RJ2jrMLmO_1gqYVSaSKrz6lw4c~knQGwPVZnhqdxxC_8Utf_2yqz4Cn42pK~zIS80WyAIsqmHS87SRve9HXhavFix4Hr3pTqot9n1TEz8tHray20PAfwWDSNArPNq5RWrLCpja6lZX~WTnfeHXLos0VNS783kDExP5TW1YelSz0hp96Z7A22e5vF4rgMQShyCPLuBNXNXbE8LVwwo15uYBpUh6ULDNWeCqcEw1D2LY598h~rnGyIeC3W_r1z_rMPa7FlPX54Emem4w8Smixuu~RKHKuvibvKczThQOO7g57X8M_RWh13IPlkX_eZdyelPBCxVWX7dUNMDVSPn5fjsfm60XcATOgAYz0BPuUBxjA8bNUQupJR21j5LrNyQEk5otr98cjO_Q_7i~hKjA5h3is68NbB869yWuR4DQRtArTLt8kglLckXa~T2nUlsKH63TV4hm07gKxu04BS2Ap3nuQl4PevHCc4HwkqoXfDP~Hq2jjm~DO5Fj55MzvQ--&scid=25021&cpno=6i06rp&ruid=100d16451b6f437d&sh=1
