### ISSUE TITLE
Captvty

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#156]
Hello, French law allows you to have a private copy of a video that's why the state has not banned this software which allows you to watch or download programs and videos from French TV channels, I sometimes watch French TV so I tested this software with the "psiphon vpn" and it works, so for simplicity and faster download speed because Media-Doanwloader has the extensions aria2c and wget, I wonder if our beloved Media-Doanwloader could maybe -to be integrated into this software so that we can download political or social programs from French television, thank you very much!

https://captvty.fr/

https://psiphon.ca/

**Comment by trimechee** [comment]
Some tv channels can be viewed or tv shows downloaded without vpn, the software also allows access to swiss and canadian tv from quebec.....

**Comment by trimechee** [comment]
Yes,I understand French and I use captvty to watch live tv and replay, there is replay of football matches, tennis, political investigation programs....I'm telling you about it because an exceptional software, when I tell you I talked about captvty, it's just a suggestion for the distant future and it's in the interest of Media-Donwnaloder and its users, I remind you that toutube-dil has been banned by github following a dmca complaint, so I make the effort to find and offer alternative software to youtube-dlp which could one day be banned, imagine google is filing a complaint against youtube-dlp because it allows you to download from youtube and google does not benefit from advertising....

for you-get and svtplay, I have trouble mastering the command lines so I haven't used them, but captvty I use it, it's really a vague suggestion for a future, of course I know how much it's is difficult to integrate them but I remind you, these software allow you to have a weak internet connection and avoid stutters, for Chinese software, many streaming platforms can ban streaming content so uploaders can post on Chinese platforms and that can be useful to integrate this Chinese software.....


of course it's just suggestions for the distant future, captvty has a GUI and I use it easily .... really  I do not suggest to tire you, I surf the internet and I come across things and since you are nice person , I share my discoveries with the users of media downloader, it can be useful for them, ok i will delete my post on captvty, and I assure you, projects like captvty and svtplay which can download encrypted tv content, it's very very rare to find them  free of charge, it's almost impossible to circumvent the protection of DRM tv channels so no worries, I don't I was going to propose to integrate thousands of projects lol

**Comment by trimechee** [comment]
Buecause it is hard work to maintaining the support ot allthese programas, i suggest you to give up support of svtplay, i think there is few sweden users using it through media-donwloader, and give up support of captvty because it seems to be not open source, but you-get seems to be a good program and support many streaming webties its it would be good idea to maintain support of you-get, thank you

**Comment by mhogomchungu** [comment]
This captvty appears to be offered through GUI only and hence can not be supported.

Only programs that offers their functionality through CLI can be supported supported.

**Comment by trimechee** [comment]
Interesting, thank you vey much :)
