### ISSUE TITLE
Download video partially

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#157]
Hello, i see in the changelog of  yt-dlp 2022.06.22.1

"A description of the various files are in the README
Changelog:
Deprecate support for Python 3.6
Add option --download-sections to download video partially"

but I'm looking for but it seems difficult to use this option, it will be great if Media-Doawnloader adds a graphical interface to this important option especially for very long videos of several hours in order to simplify the use of this option, for example add a preset "download the first 45 minutes of the video".....

this is what i find : 

Download time range: Videos can be downloaded partially based on either timestamps or chapters using --download-sections

Split video by chapters: Videos can be split into multiple files based on chapters using --split-chapters

**Comment by trimechee** [comment]
i find this : 


"Can someone help with me completing with this .bat file that automatically trims videos?


I'm trying to trim youtube video by
creating a .bat file where the .bat file first ask me for
Entering first "Video url"
start time
end time

 

I'm using using this command -f "(bestvideo+bestaudio/best)[protocol!*=dash]" I did create a working [.bat file here](https://pastebin.com/raw/qsEgrb3f) but trimmed video is always out of sync


Yt-Dlp Downloading a Section of Video?
Is there an option in `yt-dlp` to download a clip (like as in a subsection of (ex: 3:16 - 5:12) of a video?

Currently I post-process it with ffmpeg using `-ss` and `-to` :)

Would be great to merge the steps into one re-usable alias for linux.



https://www.reddit.com/r/youtubedl/comments/ru7bnv/can_someone_help_with_me_completing_with_this_bat/



https://www.reddit.com/r/youtubedl/comments/rx4ylp/ytdlp_downloading_a_section_of_video/



https://www.reddit.com/r/youtubedl/wiki/howdoidownloadpartsofavideo/






https://www.reddit.com/r/youtubedl/comments/ru7bnv/can_someone_help_with_me_completing_with_this_bat/

**Comment by trimechee** [comment]
Interesting !! Thank yo very much for your help @candrapersada  :)

**Comment by candrapersada** [comment]
> Hello @candrapersada , uget download manager is still alive ou it is a dead project ?

.sh file is an alternative to .bat file in Linux

**Comment by trimechee** [comment]
Great ! thank you very much 👍

**Comment by candrapersada** [comment]
please help me share how to use yt-dlp.sh to other Linux users.

**Comment by trimechee** [comment]
I am windows user and i never tried linux, i am not developer , i was thinkig that it's you thet  helps me lol, may be @mhogomchungu  can help you :)

**Comment by mhogomchungu** [comment]
Documentation for the options says as follows:-
```
--download-sections REGEX       Download only chapters whose title matches
                                the given regular expression. Time ranges
                                prefixed by a "*" can also be used in place
                                of chapters to download the specified range.
                                Eg: --download-sections "*10:15-15:00"
                                --download-sections "intro". Needs ffmpeg.
                                This option can be used multiple times to
                                download multiple sections
```
Why first 45 minutes and not first 30 minutes?

There is simply no way of having sane GUI options that allow supporting all possible combinations users may want when using this option and my solution is to put a text box right and center where people can type in the options they want to get the behavior they need.

There is a button that remembers the last ten used options and this place seems to be the best place to put the option if you dont use too many different options since it remembers the last ten or you can create a custom preset option with this option if you dont want it to be overriden.

![Screenshot_20220702_141745](https://user-images.githubusercontent.com/3496115/176998534-7deb15f5-6f10-41b0-8c14-025c701dc7c6.png)

**Comment by trimechee** [comment]
Thank you very much for these clarifications:) 45 mins because I watch a French investigative program, each report lasts 45 mins on average but they put the three reports together in the same video and I just like to watch a single report that m interested, so adding an option to determine the length and duration of the video you want to watch can be useful especially if the video is in 4k and downloading it can take a lot of time ..... so the user who just wants to watch part of the video and download it, can with this option limit the weight of the downloaded video if the tv show contains a lot of tv reports and only one or two tv reports interest him...
