### ISSUE TITLE
Integration with extension stream-detector

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#160]
Hello, in the options of stream-detector extension, there is an option "copy stream url as" yt-dlp command", and sometimes there is  HLS video parts, which need to be stitched, is there an option in Media-Donwloader to paste these types of stream urls please and so Media-downloader can stitch these video parts?

https://github.com/rowrawer/stream-detector/

**Comment by mhogomchungu** [comment]
I do not have firefox installed so i can not test this extension.

[This](https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#13-how-do-i-add-url-to-batch-downloader-from-a-cli) FAQ entry i just added should explain how media-downloader can receive URL from that extension and what it can do with it.

It is now up to you to set up the extension to send a URL to media downloader.

It should be easy now to set the extension to send its url to media-downloader.

**Comment by trimechee** [comment]
Great ! Thank you very much :)
just to say that following user requests, the developer of stream detector has made a version for chrome browser even if it does not give guarantees of normal running

 https://github.com/rowrawer/stream-detector/releases/download/ v2.10.8/hls_stream_detector-2.10.8.crx
