### ISSUE TITLE
Extensions of Media-Donwloader description

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#162]
Hello, in order that people to realize the wonderful mind-blowing potential of our beloved Media-Donwloader and know the effort put into adding support for different CLI programs, I think it will be great for people to know the power of Media-Donwloader. Donwloader, it will be helpful if in the extensions page of Media-Donwloader, there is mention of adding support of you-get, N_m3u8DL.....

https://github.com/mhogomchungu/media-downloader/wiki/Extensions

**Comment by mhogomchungu** [comment]
The extension page lists extensions that are supported by the latest released version of media downloader. When the next release is out, the page will include "you-get" and "svtplay-dl".

"N_m3u8DL" will not be included because its support will not be in the next version. I plan to make a new release tomorrow.

**Comment by candrapersada** [comment]
> The extension page lists extensions that are supported by the latest released version of media downloader. When the next release is out, the page will include "you-get" and "svtplay-dl".

but no windows or Linux information at https://github.com/mhogomchungu/media-downloader/releases/tag/2.4.0 "you-get"

**Comment by mhogomchungu** [comment]
The extension page has info for [you-get](https://github.com/mhogomchungu/media-downloader/wiki/Extensions#10-you-get) and [svtplay-dl](https://github.com/mhogomchungu/media-downloader/wiki/Extensions#11-svtplay-dl)

**Comment by trimechee** [comment]
Great !! that's awesome :)
