### ISSUE TITLE
Error, executable to backend "svtplay-dl" could not be found

### ISSUE THREAD

**Issue by Sopor** [mhogomchungu/media-downloader#164]
I have followed your guide how to install a plugin, but it doesn't matter what i do, i only get an error 😞

When i try to install svtplay-dl i only get:
```
[media-downloader] Download Failed
[media-downloader] Failed to find executable "svtplay-dl.exe"
[media-downloader] Error, executable to backend "svtplay-dl" could not be found
```

Where should i put the `svtplay-dl.json` file?

Where should i put the `svtplay-dl.exe`?

`svtplay-dl` is a portable application, so you can put it wherever you like (almost) and i also use the portable `Media downloader`.

This is the instructions for svtplay-dl: `Unzip and run svtplay-dl.exe from a command prompt.` It can't be simpler 😀

And yes, i'm familiar with svtplay-dl. I have used it for years.

**Comment by mhogomchungu** [comment]
1. Enter the application folder and in it, you will see a folder named "3rdParty".
2. Put "svtplay-dl.exe" in there and restart Media Downloader.

**Comment by mhogomchungu** [comment]
Add your support here[1] to make it possible for Media Downloader to automatically handle downloading of svtplay-dl.exe.

[1] https://github.com/spaam/svtplay-dl/issues/1485

**Comment by Sopor** [comment]
I have one suggestion about manually copy files to `Program Files`.

Because of UAC, files shouldn't be manually copied to `Program Files`.

All those files should be in `%APPDATA%\MediaDownloader\3rdParty` to avoid UAC.

Or do as many other applications do, install the whole Media Download to `%APPDATA%\MediaDownloader`.

**Comment by mhogomchungu** [comment]
Application's local folder for a user where everything is stored is at [1] and executables should be placed in [2]. The problem with path [2] is that "AppData" folder is hidden and its not easy to get to it. There is a button that opens a folder dialog window at [3] and there should be another one that opens a folder dialog window at path [2] to offer the same convenience.

Path at [2] is where Media Downloader downloads executables it automatically download.

[1] C:\Users\<username>\AppData\Roaming\media-downloader
[2] C:\Users\<username>\AppData\Roaming\media-downloader\bin
[3] [2] C:\Users\<username>\AppData\Roaming\media-downloader\themes

**Comment by mhogomchungu** [comment]
New version is out and it now has a button that opens a file manager where Media Downloader stores its executables and it should be easy to place svtplay-dl executable folder there.

https://github.com/mhogomchungu/media-downloader/releases/tag/2.5.0

![Screenshot_20220801_091301](https://user-images.githubusercontent.com/3496115/182083964-43c2eed5-d9d7-40b0-b681-5975e6bc1c27.png)
