### ISSUE TITLE
Profile Manager - Create, edit, remove, and switch download options in Tab Engine

### ISSUE THREAD

**Issue by candrapersada** [mhogomchungu/media-downloader#168]
why is there no custom options in the `Engine's default download options` without name it "yt-dlp-custom.json" https://github.com/mhogomchungu/media-downloader/issues/147#issuecomment-1133656588?
![image](https://user-images.githubusercontent.com/36833664/178406953-8071aeb5-6fcc-4b24-b1a5-b86e36565dc0.png)

**Comment by mhogomchungu** [comment]
There is no option because nobody requested it :-)

It seems like a nice addition.

**Comment by mhogomchungu** [comment]
Done.

![Screenshot_20220918_154935](https://user-images.githubusercontent.com/3496115/190902917-ea620185-7f7c-4167-92da-f4d7c3d8aba7.png)

**Comment by candrapersada** [comment]
is there a button to edit other than add delete and set as default?
