### ISSUE TITLE
Select "Manage Subscription" can't use "Ui Name" and  "Url"

### ISSUE THREAD

**Issue by candrapersada** [mhogomchungu/media-downloader#169]
why can't use `Enter a text you want to be seen in the Ui in the "Ui Name" text field.` and `Enter a subscription url in the "Url" text field.`
![image](https://user-images.githubusercontent.com/36833664/178867167-d0621a14-c9d3-42da-9850-96a7611c900d.png)

**Comment by mhogomchungu** [comment]
The UI is broken and the full window should look like below image, thanks for the report.

![Screenshot_20220714_093302](https://user-images.githubusercontent.com/3496115/178916469-4ba006a5-ccc4-4291-8b0f-cd67d6a53b17.png)

**Comment by mhogomchungu** [comment]
New version is out and it has a fix for this issue

https://github.com/mhogomchungu/media-downloader/releases/tag/2.5.0
