### ISSUE TITLE
Russian file names do not correctly in the UI.

### ISSUE THREAD

**Issue by mhogomchungu** [mhogomchungu/media-downloader#170]
From the command line, go to where yt-dlp.exe command is and then run the below command and then post the contents of "output.txt" file
```
yt-dlp.exe -f 242+250 --newline https://www.youtube.com/watch?v=Gkz9F4GGxOs > output.txt
```

**Comment by wvxwxvw** [comment]
`[youtube] Gkz9F4GGxOs: Downloading webpage
[youtube] Gkz9F4GGxOs: Downloading android player API JSON
[info] Gkz9F4GGxOs: Downloading 1 format(s): 242+250
[download] Destination: Так мы ещё не тонули) хорошее начало гонки) [Gkz9F4GGxOs].f242.webm
[download]   0.0% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]   0.0% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]   0.0% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]   0.0% of 42.90MiB at    7.32MiB/s ETA 00:05
[download]   0.1% of 42.90MiB at    7.57MiB/s ETA 00:05
[download]   0.1% of 42.90MiB at   10.25MiB/s ETA 00:04
[download]   0.3% of 42.90MiB at   13.78MiB/s ETA 00:03
[download]   0.6% of 42.90MiB at   19.15MiB/s ETA 00:02
[download]   1.2% of 42.90MiB at   24.95MiB/s ETA 00:01
[download]   2.3% of 42.90MiB at   30.27MiB/s ETA 00:01
[download]   4.7% of 42.90MiB at   24.68MiB/s ETA 00:01
[download]   9.3% of 42.90MiB at   33.60MiB/s ETA 00:01
[download]  18.6% of 42.90MiB at   41.66MiB/s ETA 00:00
[download]  22.8% of 42.90MiB at   45.46MiB/s ETA 00:00
[download]  22.8% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]  22.8% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]  22.8% of 42.90MiB at    6.83MiB/s ETA 00:04
[download]  22.8% of 42.90MiB at   14.65MiB/s ETA 00:02
[download]  22.9% of 42.90MiB at   15.13MiB/s ETA 00:02
[download]  22.9% of 42.90MiB at   12.30MiB/s ETA 00:02
[download]  23.1% of 42.90MiB at   13.78MiB/s ETA 00:02
[download]  23.4% of 42.90MiB at   12.45MiB/s ETA 00:02
[download]  24.0% of 42.90MiB at   18.48MiB/s ETA 00:01
[download]  25.1% of 42.90MiB at   31.22MiB/s ETA 00:01
[download]  27.4% of 42.90MiB at   41.64MiB/s ETA 00:00
[download]  32.1% of 42.90MiB at   34.47MiB/s ETA 00:00
[download]  41.4% of 42.90MiB at   35.87MiB/s ETA 00:00
[download]  45.7% of 42.90MiB at   37.44MiB/s ETA 00:00
[download]  45.7% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]  45.7% of 42.90MiB at    2.93MiB/s ETA 00:07
[download]  45.8% of 42.90MiB at    6.83MiB/s ETA 00:03
[download]  45.8% of 42.90MiB at   14.65MiB/s ETA 00:01
[download]  45.8% of 42.90MiB at    5.05MiB/s ETA 00:04
[download]  45.9% of 42.90MiB at    8.79MiB/s ETA 00:02
[download]  46.0% of 42.90MiB at    9.54MiB/s ETA 00:02
[download]  46.3% of 42.90MiB at   12.45MiB/s ETA 00:01
[download]  46.9% of 42.90MiB at    4.94MiB/s ETA 00:04
[download]  48.1% of 42.90MiB at    9.34MiB/s ETA 00:02
[download]  50.4% of 42.90MiB at   16.52MiB/s ETA 00:01
[download]  55.1% of 42.90MiB at   19.32MiB/s ETA 00:00
[download]  64.4% of 42.90MiB at   31.87MiB/s ETA 00:00
[download]  68.7% of 42.90MiB at   30.53MiB/s ETA 00:00
[download]  68.7% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]  68.7% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]  68.7% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]  68.8% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]  68.8% of 42.90MiB at    5.05MiB/s ETA 00:02
[download]  68.9% of 42.90MiB at    8.79MiB/s ETA 00:01
[download]  69.0% of 42.90MiB at   10.33MiB/s ETA 00:01
[download]  69.3% of 42.90MiB at   13.11MiB/s ETA 00:01
[download]  69.9% of 42.90MiB at    9.60MiB/s ETA 00:01
[download]  71.1% of 42.90MiB at   16.11MiB/s ETA 00:00
[download]  73.4% of 42.90MiB at   23.24MiB/s ETA 00:00
[download]  78.1% of 42.90MiB at   29.62MiB/s ETA 00:00
[download]  87.4% of 42.90MiB at   38.83MiB/s ETA 00:00
[download]  91.9% of 42.90MiB at   43.62MiB/s ETA 00:00
[download]  91.9% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]  91.9% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]  91.9% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]  92.0% of 42.90MiB at  Unknown B/s ETA  Unknown
[download]  92.0% of 42.90MiB at    5.05MiB/s ETA 00:00
[download]  92.1% of 42.90MiB at    8.79MiB/s ETA 00:00
[download]  92.2% of 42.90MiB at   10.33MiB/s ETA 00:00
[download]  92.5% of 42.90MiB at   13.83MiB/s ETA 00:00
[download]  93.1% of 42.90MiB at   22.68MiB/s ETA 00:00
[download]  94.2% of 42.90MiB at   14.48MiB/s ETA 00:00
[download]  96.6% of 42.90MiB at   23.24MiB/s ETA 00:00
[download] 100.0% of 42.90MiB at   32.71MiB/s ETA 00:00
[download] 100% of 42.90MiB in 00:01
[download] Destination: Так мы ещё не тонули) хорошее начало гонки) [Gkz9F4GGxOs].f250.webm
[download]   0.0% of 11.47MiB at  Unknown B/s ETA  Unknown
[download]   0.0% of 11.47MiB at  Unknown B/s ETA  Unknown
[download]   0.1% of 11.47MiB at    3.42MiB/s ETA 00:03
[download]   0.1% of 11.47MiB at    7.32MiB/s ETA 00:01
[download]   0.3% of 11.47MiB at    6.05MiB/s ETA 00:01
[download]   0.5% of 11.47MiB at    8.79MiB/s ETA 00:01
[download]   1.1% of 11.47MiB at   12.40MiB/s ETA 00:00
[download]   2.2% of 11.47MiB at   16.60MiB/s ETA 00:00
[download]   4.3% of 11.47MiB at   23.76MiB/s ETA 00:00
[download]   8.7% of 11.47MiB at   30.27MiB/s ETA 00:00
[download]  17.4% of 11.47MiB at   38.44MiB/s ETA 00:00
[download]  34.9% of 11.47MiB at   45.96MiB/s ETA 00:00
[download]  69.7% of 11.47MiB at   49.99MiB/s ETA 00:00
[download]  83.8% of 11.47MiB at   44.93MiB/s ETA 00:00
[download]  83.8% of 11.47MiB at  Unknown B/s ETA  Unknown
[download]  83.8% of 11.47MiB at  Unknown B/s ETA  Unknown
[download]  83.9% of 11.47MiB at  Unknown B/s ETA  Unknown
[download]  83.9% of 11.47MiB at  Unknown B/s ETA  Unknown
[download]  84.1% of 11.47MiB at    6.05MiB/s ETA 00:00
[download]  84.3% of 11.47MiB at    7.69MiB/s ETA 00:00
[download]  84.9% of 11.47MiB at   11.27MiB/s ETA 00:00
[download]  86.0% of 11.47MiB at   15.56MiB/s ETA 00:00
[download]  88.1% of 11.47MiB at   17.21MiB/s ETA 00:00
[download]  92.5% of 11.47MiB at   27.75MiB/s ETA 00:00
[download] 100.0% of 11.47MiB at   37.93MiB/s ETA 00:00
[download] 100% of 11.47MiB in 00:00
`

**Comment by mhogomchungu** [comment]
Image below show Media Downloader on Windows works fine with Russian text when it is fed Russian Text.

This still tells me the problem you see comes from data produced by yt-dlp.

![Screenshot_20220715_110219](https://user-images.githubusercontent.com/3496115/179181491-96f73e53-de2f-4e11-8bfa-9a5bfedd05f3.png)

**Comment by wvxwxvw** [comment]
I wonder if non-English Windows can affect the output of ANSI in Unicode? It looks like the ANSI string is being converted to Unicode, then it is quite expected that it will break.

**Comment by mhogomchungu** [comment]
Do you see a problem with all videos with Russian names or with some of them?

To be specific, this[1] url worked fine with yt-dlp on the command line on your system and it does not work with Media Downloader?

https://www.youtube.com/watch?v=Gkz9F4GGxOs

**Comment by wvxwxvw** [comment]
With YT everything. The fact is that output.txt in ANSI, and in the program in what encoding is the header displayed?

**Comment by wvxwxvw** [comment]
chcp write 866  
  
In general, I ran out of ideas, in the end I already know what I'm downloading. )

**Comment by wvxwxvw** [comment]
Или, если это не сложно, сделайте тестовую версию с 1251

**Comment by mhogomchungu** [comment]
You use Linux or Windows?

I think the solution is with you setting yt-dlp encoding option and i am working on solution that will allow you to set it.

**Comment by mhogomchungu** [comment]
I think i found the solution, its possible to tell yt-dlp what encoding to use with its ```--encoding``` option.

1. Create a text filed named ```yt-dlp.conf```. Careful here since Windows will probably secretly add .txt extension if you create it with windows exporer.
2. In it, add ```--encoding utf-8```
3. Put the text file in the same folder with yt-dlp.exe.
4. Run Media Downloader and check if it makes a difference.

**Comment by mhogomchungu** [comment]
New version will have a GUI option of setting encoding option

![Screenshot_20221015_203601](https://user-images.githubusercontent.com/3496115/196000759-1882f241-83e6-4174-af28-880c42fc4df4.png)

**Comment by wvxwxvw** [comment]
![2022 10 21_223329](https://user-images.githubusercontent.com/13194155/197275637-544aa8f5-ac25-4577-a0f2-05af1b5d9f8a.png)
