### ISSUE TITLE
Pyload

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#174]
Hello, I discover this surprising software taht seems capable of downloading any type of files, reading the description, the software seems to be a CLI tool and maybe our beloved Media-Downlaoder can add a frontend : 

https://github.com/pyload/pyload/tree/main

**Comment by mhogomchungu** [comment]
This is a CLI tool that offers its functionality through a web browser.

Supported CLI tool are supposed to offer their functionality through CLI interface.

**Comment by trimechee** [comment]
Interesting, thank you :)
