### ISSUE TITLE
Url 

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#177]
Hello, sometimes when we watch many episodes of a tv series, we don't need to download the whole videos because we may not like the episode and we can skip parts of the video, so sometimes I just copy the url of the video and I paste it in vlc media player or potplayer or smplayer or mpv easey player......so it will be great if our beloved Media-Player gives us an option so that we can see and copy the url address of the analyzed decrypted video by Media-downloader so we can paste the url address in the media player and we can zap without downloading the whole video and save bandwidth, for example I would like to know the video url of this video from mail.ru and paste it in vlc media player but when i put the url address in vlc or potplayer, it doesn't work, but when i used a website like https://getvideo.at/en/ , i was able to get the source url address of the video and I was able to paste it in potplayer or vlc player and play the video  but we would like to use Media-Downloader to know and copy quickly  the original esource url address of streaming video without the use of third party websites, thank you very much :)

https://my.mail.ru/mail/biard1337/video/_myvideo/807.html?from=videoplayer

**Comment by trimechee** [comment]
Awesome !! Thank you very much for your precious help 🥇

**Comment by mhogomchungu** [comment]
New version is out and it has this feature.

https://github.com/mhogomchungu/media-downloader/releases/tag/2.6.0

**Comment by trimechee** [comment]
Thank you very much for your great generosity and kindness! I tried a lot of free and paid software and I think it's time for the world to recognize Media-Downloader as the best downloader in the world 🥇 💯 


I saw that Media-Dowloader has a lot of great extensions ! we hope in sha Allah that an extension invented or recommended by our -beloved Medi -Downloader will be added to the list of extensions so this extension will be a verified trusted extension inspected and tested by our beloved amazing Media-Downlader and there, we will be able to detect and capture some complicated embeded hided streams streams from the web browser and we would no longer need to use some suspect extensions that could inject malware or ads !

  https://github.com/mhogomchungu/media-downloader/wiki/Extensions

**Comment by trimechee** [comment]
In extension page 5. wget. :  Media-Dowloader said "Media Downloader will NOT download this plugin's executable.", what is the reason please  ?  and how we can install the executable please ?

**Comment by trimechee** [comment]
I see there is new version of ffmpeg version 5.1.2, does Media-Downloader will use these new version thant has many improvement please ? 

https://www.videohelp.com/software/ffmpeg/version-history

**Comment by mhogomchungu** [comment]
>
> In extension page 5. wget. : Media-Dowloader said "Media Downloader will
> NOT download this plugin's executable.", what is the reason please ? and
> how we can install the executable please ?
>

Because the executable is not hosted on GitHub.

Version 2.6.0 of Media Downloader for Windows bundles wget for the
convenience of windows users.

Users of Linux and other system will have to install it by other means with
the recommend way being using their system's package manager.

**Comment by trimechee** [comment]
Interesting, thank you so much for your precious help :)
