### ISSUE TITLE
Technical explanation

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#178]
Hello, of course we trust our beloved wonderful Media-Downloader :)  just I did an analysis via this web site and it says that the software is likely malicious !  what do you think ? surely this is a false positive ?

https://www.filescan.io/uploads/632a3db8b333b2ec6b3b8443/reports/679373c7-2b53-40c4-98cc-f4bfd3ae0931/overview

**Comment by trimechee** [comment]
I discover this site in community section of virustotal.com website, and filescans.io even says taht the very famous "sumatra pdf" is likeky malicious !! why thet said that about these trusty softwares  ?

**Comment by trimechee** [comment]
I foud the analisys of joe sandbox cloud and it says Supatra PDF is clean, so it seems there is a discrepancy between the anti virus analysis web sites !

https://www.joesandbox.com/analysis/475508/0/html

**Comment by mhogomchungu** [comment]
The code i am responsible for does not use any of the mentioned "problematic" APIs and their existence may come from :-

1. Bundled Qt libraries.
2. Installer.
3. Bundled executables(ffmpeg,aria2c,bsdtar).

You can eliminate "problems" from the installer by checking the portable version.

**Comment by trimechee** [comment]
Yes, there is no problem, surely it is false positives and I prefer to use the executable version of Media-Downloader :) I trust you and Media-Downloader, I talked about it so you can can contact this website in order to modify its report, I made the same question on the github page of sumatra pdf and a user says: "


"I think its the safest PDF viewer there is, AFAIK it can't knowingly run most malware like web pdf viewers, but then not all malware is known.

Naturally it logs keys (it could not read the keyboard otherwise) and yes it has to phone home for updates and down/upload files for crash reports etc. and search web using google deepl etc. but then Windows has all those characteristics and more."


https://github.com/sumatrapdfreader/sumatrapdf/issues/2974#issuecomment-1253460655
