### ISSUE TITLE
Dailymotion preset

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#180]
Hello, there is a playlist of a tv show and i would like to download some chosen videos, i used the batch downloader with the "worstaudio" preset, this preset works for youtube videos but did not work with dailymotion videos , apparently dailymotion doesn't have m4a and opus audio dash streams like in youtube , so i will like to upload the worst quality videos with preset , i tried 144p ,240p preset but it didn't work , please which preset should be added to download dailymotion video with the worst quality , thank you very much :)

https://www.dailymotion.com/tpmp/videos

**Comment by mhogomchungu** [comment]
1. Add an entry to the batch downloader list.
2. Right click the entry and then select "Show Media Options".
3. You will be presented with a list of all available options.
4. The entry on the "format code" column is the one you are supposed to add to the preset list.

**Comment by trimechee** [comment]
Awesome ! Thank you so much  !!🥇 so the worst video quality of dailymotion is hls-144-0 ? and please what is the difference between hls-144-0 and hls-144-1 ?

**Comment by mhogomchungu** [comment]
The notes column is supposed to have enough information to tell the difference between the two of them but it does not say in this regard so i don't know.

Try to download both of them and see if your video player can tell them apart.

**Comment by trimechee** [comment]
Yess, i am tryng different presets, thank you very much for your precious help :)
