### ISSUE TITLE
Unable to download Roku shows

### ISSUE THREAD

**Issue by Neipas09** [mhogomchungu/media-downloader#181]
I use reelgood.com to find shows and where they are being streamed, and Roku is a common option as a Free source.
But when I try using the URL it shows in the window it pops up, it fails to download anything.
Here's an example of Episode 1 of Power Rangers, using Roku as the source.
![image](https://user-images.githubusercontent.com/58871039/192089514-fc3135c0-c4f0-4c02-a5e5-e257bb40dcf8.png)

**Comment by mhogomchungu** [comment]
The problem is not with Media Downloader but with yt-dlp not having support for that website.

The solution here is to make a request to yt-dlp to add support for this website and you can do it from their issue tracker located here: https://github.com/yt-dlp/yt-dlp/issues
