### ISSUE TITLE
menu to edit Engine's options, menu to edit Preset options, and switch Profile Engine's options

### ISSUE THREAD

**Issue by candrapersada** [mhogomchungu/media-downloader#182]
is there a menu to edit Engine's options and Preset options?
![image](https://user-images.githubusercontent.com/36833664/192133930-3790a81b-546a-4266-a392-f7a0e4cfd984.png)
![image](https://user-images.githubusercontent.com/36833664/192134019-f20161d4-ddc7-44e2-afb3-456ea5f3ef93.png)

and is there a menu to switch Engine's options like
![image](https://user-images.githubusercontent.com/36833664/192134111-9531aa0d-00d0-4ee3-926e-d1ed8b5569e4.png)
or
![image](https://user-images.githubusercontent.com/36833664/192134167-8991048f-6ec0-468e-964f-4c6bd3323847.png)

**Comment by mhogomchungu** [comment]
If you want to edit existing value then steps to take are:-
1. Copy the existing value as seen in the below image.
2. Paste copied value to the "Options To Add" field.
3. Make your modifications.
4. Add the modified entry to the list.
5. Delete the entry copied in step one.

![Screenshot_20220925_130737](https://user-images.githubusercontent.com/3496115/192138266-5679da14-6bc0-4264-9014-f520831092a8.png)

**Comment by candrapersada** [comment]
and is there a menu to switch Profile Engine's options like
![image](https://user-images.githubusercontent.com/36833664/192234319-e7c745ae-6429-48dc-be50-c102a1bb6024.png)?
