### ISSUE TITLE
 YTDL-patched : new extractor yt-dlp enhanced 

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#185]
Hello, i find YTDL-patched =yt-dlp fork with some more features : keep merging with yt-dlp/yt-dlp
implement miscellaneous extractors as possible
make -U work (yes, really works)
do anything best, may be it will be good to add this downloader to Media-Downloader ! thank you .

https://github.com/ytdl-patched/ytdl-patched

**Comment by mhogomchungu** [comment]
This project does not appear to be popular enough to warrant a dedicated extension.

The point of having extensions as json based config file is to make it possible for people to create their own extensions this project is a good candidate for people to create their extension config file to use it.
