### ISSUE TITLE
Media downloader name confusion

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#186]
Hello, i find software named "Mediadownloader" made by O7q, , it has almost the same name of Media-Downloader, may be Mr Francis should talk to the developoer of this software and ask him to change the name of his software to avoid confusion !

https://github.com/o7q/MediaDownloader

**Comment by BarbzYHOOL** [comment]
Found one called "ultimate media downloader" that looks very similar to yours, maybe a ripoff

**Comment by trimechee** [comment]
Hello @mhogomchungu,  we love open source softwares but if it causes some people to steal your work and efforts, then I think it will be good idea to turn the media-downloader project into a closed source project and abandon open source especially since you seem to be the only developer of media-downloader and you don't get help from other developers, so it will be better for the safety of users to abandon open source licence in order to avoid projects that copy you !

**Comment by BarbzYHOOL** [comment]
that indian hustler is selling a premium version in top of that

anyway just wanted to point it to you

**Comment by ezkha** [comment]
I have sent a report on Snap Store and an email to Flathub where that ripoff is being distributed.

They also have a GitHub ["repo"](https://github.com/keshavbhatt/ultimate-media-downloader-linux) for listing issues (of which a big one evidently!), though reporting it means filling an entire DMCA takedown, and requires being the owner or authorized entity.

As for :

> Hello @mhogomchungu, we love open source softwares but if it causes some people to steal your work and efforts, then I think it will be good idea to turn the media-downloader project into a closed source project and abandon open source especially since you seem to be the only developer of media-downloader and you don't get help from other developers, so it will be better for the safety of users to abandon open source licence in order to avoid projects that copy you !

I don't think this is a sufficient argument to go closed-source and proprietary. 
Unfortunately being ripped-off or having its name stolen will happen all the time with open-source projects, but the many positives of FOSS do make you think before doing such a thing. I would argue that it should be the user being wary about the authenticity of what they install; meanwhile the original project should add a related disclaimer and list the fake copies.

**Comment by mhogomchungu** [comment]
I have made a request to that project for their source code to be made public.

My understanding of the GPL says they can use my work to make money if they want but they have to provide their source code on request if it is not public.

**Comment by trimechee** [comment]
Mr @mhogomchungu , I found the ideal solution to protect your work and stay open source : i think it will be good idea to put in the main page of media downloader (and maybe make a blog to talk about the news of Media-downloader or reddit page or twitter page) that Media -downloader remains open source for experts who want to audit the code or participate in the development or make a donation but the code will now be hidden from the public to avoid theft and scams, and experts or companies who want to analyze the code or participate in the development must send you an email where they send you their resume, qualification, proof that they are security experts or honest developers with their ID and their real name and address of their company and so you could send them the code of Media -odownloader if you think they are trustworthy people, and they must commit to not making forks to sell them afterwards....     
             it is legitimate to do this to protect your work and users from fake forks because Media-downloader is the best downlader in earth !
