### ISSUE TITLE
Specefic Part

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#187]
Hello, in the chagelog of yt-dlp, that said " Don't download entire video when no matching --download-sections", so can we donwload only determinated part of videos please ? beacause sometimes, we may find a very long video of a tv show that lasts 3 hours or 4 hours and we would just like to download only the part of the video that interests us to save data, can there be an option to download only a specific part of the long video please?

https://www.videohelp.com/software/yt-dlp/version-history

**Comment by mhogomchungu** [comment]
Done

![Screenshot_20221012_133737](https://user-images.githubusercontent.com/3496115/195332791-bce7da70-916d-4613-9455-b6cd441674c5.png)
![Screenshot_20221012_133803](https://user-images.githubusercontent.com/3496115/195332798-e89e806c-e8fd-48df-9cdf-7a9fa8e9acff.png)
![Screenshot_20221012_133828](https://user-images.githubusercontent.com/3496115/195332804-46c9c6d6-5d59-403c-9abc-52f8c99d5649.png)
