### ISSUE TITLE
Rename files

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#188]
Hello, some youtube channels post documentaries, this documentary can have a name like "small murders between neighbors" and this show has several episodes, whoever posts these videos just puts the name of the show "small murders between neighbors" and posts different episodes with the same title, if I go to the youtube channel and I want to download several different episodes that have the same title, Media-Downloader will not download them because it will think that they are the same video, can Media downloader add option "rename files" so media donwloader adds a number to the new video which has the same name as the previous ones, thank you !

**Comment by mhogomchungu** [comment]
Media Downloader uses default file name of ```%(title).200s-%(id)s.%(ext)s``` and the "id" part is there to makes sure all downloaded files are unique because each media has a unique id.
