### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#191]
Hello, I had sent someone my beautiful sublime playlist which is the most beautiful playlist in the universe:

https://www.youtube.com/playlist?list=PLCVfum9m6K6OkOnoRAzHnz5puRE4zVjWF

then after a few minutes, I go to a youtube channel of a radio and a tv to choose and select some videos, Media-Downnloader normally detects the videos because I have activated "inspect the clipboard" and I use batch donwloader, I leave Media-Downloader to download and I do something else......the downloads end because I closed Media-Downloader because the downloads encountered some  problems and I discover by opening the download folder that I downloaded incosniously dozens of videos from my playlist which contains 1700 videos because I forgot that I copied the link of the playlist and it was not my intention to download the videos from my playlist because I have already downloaded the audios of these recitations of the noble Quran in the past.....

my request please: can we see the name of the videos we are going to download in Batch downloader before downloading them so we can realize that we are going to download a playlist, or is it possible that Media-Downloader displays a warning pop-up "you are about to download videos from a playlist that has 100 videos or 1000 videos, it can take a long time and youtube might temporarily ban your ip address", or tell batch donwloader to download playlist or just download a video if the video is included in a playlist, thank you very much !

**Comment by mhogomchungu** [comment]
Downloading a playlist using batch downloader should not be allowed and Media Downloader passes yt-dlp option of "--no-playlist" to make sure it does not happen.

This sounds like a bug in yt-dlp.

**Comment by mhogomchungu** [comment]
This [comment](https://github.com/yt-dlp/yt-dlp/issues/5215#issuecomment-1278346006) has a solution to your problem.

Go to configure tab and add those options to "engine's default options".

![Screenshot_20221014_082613](https://user-images.githubusercontent.com/3496115/195769037-dc800f1f-0dc6-497c-85cc-846a293f173b.png)

**Comment by mhogomchungu** [comment]
> Fantastic ! thank ou for your great help ! so we should add --break-on-reject --match-filter !playlist
> 
> but we should not put --match-filter '!playlist_index' --break-on-reject .....

Both should work but i prefer the one that does not download anything before failing.

**Comment by mhogomchungu** [comment]
> To have more peace of mind that i will not download a playlist, can i add a new preset: " worstaudio --break-on-reject --match-filter !playlist "? Media-Downloader will be able to recognize this new complex preset and this preset will prevent playlist downloading ?

This should work, but the problem here is that the playlist will get downloaded if this preset is not in use for whatever reason.

In the next version, these options will unconditionally be added by Media Downloader so you wont need to manually set them.

If you can build Media Downloader from source then a better solution is to build from git and use it without changing any setting.
