### ISSUE TITLE
japanese file names do not correctly in the playlist title on Windows

### ISSUE THREAD

**Issue by candrapersada** [mhogomchungu/media-downloader#196]
japanese file names do not correctly in the `playlist_title` and `playlist` on Windows

- Windows 10 Home
- media-downloader-2.6.0

**Comment by mhogomchungu** [comment]
1. Post a link i can use to test.
2. Do you get expected behavior when running yt-dlp from the terminal?

**Comment by candrapersada** [comment]
https://www.youtube.com/playlist?list=PLQqD_z157-Zhm34BxCCbnytj_J2NzCp81

> Do you get expected behavior when running yt-dlp from the terminal?
yes

**Comment by candrapersada** [comment]
in terminal
![image](https://user-images.githubusercontent.com/36833664/195527159-44d3d5b1-3782-4393-ac43-25092b424b0f.png)
in media-downloader
![image](https://user-images.githubusercontent.com/36833664/195527436-869a937b-e5ef-496a-b123-e5f2ac8c8cbe.png)

**Comment by mhogomchungu** [comment]
This issue is related to another one first mentioned [here](https://github.com/mhogomchungu/media-downloader/issues/152#issuecomment-1176731195) and is tracked [here](https://github.com/mhogomchungu/media-downloader/issues/170)

**Comment by mhogomchungu** [comment]
Try adding the following option
```
--add-header 'Accept-Language:ja'
```

**Comment by mhogomchungu** [comment]
Are you sure you are running the same version of yt-dlp? when running from the terminal and from within Media Downloader?

Image 1 below shows output when running version 2022.08.19 of yt-dlp

Image 2 below shows output when running version 2022.10.04 of yt-dlp

These images suggests you are running a problematic version with Media Downloader.

Image 1 of version 2022.08.19 
![Screenshot_20221013_170424](https://user-images.githubusercontent.com/3496115/195620966-bfad1292-8334-4025-9736-84848692c648.png)

Image 2 of version 2022.10.04
![Screenshot_20221013_171039](https://user-images.githubusercontent.com/3496115/195621274-b325edd2-df64-4bc0-97f5-0853b6a6a3ed.png)

**Comment by candrapersada** [comment]
> Are you sure you are running the same version of yt-dlp? when running from the terminal and from within Media Downloader?

Yes 2022.10.04 from the terminal and from within Media Downloader

**Comment by mhogomchungu** [comment]
Post output of Media Downloader log window after you have populated the playlist tab with entries from the playlist.

**Comment by candrapersada** [comment]
![image](https://user-images.githubusercontent.com/36833664/195631310-3d1e0e8a-f5be-4de9-9e3a-3aa0df934683.png)

![image](https://user-images.githubusercontent.com/36833664/195630547-c64f5736-43cd-4b5b-af5a-0fb1f1155c9f.png)

**Comment by mhogomchungu** [comment]
Making progress, it looks like yt-dlp behaves differently depending on where it is run.

Below image shows it works as expected when running from windows' terminal(i assume native environment) and not working as expected when running from mingw32(i assume not native environment)

![Screenshot_20221013_182404](https://user-images.githubusercontent.com/3496115/195640533-7439dd00-4343-42e3-b631-078fa0474743.png)

**Comment by mhogomchungu** [comment]
I have opened a bug report here: https://github.com/yt-dlp/yt-dlp/issues/5236

**Comment by mhogomchungu** [comment]
I added "--encoding utf-8" option in the "get list option" field and below is the result.

![Screenshot_20221013_212422](https://user-images.githubusercontent.com/3496115/195677593-fa8e3fc7-a999-4024-91a2-22642c4b3476.png)
![Screenshot_20221013_212817](https://user-images.githubusercontent.com/3496115/195677615-335f6b11-2cd4-482d-af64-5b810a6cc8ec.png)

**Comment by candrapersada** [comment]
it works fine thank you

**Comment by mhogomchungu** [comment]
Done.

**Comment by mhogomchungu** [comment]
New version will have a way of setting text encoding

![Screenshot_20221015_203601](https://user-images.githubusercontent.com/3496115/196000759-1882f241-83e6-4174-af28-880c42fc4df4.png)

**Comment by candrapersada** [comment]
why is there the name yt-dlp in the text encoding?

**Comment by mhogomchungu** [comment]
Because i though only yt-dlp supports the option but it looks like youtube-dl supports it also.. 

I have removed the "yt-dlp" name and make it possible for other extensions to use the setting to future proofing the code but i do not think any other will use it.
