### ISSUE TITLE
yt-dlp ffmpeg

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#197]
Hello, i tried to download dailymotion video, with yt-dlp but the download speed is only 40kb/s, lux and you get and yt -dlp aria2c fail to download dailymotion video but I had a pleasant surprise, yt-dlp ffmpeg succed to download the video with a stable speed of 100kb/s!!

https://www.dailymotion.com/video/x8edqzr

many downloader use yt-dlp, but Media-Dowloader has the fascinating feature of integrating other software, so I think it will be better if Media-Downloader includes the yt-dlp ffmpef plugin by default so ordinary users can switch easily betwwen  engine or maybe media-downloader if it detects it's a dailymoton video, media downloader will automatically change engine from yt-dlp to yt-dlp ffmpeg because yt-dlp is too slow in dailymotion, thank you very much!

I even think that media downloader should include by default all downloader plugins like you get and lux because it is one of the greatest particularities and specificities of media dowloader compared to other competing downloaders, thank you !!

**Comment by mhogomchungu** [comment]
The link you provided worked for me with yt-dlp-aria2c on both linux and windows and attacked image shows it works on Linux.

Maybe in the future i will bundle it and the rest of them but not now.

![Screenshot_20221015_190359](https://user-images.githubusercontent.com/3496115/195997099-446e7b52-993a-4b30-846a-7797fdf8a93d.png)
