### ISSUE TITLE
Library and main display 

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#198]
Hello, many have "downloads" as default download folder from web browsers, and this downoad folder is also the dowlwload foder of Media-downloader, even wehen we choose another donwload folder for media downloader, the whole dowloader freeze freezes and becomes unresponsive because there may be a lot of downloaded files in the download folder, i think it will be better that media downloader detect if we use HDD or speed SSD, and if we use hdd which may be slow, the button "library" will just open the "downloads" folder, or maybe add option to hide the library button, because often I look in the options and click carelessly and unintentionally on "library" and the downloader freezes, in addition the new users may get bad misconception about downloader if they click library and freeze program, it will be better either hide library button or library just open download folder....thank you!

and some have view problems if the main windows display is tiny, they can't read very well on the main display, i think it will be better to enlarge a little bit the main window of Media- Downloader by default , for example zoom 1 .25, so people will be able to explore media downloader options with more greater visual comfort, especially as notebook screens are getting bigger and bigger, thank you !

**Comment by mhogomchungu** [comment]
One issue per report please.

The library tab is now off by default and there is a GUI option to enable it.

The default app size will stay the same. Ideally, default options should be on the side of the majority and i have no idea majority will agree with a different default value let alone set it to 1.25.

![Screenshot_20221015_142430](https://user-images.githubusercontent.com/3496115/195984102-6dc4b7c4-0114-46f1-9c61-7acb1359490a.png)
