### ISSUE TITLE
formats detection

### ISSUE THREAD

**Issue by Kicer86** [mhogomchungu/media-downloader#2]
I believe that basic downloader (other tabs too where applicable) should have some more user friendly UI:
1. user is asked for video url.
2. app detects available formats and prepares nice and clickable list of modes (including 'best', 'bestvideo' etc)
3. video is being downloaded

**Comment by mhogomchungu** [comment]
The app already show a list of preset modes you can choose from(click the options button) and the list is configurable.

It is not possible to auto generated a list that is comprehensive and sane because there will always be too many combinations to choose from. My preferred choice for example is 242+250 for videos i want to download, watch and delete.

If you have a combination you like best, add it to the list for easy access and the app expects your custom option to be structured like ```$CUSTOM_NAME($CUSTOM_MODE)```

**Comment by Kicer86** [comment]
Problem with preset modes is that they are fixed and may not exists for some videos. Also some videos may offer more that this set contains. Not experienced user will not know what to do.
My suggestion is to parse output of youtube-dl and collect available modes.

**Comment by mhogomchungu** [comment]
With result like below from youtube, what options would you like to see in the UI? The only ones that make sense to me are the last two.
```
249          webm       audio only tiny   51k , opus @ 50k (48000Hz), 1.19MiB
250          webm       audio only tiny   65k , opus @ 70k (48000Hz), 1.45MiB
251          webm       audio only tiny  114k , opus @160k (48000Hz), 2.60MiB
140          m4a        audio only tiny  130k , m4a_dash container, mp4a.40.2@128k (44100Hz), 3.09MiB
278          webm       256x144    144p   96k , webm container, vp9, 30fps, video only, 1.75MiB
160          mp4        256x144    144p  119k , avc1.4d400c, 30fps, video only, 1.58MiB
242          webm       426x240    240p  192k , vp9, 30fps, video only, 2.39MiB
133          mp4        426x240    240p  251k , avc1.4d4015, 30fps, video only, 3.63MiB
243          webm       640x360    360p  335k , vp9, 30fps, video only, 4.18MiB
134          mp4        640x360    360p  521k , avc1.4d401e, 30fps, video only, 6.81MiB
244          webm       854x480    480p  613k , vp9, 30fps, video only, 7.04MiB
135          mp4        854x480    480p  908k , avc1.4d401f, 30fps, video only, 12.49MiB
247          webm       1280x720   720p 1308k , vp9, 30fps, video only, 17.03MiB
136          mp4        1280x720   720p 1867k , avc1.64001f, 30fps, video only, 24.46MiB
302          webm       1280x720   720p60 2262k , vp9, 60fps, video only, 24.94MiB
298          mp4        1280x720   720p60 2745k , avc1.640020, 60fps, video only, 38.75MiB
18           mp4        640x360    360p  351k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 8.38MiB
22           mp4        1280x720   720p 1154k , avc1.64001F, 30fps, mp4a.40.2@192k (44100Hz) (best)
```

**Comment by Kicer86** [comment]
Actually all columns but first.

**Comment by Joduai** [comment]
I'd also opt for couple audio choices as yt-dl can also grab from scloud, bcamp, spotify and other "music only" webservices. Definitely 128kbit as it's max bitrate from mentioned, and 'bestaudio' would come in handy.

Found this nice piece of software yesterday and I love it.
Although there's pretty much space for further development ;)

**Comment by mhogomchungu** [comment]
1. If you want to download an audio file with best audio then enter "bestaudio" in the option field.
2. If you want to download an audio file with best audio and convert it to mp3 for example then enter "bestaudio -x --audio-format mp3" in the option fields.

For easy access, you can add your own custom entries like above in the preset list by going to configure tab and then add them to the "preset list". Options are comma separated.

The structure is ```$UINAME($MEDIA_CODE $REST_OF_YOUTUBE-DL-OPTIONS)```

With the above two examples, add the following entries.
1. BestAudio(bestaudio)
2. BestAudio-mp3(bestaudio -x --audio-format mp3)

This app does not assume its downloading media file from youtube and youtube media files do not get preferential treatment, it works equally to all websites that are supported by youtube-dl.

**Comment by Joduai** [comment]
I've already done it once I found your guide in one of your replies - no idea thou why I cannot find it anymore.
I did request this for future users and getting it out of the box.
Nonetheless this guide could get at least into wiki or into readme.md as it's very useful.

**Comment by mhogomchungu** [comment]
There is now a FAQ page: https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions

**Comment by mhogomchungu** [comment]
When clicking the "Get List" button the UI in the basic downloader tab switch to what is seen below and a user can click the option they want and the option will be added to the "Enter Options" field. Multiple options can be added by clicking an extra option while holding CTRL key.

![Screenshot_20210422_075943](https://user-images.githubusercontent.com/3496115/115658745-0c08bb80-a342-11eb-8808-57cc0ebaeab2.png)
