### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#200]
Hello, i discover in "option of the default engine", that there is "path of cookie file", i don't know what is this option for and how to use it, I searched in Frequently Asked Questions section but there is no info about cookies, it will be great great if there is informations about this option, thanks!

https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions

**Comment by mhogomchungu** [comment]
yt-dlp says the following about the option
```
--cookies FILE                  Netscape formatted file to read cookies from
                                and dump cookie jar in
```
you-get says the following about the option
```
Load cookies
Not all videos are publicly available to anyone. If you need to log in your account to access something (e.g., a private video), it would be unavoidable to feed the browser cookies to you-get via the --cookies/-c option.

Note:

As of now, we are supporting two formats of browser cookies: Mozilla cookies.sqlite and Netscape cookies.txt.
```
