### ISSUE TITLE
immediately start downloading after selecting the perest option

### ISSUE THREAD

**Issue by candrapersada** [mhogomchungu/media-downloader#201]
why after selecting the perest options the download starts without pressing the download button?
![image](https://user-images.githubusercontent.com/36833664/195883965-01cb229a-e393-4b63-a299-e8eb5921c915.png)

**Comment by mhogomchungu** [comment]
Its by design and it saves you the trouble of clicking the download button.

**Comment by mhogomchungu** [comment]
This behavior will be off by default in the next version
