### ISSUE TITLE
want to get the list of urls in a channel only first 200

### ISSUE THREAD

**Issue by sant527** [mhogomchungu/media-downloader#202]
want to get the list of urls in a channel only first 200

how to do this..

**Comment by mhogomchungu** [comment]
You are using windows or linux?

Released version does not have an option for saving only urls, it can save them but with other informations.

On the command line, a command to run to get the list of url is:-

```
yt-dlp --print webpage_url --playlist-items 1-200 $URL
```
Where $URL is the playlist url

**Comment by mhogomchungu** [comment]
When using atleast version 2.7.0 of Media Downloader, do the following:-

1. Go to playlist tab.
2. Enter the Url you want to download from in the URL text field.
3. Enter ```--playlist-items 1-200``` in the "Get List Options" text field.
4. Click "Get List".
5. After Media Downloader is populated with the list, right click one of the entries and then select "Save List To File".
6. Give the file name you want to save URL a ".txt" extension to save only URLs. The default :.json" extension will cause Media Downloader to save URL together with other things that you most likely not want.
