### ISSUE TITLE
What does "Delete" have to do with it?

### ISSUE THREAD

**Issue by wvxwxvw** [mhogomchungu/media-downloader#210]
https://github.com/mhogomchungu/media-downloader/blob/490987d3e9dc0d626b2d1fa466ea8473cc975228/translations/en_US.ts#L952
  
I have already written about this.

**Comment by mhogomchungu** [comment]
See below image to see where that "Delete" shows up in the UI. What did you say about "delete" because i do not remember it.

![Screenshot_20221024_072942](https://user-images.githubusercontent.com/3496115/197448870-265ff1cb-a30a-4388-92b7-5982be0dda05.png)

**Comment by wvxwxvw** [comment]
I'm sorry, I messed up something. It was about another line.
