### ISSUE TITLE
Wget disappearance

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#211]
Hello, recently i installed all extensions like lux, you get, aria2c.....except wget since "Wget is bundled in the Windows version of Media Downloader as of version 2.6.0.", but mysteriously wget engine disappeared from the list of available engines....it's mysterious, wget can cause conflicts with other engines, hence its sudden automatic deletion?

**Comment by mhogomchungu** [comment]
Yes, all extension's config files go in the "engines.v1" folder. Only this
folder will be used to search for "enabled" extensions.

**Comment by mhogomchungu** [comment]
You can set Media Downloader to use a specific engine with specific options when downloading media from a specific website. Go to Configure->Ui Manager to set things up.

I use yt-dlp-aria2c full time. Aria2c  behavior of opening multiple connections to download multiple chunks of a single file may appear to be abuse by some servers out there and this may lead to a ban but it has not happened to me yet. I think this concern is theoretical at this point.

yt-dlp does not support wget as a downloader so its not possible to have yt-dlp-wget extension
