### ISSUE TITLE
Hlsdl and m3u8

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#212]
Hello, i find this tool : hlsdl : C program to download VoD HLS (.m3u8) files, i read that ffmpeg could have some problems with hls streams,  so I think it may be a good idea, if this software is compatible with Media-Downloader to integrate it in order to avoid possible bugs with hls streams :

https://github.com/selsta/hlsdl

and also this tool : m3u8 which is Python m3u8 Parser for HTTP Live Streaming (HLS) Transmissions : 

https://github.com/globocom/m3u8

**Comment by mhogomchungu** [comment]
This one has no release, not popular enough and not worth supporting.
