### ISSUE TITLE
Consider creating a makedeb script for Debian based distros

### ISSUE THREAD

**Issue by sbstn87** [mhogomchungu/media-downloader#220]
Hi,

if packaging application as Flatpak is not something you currently plan to do, consider perhaps creating a makedeb script:
https://www.makedeb.org/

And adding it to MPR:
https://mpr.makedeb.org/

This will automatically cover all Debian based distros, just like AUR covers all Arch based distros.

**Comment by mhogomchungu** [comment]
I have many binary packages for debian, ubuntu, fedora and open suse [here](https://software.opensuse.org//download.html?project=home%3Aobs_mhogomchungu&package=media-downloader).

What is wrong with these packages?

**Comment by sbstn87** [comment]
Those packages are perfectly fine and work for me. Thank you for providing them.

Adding a makedeb script would cover all Debian based distros at once, no need for separate .deb files for each Debian/Ubuntu/Mint release. Also, this eliminates the need to add a new repository to the system, it would automatically update application from the last available version in the MPR.

**Comment by mhogomchungu** [comment]
You expressed your first preference as a flatpak package and Media Downloader is already on [flathub](https://flathub.org/apps/io.github.mhogomchungu.media-downloader) so closing this one as "fixed".
