### ISSUE TITLE
Encrypted stream

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#221]
Hello, i read this disucussion about donwload enrypted stream, ant it said : "No m3u8, but mpd.

Your stream is encrypted. You will need keys to decrypt.

yt-dlp --allow-u "mpd_url"

https://forum.videohelp.com/threads/407535-Zee5-video-download

Does Media-Donwloader include by default this command " --allow-u "mpd_url" to donwload encrypted streams ?

**Comment by mhogomchungu** [comment]
I will not be adding it as a default option.

Yes, you can add it:-
1. As one of the options in the "Enter options" field in batch downloader tab.
2. As one or only option of a custom preset option.
3. As one of the options In a custom engine's default option.

**Comment by mhogomchungu** [comment]
Are you sure you added it in an engine you are using?

**Comment by mhogomchungu** [comment]
Add the option to Media Downloader and Media Downloader will faithfully pass it along to yt-dlp, how yt-dlp behaves when its given the option is yt-dlp problem, not Media Downloader..

You can easily see if Media Downloder passed the option to yt-dlp or not by looking at the log window when telling it to download a media.

I have never used this option so i dont know how yt-dlp works with it and i just looked at yt-dlp and i do not see an option named "--allow-u".
