### ISSUE TITLE
Invisible internet

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#227]
Hello, recently the american authorities seized a hundred domains of the z-lib library, I think more and more to may be use the invisible internet because z-lib tells us to use tor browser and i2p browser to access the librarie banned from the regular internet through their onion and i2p addresses, and so I was wondering if our beloved media-downlader could download files from the invisible secure encrypted internet hidden on the i2p and onion networks as censorship grows from more and more and even Italian and German justice orders third-party dns providers like cloudflare and quad9 to ban dns attacks from torrent and streaming sites....

I looked for info on the i2p network and I see that you can even download files via bitttorent protocol and the download is encrypted encrypted by the i2p protocol without even needing vpn!

my question is can media -downloader consider supporting dark net and i2p and tor or bittotrrent protocol since censorship on the visible internet is getting tougher?

thank you!

https://fr.singlelogin.me/

https://i2pd.website/

https://geti2p.net/en/

https://censorship.no/en/index.html

https://www.torproject.org/download/

https://dtechclub.com/directory-best-darknet-sites/

**Comment by mhogomchungu** [comment]
Media Downloader supports aria2c and aria2c supports downloading torrents so there is support for downloading torrents in Media Downloader through aria2c though i have never tried it.

Media Downloader is a front end to other tools that deal will media downloading. Creating or establishing secured network connections is outside of its scope.
