### ISSUE TITLE
Can I rename it?

### ISSUE THREAD

**Issue by StrollStars** [mhogomchungu/media-downloader#228]
If a file with the same name exists in the same directory, the program will display:
> file already exists, skipping

Can I continue downloading by renaming? Where should I set it up?

**Comment by mhogomchungu** [comment]
It is not possible.  yt-dlp by default adds "id" to make it harder for file names to collide and if it still happens then you can add "epoch" variable to the "-o" option to make it even harder for file names to collide.

If you want the file name to automatically be renamed then open a feature request with yt-dlp  and make a request there and it will be easier for Media Downloader to support the behavior by adding a relevant option.

**Comment by StrollStars** [comment]
I use lux, can you support it as yt-dlp?

**Comment by mhogomchungu** [comment]
Lux is supported, install [this](https://github.com/mhogomchungu/media-downloader/wiki/Extensions#9-lux) extension to support it. Instructions of how to install are [here](https://github.com/mhogomchungu/media-downloader/wiki/Extensions#how-to-install-extensions)

Lux also do not have an option to automatically rename a file if it already exist.

Why do you want to redownload an existing file?

**Comment by StrollStars** [comment]
@mhogomchungu Thank you for your reply. I used the Lux xtension to download videos from a website, and found that the downloaded files all have the same name.
I give feedback there.

**Comment by mhogomchungu** [comment]
Do you use Linux or Windows version of Media Downloader?

Lux has  "-O" option that allows settings of a file name and the next version of Media Downloader will use this option to allow you to set a file name of your choice together with a unique value that will serve a purpose of making sure each file has a unique name.

Currently supported unique identifiers are:-
1. ```%(autonumber)s```. This variable will be replaced by a number that is equal to the position of the media entry in the UI.
2. ```%(id)s```. This variable will be replaced with a unique id.

Below two images show how these options can be added and how the final file name will be in the UI.

Will keep this feature request open until after i made another release.

![Screenshot_20221122_082916](https://user-images.githubusercontent.com/3496115/203231988-f2a0b4b1-21f1-44ea-8ff8-beb758a5fc92.png)

![Screenshot_20221122_102352](https://user-images.githubusercontent.com/3496115/203250880-43f115a8-be5b-43cf-812b-c395dd26e855.png)

**Comment by mhogomchungu** [comment]
Do you use Linux or Windows version of Media Downloader?

Lux has  "-O" option that allows settings of a file name and the next version of Media Downloader will use this option to allow you to set a file name of your choice together with a unique value that will serve a purpose of making sure each file has a unique name.

Currently supported unique identifiers are:-
1. ```%(autonumber)s```. This variable will be replaced by a number that is equal to the position of the media entry in the UI.
2. ```%(id)s```. This variable will be replaced with a unique id.
3. ```%(title)s```. This variable will be replaced by the media title.

Below images show how above three options can be added and how the final file name will be in the UI.

Will keep this feature request open until after i made another release.

![Screenshot_20221122_151415](https://user-images.githubusercontent.com/3496115/203311411-19f1c8b6-8b66-44d1-8ffc-61eb4bddbe27.png)

**Comment by StrollStars** [comment]
I use Windows version of Media Downloader.
I know the `-O` parameter, so I wrote a batch file to call it to download.
I look forward to the new version of Media Downloader, thanks.

**Comment by mhogomchungu** [comment]
[New version is out](https://github.com/mhogomchungu/media-downloader/releases/tag/2.8.0) and it has a solution for this problem.

To make sure you do not get identical file names, do the following:-
1. Go to configure->engine's default options.
2. Select "lux" in the engines drop down list
3. In the "Options To Add" text field, add "-O %(title)s-%(id)s"
4. Click "Add".
5. Right click the entry you just added and set is as default.

A bad thing about this solutions is file names ending with a bunch of characters that makes no sense. These characters are supposed to be unique and are what makes file names unique. You can also add "%(autonumber)s" to make it possible to know file was at what position in the UI.
