### ISSUE TITLE
file names do not correctly in the playlist title. sign //

### ISSUE THREAD

**Issue by candrapersada** [mhogomchungu/media-downloader#230]
in terminal or Command Prompt
![gambar](https://user-images.githubusercontent.com/36833664/203545355-fb8cf2e0-f132-4662-b00a-fb4f8e767129.png)
in media-downloader
![gambar](https://user-images.githubusercontent.com/36833664/203545733-d5d4bcd3-f840-4011-b859-563cc0c9d8be.png)
![gambar](https://user-images.githubusercontent.com/36833664/203545519-7800c90c-a674-461b-af4c-c2da078f9428.png)
https://www.youtube.com/playlist?list=PLQqD_z157-ZhNbzisySgP_zMNUOrJJXKH
![gambar](https://user-images.githubusercontent.com/36833664/203546685-6d4e9b8a-3d38-4f27-b5f1-fc4154d88d7d.png)

**Comment by mhogomchungu** [comment]
Can you post a screenshot of Media Downloader?  It seems to be working fine here and my screenshot is below.

Go to "Configure->general options" and then put "utf8" in the "text encoding" text fields and try again.

![Screenshot_20221124_152945](https://user-images.githubusercontent.com/3496115/203785106-4312283c-6f11-4328-a385-7ce9ef0fe915.png)

**Comment by candrapersada** [comment]
![gambar](https://user-images.githubusercontent.com/36833664/203817833-ead2e678-3933-4063-b847-54289cb7ae13.png)
`-o "%(uploader)s/%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s"`

**Comment by mhogomchungu** [comment]
So it works now after you added the "utf8" option? 

I do not see the problem in your latest screenshot.

**Comment by candrapersada** [comment]
the problem is that the download folder in the playlist title is incomplete as shown in this image
![image](https://user-images.githubusercontent.com/36833664/204575074-296d2465-a95a-4808-b3fb-30544fa85a0d.png)
![image](https://user-images.githubusercontent.com/36833664/204575168-4ec86dd7-cff5-4a7b-9bc8-76df2b920857.png)

**Comment by mhogomchungu** [comment]
So the problem here is that "title" has  "//" characters sand yt-dlp+Media  Downloader treats them as a folder path while yt-dlp when used alone does not.

**Comment by mhogomchungu** [comment]
Fixed.

The solution is to use ```--parse-metadata``` yt-dlp option and to do the replacement by using  something like
```--parse-metadata 【アニメ】 .hack//G.U.:%(playlist_title)s``` to properly set playlist_title,
![Screenshot_20221130_172929](https://user-images.githubusercontent.com/3496115/204824968-eab9ccab-804e-4318-9b4a-8933541e1421.png)
