### ISSUE TITLE
Chapters

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#231]
Hello, I think donwloading by chapters is more easy and comfortable from manually setting time range, it will be great to add option "split by Chapters "= after the download is complete, save the file by chapter and also add option "chapter lables = only download single chapter (will override the Time Range setting), thank you !

**Comment by mhogomchungu** [comment]
Done and the UI looks like below image.

![Screenshot_20230201_090108](https://user-images.githubusercontent.com/3496115/215964816-a1db944a-417c-42d7-bda7-f513fb4c26f0.png)

**Comment by trimechee** [comment]
Wonderful !!! Thank you very much for all your efforts and generosity to add these amazing awesome options to make Media-Downloader N1 in the world ! 🥇 💯
