### ISSUE TITLE
[Request] Download path button on every tab with the list of prev used paths

### ISSUE THREAD

**Issue by iG8R** [mhogomchungu/media-downloader#237]
Hi.
Could you, please, add the download path button to each tab (Basic, Batch, Playlist) with the remembered drop-down list of the previously used paths and with the last used one selected?

**Comment by mhogomchungu** [comment]
How will you add a new download path to use? You would also need a text field on each tab to put the download path.

This feature will clutter the UI too much and will conflict with download path text field in the configure tab so i am not going to add this.

You can simulate the behavior you want with a preset feature, go to configure tab and then preset options sub tab and below is an example of how to set the option.

1. In the "UI Name" text field, add something like "Network Drive"
2. In the "Options" text field, add something like 

```
-f Default --newline --ignore-config --no-playlist -o $PATH_TO_NETWORK_DRIVE/%(title).200s-%(id)s.%(ext)s
```
3. Press Add and then select this preset option everytime you want to use the network drive as a download path.

You can also simulate the behavior you want by adding engine's default option located at configure and then engine's default options sub tab. An example option to add is

```
--newline --ignore-config --no-playlist -o $PATH_TO_NETWORK_DRIVE/%(title).200s-%(id)s.%(ext)s
```

**Comment by iG8R** [comment]
@mhogomchungu 
Thanks for such a comprehensive answer. It's awesome.
But it will only work if the user will still continue to use the concept inherent in Media Downloader, i.e. when all video will be saved in a maximum of 10-15 directories, otherwise adding new "Network Drive" will turn into a terrible chore, contrary to the very concept of what GUIs are created for, i.e. ease of routine operations and the user's life.
Let's say the user initially wants all downloaded videos to be strictly structured, for example:
```
Music
├Singer1
├Singer2
├Band1
├etc...
```
but the number of singers and bands is initially unknown, they will increase as the user uses Media Downloader.
If everything is dumped into one folder, as it happens now, sooner or later it will look like a mountain of incomprehensible things and find in all this something necessary will be extremely difficult.
Also, if you compare the look of the interface that we have now with what I suggested, does it seem cluttered?
![Media-Downloader-DownloadPath-Modified-2023-01-24_010026](https://user-images.githubusercontent.com/11407417/214177433-7adb3eea-f8a4-43c3-bf1a-1442eb453e45.jpg)

Regarding the conflict with the settings - remove the path setting from the configuration tab and focus on the paths specified in the tabs.
This also assumes that all previously used folders will be remembered.
Yes, I know I can use the -o argument with different options to save to different folders, but then again, this is all a manual chore as opposed to a couple of GUI clicks.
