### ISSUE TITLE
New beta software for m3u8

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#241]
Hello, Sorry for asking because i hope to verify : it seems that our friend Nilaoda is making a new software to download m3u8 and it seems different from N_m3u8DL-CLI beaause it is in beta : Cross-Platform, modern and powerful stream downloader for MPD/M3U8/ISM. English/.

https://github.com/nilaoda/N_m3u8DL-RE

So can this new software just like N_m3u8DL-CLI be integrated in Media-downloader ?

**Comment by mhogomchungu** [comment]
This requested was posted again and i responded in the duplicate.
