### ISSUE TITLE
Can't download from deviantart

### ISSUE THREAD

**Issue by VanTuz5** [mhogomchungu/media-downloader#247]
I'm trying to download a gallery from deviantart usinggallery-dl via the media downloader, but nothing seems to work, giving me the following error:
![image](https://user-images.githubusercontent.com/39066280/219170339-b2c67280-4fd5-42ff-8648-fc802c3fd174.png)
I asked the developer of gallery-dl about this and he answered the following:
That's media downloader's fault for mixing URIs and command-line options. The command should either put all URIs at the end or the beginning, e.g. gallery-dl -o output.mode=terminal oauth:deviantart deviantart.com/viejilloxart/gallery/all/

**Comment by VanTuz5** [comment]
The problem was solved by deleting "default" from "Options" in the url manager settings

**Comment by mhogomchungu** [comment]
What did you put in the url manager that caused the problem and what did you put that solved the problem.

**Comment by VanTuz5** [comment]
The problem was that in the URL manager in the "options" field I entered "default oauth: deviantart", but it was necessary "oauth: deviantart".

**Comment by mhogomchungu** [comment]
This is now fixed by making sure Media Downloader option of ```-o output.mode=terminal``` always start.
