### ISSUE TITLE
not downloading from youtube

### ISSUE THREAD

**Issue by wowxiz** [mhogomchungu/media-downloader#248]
ERROR: [youtube] QTxvUA4l0Vs: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

all updated

**Comment by mhogomchungu** [comment]
I just downloaded from youtube,

Are you sure you are running the latest version of yt-dlp? Go to configure tab->general options->update plugin->yt-dlp
![Screenshot_20230217_090948-1](https://user-images.githubusercontent.com/3496115/219563963-cb2291cf-68e9-447c-93cf-fc9bf064ccc0.png)

**Comment by mhogomchungu** [comment]
It looks like its a new and known problem.

https://github.com/yt-dlp/yt-dlp/issues/6247

**Comment by mhogomchungu** [comment]
New version yt-dlp is out and the problem should be gone if you update using steps provided above.

**Comment by wowxiz** [comment]
its working again ty, next time I'll wait for the next update or go to the yt-dlp github.
