### ISSUE TITLE
Way To Tell Media-Downloader To Use Different Python Version

### ISSUE THREAD

**Issue by richardstevenhack** [mhogomchungu/media-downloader#249]
Hi. I've been using Media-Downloader on openSUSE Leap 15.4.

Leap 15.4 has python version 3.6 as the system python. I have installed python 3.10 separately.

Today yt-dlp reported an issue, which according to their Github page has been fixed in the latest release. I installed the latest version.  However yt-dlp now requires python 3.7 or higher to run. It will not run with python 3.6.

I copied the latest version yt-dlp Python script to /usr/local/bin.

 I am able to run it by calling it like so:
`/usr/bin/python3.10 /usr/local/bin/yt-dlp`

I just updated Media-Downloader to the latest version. It does not recognize the installed version of yt-dlp, saying:

`Checking installed version of yt-dlp
[media-downloader] Failed to find version information, make sure "yt-dlp" is installed and works properly`

Is there any way I can tell Media-Downloader to use python version 3.10 to execute the new yt-dlp the way I can do it from the command line, as shown above, instead of using the system 3.6 Python?.

**Comment by mhogomchungu** [comment]
1. Go to ```$HOME/.local/share/media-downloader/engines.v1``` folder.
2. Open ```yt-dlp.json``` text file with a text editor.
3. Look at the text file and you will see below section.
4. In the "Args" part, replace ```"yt-dlp"``` text with ``` "python3.10","yt-dlp"``` text,
5. Save the file and restart Media Downloader.
```
"Generic": {
            "amd64": {
                "Args": [
                    "yt-dlp"
                ],
                "Name": "yt-dlp"
            },
            "x86": {
                "Args": [
                    "yt-dlp"
                ],
                "Name": "yt-dlp"
            }
        },
```

**Comment by richardstevenhack** [comment]
Outstanding! The checks still fail but the download works!

Much appreciated. Thank you.

**Comment by mhogomchungu** [comment]
1. Set Media Downloader to show version info when starting.
2. Open the terminal and run ```media-downloader --debug``` command to start media downloader.
3. Post the contents of basic tab that shows Media Downloader checking for version info of each backend.

**Comment by richardstevenhack** [comment]
OK, here you go.
`[media-downloader] cmd: "/usr/bin/python3.10" "/usr/local/bin/yt-dlp" "--version"
[media-downloader] Found version: 2023.02.17.334
[media-downloader] Checking installed version of yt-dlp
[media-downloader] cmd: "/usr/local/bin/yt-dlp" "--version"
[media-downloader] Failed to find version information, make sure "yt-dlp" is installed and works properly
[media-downloader] Checking installed version of yt-dlp
[media-downloader] cmd: "/usr/local/bin/yt-dlp" "--version"
[media-downloader] Failed to find version information, make sure "yt-dlp" is installed and works properly
[media-downloader] Checking installed version of ffmpeg
[media-downloader] cmd: "/usr/bin/ffmpeg" "-version"
[media-downloader] Found version: 3.4.9
[media-downloader] Checking installed version of aria2c
[media-downloader] cmd: "/usr/bin/aria2c" "--version"
[media-downloader] Found version: 1.36.0
[media-downloader] Checking installed version of python3
[media-downloader] cmd: "/usr/bin/python3" "--version"
[media-downloader] Found version: 3.6.15`

Note that it checks twice for the version for some reason. 

Also note that I'm running version 2023.02.17.334 of yt-dlp as I noted in my OP. This is a new version the author put up to resolve an issue with some failure to download and is unsupported until a new release comes out which includes the patch. Perhaps when the new release comes out, this issue with Media-Downloader will be resolved as well.

**Comment by mhogomchungu** [comment]
There is already a new released version of yt-dlp. Try with the new released version(2023.02.17).

**Comment by mhogomchungu** [comment]
What is a list of files you have in ```$HOME/.local/share/media-downloader/engines.v1```?

I suspect you have 3 files for yt-dlp and manually set python path to only one of them.

**Comment by richardstevenhack** [comment]
That's the one I'm running. I'm running . It was uploaded because of this issue:
https://github.com/yt-dlp/yt-dlp/issues/6247

I used the version at https://github.com/ytdl-patched/yt-dlp/releases/latest , downloaded today.

Ah, I see the issue with the double-check: I left the original engines JSON in the directory but renamed it with the extension "original". Doesn't solve the failure to detect version, though.

**Comment by richardstevenhack** [comment]
Ah, and looking again, I see there is the edited backup version of the file produced by my editor which is named:
yt-dlp with an ellipsis or something at the end. jEdit produces that on files that it's editing. I'll delete it and try again.

**Comment by richardstevenhack** [comment]
That fixed it. It now find the correct version of yt-dlp.

We can close this one out, I think.

**Comment by richardstevenhack** [comment]
Whoops, wait a minute. It's still checking a second time. Hold on, let me move the original version out of the directory.
OK, that really does fix it. Now it only checks once and finds the correct version.

We're good.
