### ISSUE TITLE
Download speed limited to 7 kb/s

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#252]
Hello, this bug often happens to me, I often download youtube videos using the "worstaudio" preset so the download size is not large and often does not exceed 50mb or 100mb and often the download speed is limited to 7kb/s , I close the program, I restart the computer and I restart the internet box and the download speed returns to normal but now, despite having restarted the computer, internet box... I waited 12 hours, the download in Media-downloader remains at 7kb/s, there is no "logs" option to be able to post the logs in order to find the origin of the bug please?

is it because i'm still using the worstaudio preset that youtube has detected my ip address and is limiting me? i tried to download other files via browser and the speed exceeds 400kb/s, i tried with "lux" in Media-downloader and the download speed exceeds 400kb/s, i tried with yt -dlp aria2c and yt-dlp ffmpag and the speed is 7kb/s! the bug comes from yt-dlp or youtube flange my ip address? I tried with a vpn and the speed in media downloader remains limited to 7kb/s using yt-dlp preset worstaudio :(

**Comment by mhogomchungu** [comment]
Known issue: https://www.reddit.com/r/youtubedl/comments/11dzu0t/anyone_getting_throttled_on_ytdlp_20230217/

**Comment by trimechee** [comment]
Wow that's surprising ! thank you for your help :) i see there is new version ffmpeg 6, maybe yt-dlp ffmpeg will solve the problem..or i think the solution is we have to use another engine "lux" or 'you -get', I tried "worstaudio" preset with lux but it didn't work, we hope our beloved "Media-downloader" will add preset support to "lux" and "you-get", thanks a lot !

For now as a temporary solution I think I will use a website like getvideo to download my files as it has a bookmarklet or use "3D Youtube Downloader" hoping it can download from dailymotion....
in any case thank you so much for all your efforts to make this wonderful software and the addition of new engines like lux and you-get which allow us to work around this bug....

**Comment by trimechee** [comment]
Personaly I think that downloaders should  favor the 360p and 720p resoltions quality in the default settings to download more faster and therefore favor the webm format over the "m4a" or "opus" format for the audio download of youtube videos....

"Only the 720p and 360p (formats 22 and 18) can be downladed at full speed. The other ones (480p, 1080p and above) have to be downloaded with separate video and audio streams (and automatically merged with FFMpeg if installed), and these streams are throttled by YouTube.

When you DL a video, first check the available formats (yt-dlp -F <URLs>) and choose your format (one per yt-dlp command) with yt-dlp -f <format> <URLs> (eg: yt- dlp -f 22 https://www.youtube.com/watch?v=z9yRpdDIJ00 https://www.youtube.com/watch?v=g9f9dzzfyGA). Downlading this way should be faster."

**Comment by mhogomchungu** [comment]
[This](https://www.reddit.com/r/youtubedl/comments/11fuomc/download_capped_for_no_reason/) person describes format 22 as "insanely low quality" and this comment should be enough to show that using this format as a default is not a good idea because people will be asking why they are not getting a better quality video "out of the box" as they expect.

The preset default options are broken, they are always there but they work only with youtube-dl/yt-dlp and are specific for youtube.

Closing this one because the reported problem is not with Media Downloader but with yt-dlp.

**Comment by trimechee** [comment]
👍
