### ISSUE TITLE
Feature request - integrate with browsers via Plasma Integration extension ?

### ISSUE THREAD

**Issue by linuxguy123** [mhogomchungu/media-downloader#255]
Would it be possible to add a button to Media Downloader to grab the current URL from a browser via the Plasma Integration extension shipped with KDE ?  It would save the user from having to copy and paste the URL.

**Comment by mhogomchungu** [comment]
Press the button seen in the below image to make batch downloader monitor clipboard contents.

![Screenshot_20230312_093943](https://user-images.githubusercontent.com/3496115/224528800-252e5f9c-62c5-4245-ae08-f33acde7f46e.png)

**Comment by mhogomchungu** [comment]
I think the support is already there in Media Downloader for external integration. 

1. To start Media Downloader with Url in batch tab, run ```media-downloader -u $URL```
2. To start Media Downloader with Url in batch tab and start downloding, run ```media-downloader -a -u $URL```
3. Add option ```-s``` if you do not want to reuse an existing instance.
