### ISSUE TITLE
Drag and drop works to Enter URL control but wrong URL is added to the download list.

### ISSUE THREAD

**Issue by linuxguy123** [mhogomchungu/media-downloader#256]
The Enter URL control on the Batch Downloader tab allows the user to drag a URL from a browser (FF and Brave, anyway) to the box, where it is correctly displayed.   However, when it is added to the URL to Download list, the last URL is added instead of the URL that was dropped into the Enter URL field.

If the list is empty, the correct URL is added to the list.   If the list has items in it, the last URL is added again instead of the URL that was dropped into the box.

```
$ dnf list media-downloader
download.vscodium.com                                                                       1.8 kB/s | 866  B     00:00    
Installed Packages
media-downloader.x86_64                                    2.9.0-1.fc37 

Operating System: Fedora Linux 37
KDE Plasma Version: 5.27.2
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.15-200.fc37.x86_64 (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 5900X 12-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
```

**Comment by mhogomchungu** [comment]
I can not reproduce this one.
