### ISSUE TITLE
Text missing from some controls.

### ISSUE THREAD

**Issue by linuxguy123** [mhogomchungu/media-downloader#257]
The buttons to the right of Enter URL and Download Options are not displaying text.  Similar buttons on other tabs are also missing text. 

```
$ dnf list media-downloader
media-downloader.x86_64                                    2.9.0-1.fc37 

Operating System: Fedora Linux 37
KDE Plasma Version: 5.27.2
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.15-200.fc37.x86_64 (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 5900X 12-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
```

![Media Downloader missing text](https://user-images.githubusercontent.com/1920754/224515329-55f99719-7c8f-4321-9514-719e9d775932.png)

**Comment by mhogomchungu** [comment]
Its by design and texts are in the button's tooltip.

There is simply no room to expand the buttons to accommodate their texts.
