### ISSUE TITLE
yt-dlp.conf file

### ISSUE THREAD

**Issue by Useless-Panda** [mhogomchungu/media-downloader#259]
is there a way to use yt-dlp.conf with media downloader

**Comment by Useless-Panda** [comment]
i figured it out, i used this command

`--config-location` "yt-dlp.conf"`

**Comment by mhogomchungu** [comment]
What operating system are you using?

**Comment by ibigfire** [comment]
> What operating system are you using?

Windows 10.  Thank you for any help you're willing to offer.

**Comment by mhogomchungu** [comment]
There are a bunch of places you can put ```gallery-dl.conf``` and one of them is next to gallery-dl executable.

Click a button pointed to in the below image and then place ```gallery-dl.conf```` file in that folder and gallery-dl should start using your config file.

![Screenshot_20230806_223942](https://github.com/mhogomchungu/media-downloader/assets/3496115/ce202612-0a26-4936-8e68-ea70efb1c324)

**Comment by ibigfire** [comment]
Great!  I'll give that a shot.  Thanks very much! 👍
