### ISSUE TITLE
RSA SSH host key

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#260]
Hello, the press is talking about a serious security problem that has affected github since its inception even for paying users and that it could lead to a massive lawsuit against github....
 github is reassuring and so my question is is this the program code is compromised? should we uninstall the software while waiting for the code to be reviewed?

https://www.theregister.com/2023/03/24/github_changes_its_ssh_host/

https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

https://securite.developpez.com/actu/342770/GitHub-publie-sa-cle-d-hote-RSA-SSH-by-error-in-un-referentiel-public-sur-sa-plateforme-l- company-has-updated-the-compromised-key-and-encourages-users-to-delete-it/

**Comment by mhogomchungu** [comment]
Thanks for making this project aware of this issue.

This issue does not affect us at all.

**Comment by trimechee** [comment]
Great ! 💯
