### ISSUE TITLE
Gallery-dl albums and other questions

### ISSUE THREAD

**Issue by Scientist07** [mhogomchungu/media-downloader#271]
1. Is there a way to have the built in gallery-dl extension place content into subfolders? As it stands, different albums from the same site go into one folder with that site name and are not separated. Is there some option I'm missing to fix this? 

2. Why are video download speeds capped so low for gallery-dl? I've used other tools before and never had such bad download speeds for vids. Is this a limitation with gallery-dl?

3. Does the tool have a queue functionality or at least allow for multiple instances? If I want download more than one thing, I'm forced to wait for each download to complete before I can start a new one. That becomes inefficient if one has many tasks to perform.   
**EDIT**: I assume batch download is what I'm looking for in regards to number 3

**Comment by mhogomchungu** [comment]
1. I do not think there is an option for that and the best place to discuss this feature is with gallery-dl project. A workaround i have found is manually setting "-D" option when downloading. If for example your download path for galley-dl is at ```C:\downloads\gallery-dl``` then  put the following in Media Downloader's "Download Options" text field: ```-D "C:\downloads\gallery-dl\$ABC"``` where "$ABC" is a unique folder name you want for all files to be downloaded. With this workaround, you will have to do one download at a time and change the "$ABC" part for every download.
2. This is a question for gallery-dl project.
3. Start the app with "-s" argument to force another instance to start. Yes, batch downloader tab is there to allow for concurrent downloading.

**Comment by Scientist07** [comment]
1. I saw that workaround mentioned before but was hoping for a more automated solution. Sucks that this makes you have to download one at a time. I assume if you have multiple instances you can bypass this side effect.
2. Ok..I'll go try there.
3. What do you mean by this? Where am I putting in "-s"?

**Comment by mhogomchungu** [comment]
1. What operating system are you using media downloaderwith?
2. If windows, are using portable version or installed version?

**Comment by Scientist07** [comment]
Windows 10, installed version.

**Comment by mhogomchungu** [comment]
![Screenshot_20230504_103530](https://user-images.githubusercontent.com/3496115/236140012-2d3658c8-5ae4-4d6d-9511-3b3f8d2bf8a1.png)

If you always want to have multiple instances of Media Downloader to run then do the following:-
1. Right click the application icon on the Desktop and then click properties.
2. In the "target" section, add "-s" at the end making sure there is a space character between what was there and what you are adding.
3. Click "OK".

**Comment by mhogomchungu** [comment]
>I also noticed that the batch downloader tab has a "Download Options" field as well. Since you said I would have to download one at a time if I'm using the workaround, I assume I can't type the same commands there as I did for single download. What options does this field support then?

It does the same thing as in basic downloader tab. If you only have one entry in the batch downloader tab then the net result is the same as if you were using basic downloader tab.

The point of batch downloader tab is to do multiple downloading at a time. This does not work in your case because whatever is in "Download Options" when "Download" button is pressed will be applied to all entries in the tab while in your case, you want each entry to have its own -D option.

**Comment by Scientist07** [comment]
> ![Screenshot_20230504_103530](https://user-images.githubusercontent.com/3496115/236140012-2d3658c8-5ae4-4d6d-9511-3b3f8d2bf8a1.png)
> 
> If you always want to have multiple instances of Media Downloader to run then do the following:-
> 
>     1. Right click the application icon on the Desktop and then click properties.
> 
>     2. In the "target" section, add "-s" at the end making sure there is a space character between what was there and what you are adding.
> 
>     3. Click "OK".

Thanks a lot man. It worked.

**Comment by Scientist07** [comment]
> > I also noticed that the batch downloader tab has a "Download Options" field as well. Since you said I would have to download one at a time if I'm using the workaround, I assume I can't type the same commands there as I did for single download. What options does this field support then?
> 
> It does the same thing as in basic downloader tab. If you only have one entry in the batch downloader tab then the net result is the same as if you were using basic downloader tab.
> 
> The point of batch downloader tab is to do multiple downloading at a time. This does not work in your case because whatever is in "Download Options" when "Download" button is pressed will be applied to all entries in the tab while in your case, you want each entry to have its own -D option.

Ahh I see. Well thanks for all your help and this piece of software.
