### ISSUE TITLE
Sibnet videos bug

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#273]
Hello, this web site contains many videos son i hope to donwload them, for exemple thise video : 

https://video.sibnet.ru/video2736327-Tokyo_Ghoul_S02_E02_VF_www_vostfree_com/?utm_source=player&utm_medium=video&utm_campaign=EMBED

I tried with Media-Dowloader but sadly Media-Dowloader can't download it although this site is supported by yt-dlp, and I tried with another open-source program which also uses yt-dlp and this downloader was able to download this same video from the sibnet.ru site, so logically the problem does not seem be caused by yt-dlp because the other downloader use  yt-dlp and it was able to download this video, I hope our beloved media-downloader will fix this bug, thanks !

**Comment by mhogomchungu** [comment]
Worked fine here,what error are you getting?

![Screenshot_20230501_013018](https://user-images.githubusercontent.com/3496115/235378981-bf420660-656a-45a9-b2a9-d9df8bac31e1.png)

**Comment by trimechee** [comment]
It's amazing ! i thought basic downloader is the most suitable for downloading this kind of individual video, because i reserve batch donwloader only for presets like "bestaudio"....with basic downlader i got void, empty space, none analysis of the video that's why I thought there was a bug....but I just tried with batch downloader after deleting the preset values and it worked ! Tahnks  :)

**Comment by trimechee** [comment]
I tried with another site using the basic downloader and it works!!

https://www.myvi.ru/watch/HYQWu25WLkyaX_QzrJeUtA2

my mistake was not to have erased what was in the "donwload options" box in basic donwloader (delete the presets), and i have to do the same thing in batch downloader to be able to download the videos....maybe it will be more practical and simple to add a button to delete with a simple click what is in the "download options" box....
