### ISSUE TITLE
Media Downloader 1.3.0 - GUI issue

### ISSUE THREAD

**Issue by bovirus** [mhogomchungu/media-downloader#278]
@mhogomchungu 

Is this issue aboiut GUI text string depending not update version of application

![image](https://user-images.githubusercontent.com/1262554/236765148-f8b386ee-7490-4e3c-84a2-d6bce25ff0f4.png)

**Comment by mhogomchungu** [comment]
When the program starts for the first time, those options are read from the application and then stored on disk and then they start being read from disk.

If you want to reset those options to the current version of the application then click the button pointed at in the below image.

![Screenshot_20230508_143217](https://user-images.githubusercontent.com/3496115/236813626-e6bd91b2-0a72-4e2f-95d6-9df7514ee856.png)
