### ISSUE TITLE
[REQUEST] Remove the Thumbnail column from Batch downloader section

### ISSUE THREAD

**Issue by cinetube** [mhogomchungu/media-downloader#281]
Please add a option to hide the Thumbnail column from Batch Downloader section.

**Comment by mhogomchungu** [comment]
Why you don't want to see the thumbnail column?

**Comment by cinetube** [comment]
> Why you don't want to see the thumbnail column?

I found the thumbnail column useless for me. It would have been better if you replaced the thumbnail column with download progress section which would include a simple progress bar.

**Comment by mhogomchungu** [comment]
The next version will have an option as seen in the below image.

 When the option is set:-
1. Thumbnail column will be visible and will contain the media thumbnail.
2. Other metadata that will be shown are media title, media duration, and media upload date.

When the option is not set:
1. The thumbnail column will not be displayed.
2. No metadata will be downloaded and displayed.

![Screenshot_20230520_110236](https://github.com/mhogomchungu/media-downloader/assets/3496115/1366b50f-1ff7-4e84-a9d8-3ed568a1f6fd)
