### ISSUE TITLE
Make Media-Downloader compatible with stream-detector extension commands

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#284]
Hello, I am trying to download the video from the Uqload player of this site

https://vostfree.ws/845-hello-world-vostfr-movie-ddl-streaming-1fichier-uptobox.html

using the stream-detector extension:

https://github.com/54ac/stream-detector

by activating the option  "copy stream url as yt-dlp" command" of the addon "stream-detector" then I play the video Uqload and copy paste the url obtained from stream detector in media-downloader but media-downloader does not succeed to download the video from Uqload, streaming sites seem to have strengthened their mechanism to prevent downloading videos easily, I hope that media-downloader will add an option to receive commands from the "stream detector" extension and so on download the video, I even tried to change the engine in my media -dowloader to wget and ariac2c by activating the "use external dowloader for yt-dlp" option of the "stream-detector" extension but it doesn't work no....i also hope that we can preview and preview and watch the part downloaded by media-downloader with a video player without waiting for the download of the video to finish so it will be great that media-donwloader does not download bcp section at the same time to speed up the download but just a segment so that we can watch the video before the end of the download, thank you very much !

Edit : i verify and Uqload platform is supported by yt-dlp so media-downloader is spposed to be able to download from Uqload..... 

https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md

i find also another video extension open source and it will be great to make it compatible with the download manger, thank you :)  

https://github.com/chandler-stimson/live-stream-downloader

**Comment by mhogomchungu** [comment]
>by activating the option "copy stream url as yt-dlp" command" of the addon "stream-detector" then I play the video Uqload and copy paste the url obtained from stream detector in media-downloader 

Paste here the command you send to Media Downloader

**Comment by trimechee** [comment]
I found another open source extension that may be can have integration with Media-downloader : 

https://github.com/puemos/hls-downloader
https://puemos.gitbook.io/hls-downloader/

**Comment by mhogomchungu** [comment]
I wanted to work on this and just discovered this extension is be abandoned by its author.

**Comment by trimechee** [comment]
Hello, the developer talked about that in the summer, he did not say that he was definitively abandoning the extension, but just the development of new features is on pause,....the extension is mature and development is focused on fix the bugs for the moment and perhaps the developer does not have the time at the moment to fully concentrate on the extension....I will try to check the progress of the development of this extension and if that it doesn't  bother you, I will inform you if the developer made new update in sha Allah, we thank you very much for having considered working on this extension :) and I will try to see if there are forks or equivalent to this extension.....

**Comment by mhogomchungu** [comment]
All the links you provided do not work.

The extension on firefox do not detect any links with the url you provide in your original post

**Comment by mhogomchungu** [comment]
Support is done.

Some things are easier implementing them than they seem when thinking about them :-)

**Comment by trimechee** [comment]
Wow, magnificent, exceptional awesome ! I think this exceptional magnificent rare sensational grest feature should be added to the description page of our beloved Media-Downloader, perhaps to the "extension" section....I will try to contact the developer of this extension to inform him of the support of his extension by the superb Meda-Downloader manager and suggest to him as soon as he has time available, he should continue to develop this extension....


I also think to thank you for your efforts and participate in the development of the project, when we install or update Media-Downlaoder, the sponsor button must appear first so when in the github page, I read that we can earn money if people watch the ad, so suggest users click and watch 30-second or 1-minute ads to support the project....
, so i think our beloved  Media-Downloader should automatically display or open some non-intrusive ad windows to support development, or display a donation message....and maybe add an option to disable ads for those who don't want to not have advertising, or enter into partnerships and bundle the program with partner softwares and users will have the choice to accept ou refuse the install of the partner software which sponsors the project, for example anti-virus software.....

**Comment by trimechee** [comment]
I see the great developer of great Ultrawideo extension made the decision to transform its extension into closed source especially with the introduction of manifest v3 which adds security, and I approve of this decision :

 https://github.com/dvlden/uw-pub



 I think that Media-Dowloader must immediately become closed source to protect your work from theft and falsification and fake versions, especially beacuas we knows the name of the trusted great developer Mr Francis Banyikwa, I think the software is mature and excellent and no need to add more new features, whoever asks you to add new features must make a donation, I think for example the options and extensions to download photos from Instagram must become paid....



"UltraWideo cross-browser extension is no longer open-source. Why? Because it contains premium features and having it open-sourced in the past had no value. I strongly believe that v3 and onwards will keep user's trust and security, even as a closed-source.

Decision to create a pub (a place for all users) is now mainly for:

⚠️ [Issues](https://github.com/dvlden/uw-pub/issues) | 💭 [Discussions](https://github.com/dvlden/uw-pub/discussions) | 📋 [Planning](https://github.com/users/dvlden/projects/2) | 📚 [Learning](https://github.com/dvlden/uw-pub/wiki)

But later on, you'll be able to vote for the next features and that way contribute in its development.

© [UltraWideo](https://uw.wtf/). All rights reserved."

**Comment by trimechee** [comment]
In github page of Stream-Detector, there is good news, officially the development of this extension is not abandoned but just paused because the developer has other projects to do...so it is wonderful news that Media-Downlaoder adds support for this extension so we can download complicated embed hidden videos ! 👍 

"After over 100 closed issues and 60 GitHub releases, as of v2.11, the repo is being archived until further notice due to lack of free time and focusing on work and other projects. Serious issues and minor features might still be addressed, but active development has been put on hold."

https://github.com/54ac/stream-detector?tab=readme-ov-file#additional-notes

**Comment by trimechee** [comment]
And bout all the links i provided do not work, perhaps because they are old links dating from May 2023.....here are my favorite streaming sites where there are links from uqload platform, please use dns0 , or dns quad9 or dns cira or cleandns or dns cloudflare or dns google if the uqload platform is blocked, or use the free vpn proxy of opera web browser or psiphon vpn or lantern vpn or windscribe vpn or hola vpn....

https://french-anime.com/

https://wiflix.voto/

https://wiflix.name/

https://wiflix-news.com/

**Comment by trimechee** [comment]
I find In reveiws of firefox addons, users say : 

"It was working great but now most of the time, I have to reload the page for it to work.

It doesn't capture anything unless you reload the page.


Very nice addon, although it be nice if MPV or VLC (or both) were included by default (instead of user custom command), also maybe in settings a filter list of some sort so video title (based on page title) you can add "[space]- Websitenamehere" and on new line something else..."


https://addons.mozilla.org/en-US/firefox/addon/hls-stream-detector/reviews/


Excuse me agaIn Mr @mhogomchungu ,   I read these reviews in mozilla addons store and i am not sure any more if I understood correctly how stream detector extension  works correctly ! so we must install also " yt-dlp" and "streamlink" softwares with Media-Downloader manager to be able to copy the commands with all of the necessary cookies and headers ? because it seems streamlink also allows users to stream and download at the same time..... so can we send streamlink links to Media-Downloader ?
