### ISSUE TITLE
[feature] Add a field to rename the video(s) when downloading it

### ISSUE THREAD

**Issue by BarbzYHOOL** [mhogomchungu/media-downloader#287]
Hello,
it would be pretty useful, i often DL youtube videos named like bullshit, so i have to rename them by opening the file manager etc, kinda annoying

**Comment by mhogomchungu** [comment]
Current format for filenames is title-id.extension. What format do you want your file names to be in?

Steps to take to make file name the way you want it are explained [here](https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#3-how-to-make-downloaded-media-not-have-weird-text-in-the-file-name)

**Comment by BarbzYHOOL** [comment]
@mhogomchungu i'd like to change the name of each video as soon as i download it, for example, with an extra field in the  single video download tab, not following a pattern
