### ISSUE TITLE
Bandcamp playlist no longer downloading

### ISSUE THREAD

**Issue by tc36** [mhogomchungu/media-downloader#288]
Apologies if I make any mistakes in this post, never used github to report issues, made an account specifically for this

I'm attempting to download a bandcamp album using the playlist feature, which has never been an issue for me. I'm using the following argument, which has always worked perfectly:

`bestaudio -x --embed-thumbnail --audio-format flac --embed-metadata -o "%(artist)s/%(album)s/%(title)s"`

Now when I enter the url and click "get list" it appears to be processing as normal (and the log window checks out) but no list populates, and downloading doesn't do anything. 

Attachment 1 shows the "Get List" results and attachment 2 shows the log window 

This issue happens in multiple versions of media-downloader, I'm able to download directly via yt-dlp.exe just fine

![Screenshot 2023-06-23 075135](https://github.com/mhogomchungu/media-downloader/assets/137507037/95836f8a-2463-444c-9a3a-af4cfdb3a0ad)
![Screenshot 2023-06-23 075206](https://github.com/mhogomchungu/media-downloader/assets/137507037/883a5288-ed93-4a0c-a736-519f11f42e1e)

**Comment by tc36** [comment]
Commenting to add: I've done a number of clean installs to verify it isn't a config issue

**Comment by mhogomchungu** [comment]
1. Make sure Media Downloader is using the latest version of yt-dlp.

2. Can you post a url so that I can test locally.

**Comment by tc36** [comment]
1) Just manually updated the yt-dlp.exe within the media-downloader bin folder and it still isnt functioning properly.
Do I need to make any configuration adjustments?

2) try this link https://filmschoolmusic.bandcamp.com/album/brilliant-career

**Comment by mhogomchungu** [comment]
Media Downloader can not parse metadata even on YouTube in both Batch
downloader tab and playlist downloader tab when using the latest version of
yt-dlp(2023.06.22).

The only solution here is downgrade yt-dlp to a previous version until
Media Downloader is updated.

**Comment by tc36** [comment]
I reverted back to version 2023.3.4.0 of yt-dlp and that fixed the issue

**Comment by mhogomchungu** [comment]
I have found the problem and have reported it here:
https://www.reddit.com/r/youtubedl/comments/14fxqlm/comment/jp8hnh2/

**Comment by mhogomchungu** [comment]
I just released a new version and it has a fix for the latest version of
yt-dlp.
