### ISSUE TITLE
Presets are gone after update.

### ISSUE THREAD

**Issue by filchcomp** [mhogomchungu/media-downloader#289]
The custom commands/presets I created are gone after the update. When I open the presets list, all I can see are the default ones.

**Comment by filchcomp** [comment]
3.2.0, Windows, portable version.

**Comment by mhogomchungu** [comment]
I can not reproduce this, do you also have installed version of MD? Maybe your lost options are still there but they are in the installed version.

Can you readd your lost preset option?

**Comment by filchcomp** [comment]
Yeah, I have the installed version now. 
Perhaps the file is still there, but I could not find info on which file contains the presets.
Program also keeps redownloading youtube-dlp when I launch it.

**Comment by mhogomchungu** [comment]
Post contents of the basic downloader tab after it is done updating yt-dlp so that i can see why it is failing.

In portable version, preset options are in a file named "presetOptions.json" and the file is located in "portable version folder"/local/data.

In the installed version, preset options are a file named "presetOptions.json" and the file is located in "C:\users\USER\Application Data\media-downloader\media-downloader\data"

**Comment by filchcomp** [comment]
Thanks, I found the presets intact.

The contents of the basic downloader tab:
Here's some extra: Mediadownloader itself keeps updating to 3.2.1 too, while staying on 3.2.0.
[media-downloader] Checking installed version of OpenSSL
[media-downloader] Found version: OpenSSL 1.1.1j  16 Feb 2021
[media-downloader] Checking installed version of Media Downloader
[media-downloader] Found version: 3.2.0
[media-downloader] Newest Version Is 3.2.1, Updating
[media-downloader] Start Downloading Media Downloader ... ...
[media-downloader] Downloading: https://github.com/mhogomchungu/media-downloader/releases/download/3.2.1/MediaDownloader-3.2.1.zip
[media-downloader] Destination: C:/Users/YJ/AppData/Roaming/media-downloader/update/local/tmp/MediaDownloader-3.2.1.zip
[media-downloader] Downloading Media Downloader: 70.23 MiB / 70.23 MiB (100.00%)
[media-downloader] Extracting archive: C:/Users/YJ/AppData/Roaming/media-downloader/update/local/tmp/MediaDownloader-3.2.1.zip
[media-downloader] Update Complete, Restart To Use New Version
[media-downloader] Checking installed version of yt-dlp
[media-downloader] Found version: 2023.06.22
[media-downloader] Newest Version Is 2023.07.06, Updating
[media-downloader] Start Downloading yt-dlp ... ...
[media-downloader] Downloading: https://github.com/yt-dlp/yt-dlp/releases/download/2023.07.06/yt-dlp.exe
[media-downloader] Destination: C:/Users/YJ/AppData/Roaming/media-downloader/update/local/bin/yt-dlp.exe.tmp
[media-downloader] Downloading yt-dlp: 13.30 MiB / 13.30 MiB (100.00%)
[media-downloader] Download complete
[media-downloader] Renaming file to: C:/Users/YJ/AppData/Roaming/media-downloader/update/local/bin/yt-dlp.exe
[media-downloader] Checking installed version of yt-dlp
[media-downloader] Found version: 2023.07.06
[media-downloader] Checking installed version of aria2c
[media-downloader] Found version: 1.36.0
[media-downloader] Checking installed version of wget
[media-downloader] Found version: 1.21.3
[media-downloader] Checking installed version of ffmpeg
[media-downloader] Found version: n5.0-5-g426b7f48d9-20220308
[media-downloader] Checking installed version of aria2c
[media-downloader] Found version: 1.36.0

**Comment by mhogomchungu** [comment]
Found the problem and the solution is for below folder to not exist.

```
C:/Users/YJ/AppData/Roaming/media-downloader/update/local
```

The update folder should only contain "media-downloader.exe" and "translations" folder. The code that deleted rest of the stuff in the "update" folder did not work in the installed version.

**Comment by mhogomchungu** [comment]
I have updated "MediaDownloader-3.2.1.zip" version with a fix to the problem. Allow it to auto update one more time to get the updated version.
