### ISSUE TITLE
How to Build On Windows?

### ISSUE THREAD

**Issue by titus-shoats** [mhogomchungu/media-downloader#29]
Helloi see instructions to build on linux, but is there a way to compile and build this on windows? I tried opening it up in Qt Creator but I get tons of compile errors. Any advice?

**Comment by mhogomchungu** [comment]
Did you open the "CMakeLists.txt" file with Qt Creator?

The "media-downloader.pro" file is there only to translation purposes and the build system is cmake based.

What errors did you get? I also use mingw version of Qt and NOT visual studio version, which one are you using?

**Comment by titus-shoats** [comment]
Thanks that worked! Is there a way to compile this with visual studio ?

**Comment by mhogomchungu** [comment]
About OpenSSL, run Qt maintenance tool and look for OpenSSL and install it(Look at the image below where its located in the tool).

After you have install it, go to "C:\Qt\Tools\OpenSSL\Win_x86\bin" and copy "libcrypto-1_1.dll" and "libssl-1_1.dll" to media downloader folder and that should do it.


![Screenshot_20210526_220201](https://user-images.githubusercontent.com/3496115/119717027-785d6a00-be6e-11eb-9f22-bd9653594d59.png)

**Comment by mhogomchungu** [comment]
I got FFMPEG from here[1] and the link to the latest full version is here[2].

Download it and put ffmpeg folder in "3rdParty" subfolder and that should do it. You can delete all other binaries and leave only "ffmpeg.exe" because the only one that is required.

I do not have these binaries in git because the ffmpeg binary is massive and will make cloning the repository a very annoying experience.

[1] https://www.gyan.dev/ffmpeg/builds/
[2] https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z

**Comment by mhogomchungu** [comment]
If you want a portable version then create a folder named "local" and put it next to "media-downloader.exe executable.

**Comment by titus-shoats** [comment]
What version of Qt Creator are using to get the OpenSSL Toolkit?

**Comment by mhogomchungu** [comment]
Not Qt Creater, the tool is called ```Qt Maintenance tool``` and it should be installed in your system and it is the tool to use to update Qt or Qt Creator and other supporting libraries like compiler.

**Comment by mhogomchungu** [comment]
Not Qt Creater, the tool is called ```Qt Maintenance tool``` and it should be installed in your system and it is the tool to use to update Qt or Qt Creator and other supporting libraries like compiler.

**Comment by titus-shoats** [comment]
Great, got it fully compiled, thanks so much @mhogomchungu .. Awesome project by the way!

**Comment by titus-shoats** [comment]
And Lastly, for the portable version, I'm assuming I need to manually copy those 3 other folders into the local folder?

**Comment by mhogomchungu** [comment]
Yes
