### ISSUE TITLE
Cannot update, it does not extract

### ISSUE THREAD

**Issue by BarbzYHOOL** [mhogomchungu/media-downloader#290]
> [media-downloader] Extracting archive: /home/xxx/.local/share/media-downloader//tmp/MediaDownloader-3.2.0.zip

it never completes, and i checked the dir, it didn't extract anything

also i cannot stop the update from happening because it starts auto and can't edit conf

**Comment by mhogomchungu** [comment]
There is a bug here, auto updating of Media Downloader should be available for windows only.

**Comment by mhogomchungu** [comment]
Fixed [here](https://github.com/mhogomchungu/media-downloader/commit/31ba34c5e284a87773581782bda9f5fe711e01fb), will make a new release shortly and then i will close this bug report.

**Comment by mhogomchungu** [comment]
New release is out: https://github.com/mhogomchungu/media-downloader/releases/tag/3.2.1

**Comment by BarbzYHOOL** [comment]
> New release is out: https://github.com/mhogomchungu/media-downloader/releases/tag/3.2.1

i tried the auto update again, it failed

do i need to redownload it manually first (seems logic but just to make sure)??

**Comment by mhogomchungu** [comment]
The app can update itself either manually or automatically on in Windows.

Since you are not using a windows system, you have to manually update outside of Media Downloader.

You said you installed a flathub? from where? I am not aware of any flathup package for this project

**Comment by BarbzYHOOL** [comment]
ok i thought you fixed it for linux lol

na, apparently i installed it from the deb, i can just update with apt
