### ISSUE TITLE
Downloading from YouTube: Metadata?

### ISSUE THREAD

**Issue by thenormal** [mhogomchungu/media-downloader#297]
Hello. I just downloaded this program for my Windows machine. When it comes to downloading YouTube videos, I was wondering if there is a way to also download the Metadata (video description, tags, etc...) that comes with every video.

Regards.

**Comment by mhogomchungu** [comment]
"You don't need my permission to make this program do what you want" is the motto of this program. All tabs have a "download options" text field front and center to allow you to easily enter whatever options you want to make a yt-dlp behave to your liking.

To get video descriptions for example, add an option "--write-description"
