### ISSUE TITLE
Bug: "[media-downloader] Download Failed(ErrorCode=1)" & media-downloader thinking the download options are urls

### ISSUE THREAD

**Issue by metapea** [mhogomchungu/media-downloader#298]
I keep getting this when using bestvideo+bestaudio in the download options: 
```
[generic] Extracting URL: bestvideo+bestaudio
ERROR: [generic] None: 'bestvideo+bestaudio' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:bestvideo+bestaudio" ) to search YouTube
```
and in the end of the download:
`[media-downloader] Download Failed(ErrorCode=1)`
Most of the time, videos download fine even with the error, but a few times it ignored the download options and just downloads the video without it.

**Comment by mhogomchungu** [comment]
Put below text in the "download options" text field and try again.

-f bestvideo+bestaudio

**Comment by metapea** [comment]
It was in the download options:
![ytdlp](https://github.com/mhogomchungu/media-downloader/assets/35351174/e1a5545d-fa7b-4622-81f0-16152b825d84)

**Comment by mhogomchungu** [comment]
What i observed here is as follows:-
1. You have to put "-f bestvideo+bestaudio" in basic downloader tab.
2. Batch downloader tab works just fine with or without "-f".
3. Playlist downloader tab wors just fine with or without "-f".

It is best to always put "-f" and yes, this is a bug since basic downloader tab should work the same as other tabs.

**Comment by metapea** [comment]
Thanks

**Comment by mhogomchungu** [comment]
This is fixed now.

**Comment by rosesr** [comment]
Is my install out of date if I'm still having this issue? Or is this fixed in the upcoming patch? No worries if so, just want to make sure I have it configured properly as-is.

**Comment by mhogomchungu** [comment]
The fix is already in but it is not released yet so not available to the general public.

The fix will be available to the general public when i make a new release. For now, put the "-f" argument until when a new released is out.

**Comment by mhogomchungu** [comment]
New version is out and it has a fix for this problem

https://github.com/mhogomchungu/media-downloader/releases/tag/3.3.0
