### ISSUE TITLE
Feature requests: A second "download options" text field for FFmpeg when using yt-dlp-ffmpeg

### ISSUE THREAD

**Issue by metapea** [mhogomchungu/media-downloader#300]
FFmpeg has options as well and there's no way to used them, since the download options is only for yt-dlp.
For the people using the yt-dlp-ffmpeg, it would nice to also have a text field for FFmpeg or use the "download options" text field and put "ffmpeg:" in the same text field to use FFmpeg 
I've seen users here having a hard time using FFmpeg in [yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/7607), so hopefuly this would make it easier.

**Comment by mhogomchungu** [comment]
It should be fine putting those ffmpeg in the "download options" text field.

**Comment by metapea** [comment]
> It should be fine putting those ffmpeg in the "download options" text field.
This was made before finding out about the bug report for yt-dlp with the info for `--use-postprocessor FFmpegCopyStream`. Right now instead of copy and pasting `FFmpegCopyStream`, i still think it would be a nice optional qoe feature to have.

**Comment by mhogomchungu** [comment]
Officially, you can download with yt-dlp using ffmpeg or aria2c, add an option for one and another person will ask for the same option for the other.

The "download option" text field should be good enough.
