### ISSUE TITLE
[media-downloader] Download Failed(ErrorCode=1)

### ISSUE THREAD

**Issue by BarbzYHOOL** [mhogomchungu/media-downloader#303]
When I try to DL with the lowest quality possible, I am forced to click on "Get list" right?
Then I choose the 144p option for audio/video by clicking on it

And invariably, I get this kind of output

```
ERROR: [generic] None: '17' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:17" ) to search YouTube
[youtube] Extracting URL: https://www.youtube.com/watch?v=oFxCqG437wc
[youtube] oFxCqG437wc: Downloading webpage
[youtube] oFxCqG437wc: Downloading ios player API JSON
[youtube] oFxCqG437wc: Downloading android player API JSON
[youtube] oFxCqG437wc: Downloading m3u8 information
WARNING: [youtube] Cannot parse localized time text "Jul 25, 2023"
[info] oFxCqG437wc: Downloading 1 format(s): 248+251
[download] Destination: IF YOU ARE AFRAID OF LEARNING HANDSTAND THESE DRILLS ARE FOR YOU!-oFxCqG437wc.f248.webm
[download] 17,42 MiB / 17,42 MiB (100%) at 4,54 MiB/s, ETA NA
[download] Destination: IF YOU ARE AFRAID OF LEARNING HANDSTAND THESE DRILLS ARE FOR YOU!-oFxCqG437wc.f251.webm
[download] 2,18 MiB / 2,18 MiB (100%) at 4,42 MiB/s, ETA NA
[Merger] Merging formats into "IF YOU ARE AFRAID OF LEARNING HANDSTAND THESE DRILLS ARE FOR YOU!-oFxCqG437wc.webm"
[media-downloader] Download Failed(ErrorCode=1)
```

the option is not recognized, the video is high quality and there is a "download failed" error

**Comment by mhogomchungu** [comment]
You did not put the whole log output because i do not see the yt-dlp command executed on your output.

If you are using basic downloader tab then switch to batch downloader tab and your problem is the same as this one: https://github.com/mhogomchungu/media-downloader/issues/298

**Comment by BarbzYHOOL** [comment]
i always click on the option "17" and it replaces the options in the option field by `17` and not `-f 17`, that's probably the cause of the bug??

**Comment by mhogomchungu** [comment]
"17" is supposed to entered and then internally converted to "-f 17".

New version is out and it solved this problem.

https://github.com/mhogomchungu/media-downloader/releases/tag/3.3.0
