### ISSUE TITLE
Can only Download webm

### ISSUE THREAD

**Issue by MrOctober77** [mhogomchungu/media-downloader#305]
https://www.youtube.com/shorts/do1rp41HDSA

Tried to use the 136+140 option. But got this:

ERROR: [generic] None: '136+140' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:136+140" ) to search YouTube
[youtube] Extracting URL: https://www.youtube.com/shorts/do1rp41HDSA
[youtube] do1rp41HDSA: Downloading webpage
[youtube] do1rp41HDSA: Downloading ios player API JSON
[youtube] do1rp41HDSA: Downloading android player API JSON
[youtube] do1rp41HDSA: Downloading m3u8 information
[info] do1rp41HDSA: Downloading 1 format(s): 247+251
[download] Destination: Becky Lynch and the WWE Women on Celebrity Family Feud-do1rp41HDSA.f247.webm
[download] 2.11 MiB / 2.11 MiB (100%) at 6.37 MiB/s, ETA NA
[download] Destination: Becky Lynch and the WWE Women on Celebrity Family Feud-do1rp41HDSA.f251.webm
[download] 213.68 KiB / 213.68 KiB (100%) at 865.52 KiB/s, ETA NA
[Merger] Merging formats into "Becky Lynch and the WWE Women on Celebrity Family Feud-do1rp41HDSA.webm"
[media-downloader] Download Failed(ErrorCode=1)

No matter what download option I choose, I get the same "not a valid URL" error.

Using the portable Windows version.

**Comment by mhogomchungu** [comment]
New version is out and this problem is no longer there

https://github.com/mhogomchungu/media-downloader/releases/tag/3.3.0
