### ISSUE TITLE
 Limit yt-dlp aria2c fragments threads

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#306]
Hello, thank you for the new version ! youtube donwloads again becomes slow at 50kb/s, so I use yt-dlp aria2c again, I noticed for a youtube video of about ten minutes, I noticed during the download by checking the download folder that it there are almost 600 file fragments, if the download is interrupted for some reason and it's happened to me before, I may have to delete 600 files in my download folder, maybe limit the number of segments and threads of yt-dlp aria2c to 4 for example? I know that dividing the file into small segments helps to speed up the download but is there an option to add to limit the number of segments threads please?

**Comment by mhogomchungu** [comment]
I have looked and i do not think aria2c has an option to limit the number of fragment files it keeps on disk before merging them.
