### ISSUE TITLE
Name of downloaded file includes the youtube URL. Is it just me? How do I remove it?

### ISSUE THREAD

**Issue by bbksleazy** [mhogomchungu/media-downloader#311]
If I download a video, the file auto names with *title*+*first part of url* ![tempsnip](https://github.com/mhogomchungu/media-downloader/assets/131390099/4976e071-2f76-43aa-a983-2c0d70f4cc01)

Is this normal?

**Comment by mhogomchungu** [comment]
It is normal and those weird text are there to avoid a possibility of two media from  two different places to end up with the same file name if they share the same title.

You can remove them by following instructions from here: https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#3-how-to-make-downloaded-media-not-have-weird-text-in-the-file-name
