### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#314]
Hello, with the recent update of yt-dlp,  preset best audio doesn"t work any more, it will be great to update the FAQ with new preset  -f bestaudio -x / -f bestaudio -x --audio-format mp3 : 

"f you want to download an audio file with best audio then enter bestaudio in the option field.
If you want to download an audio file with best audio and convert it to mp3 for example then enter bestaudio -x --audio-format mp3 in the option fields.

https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions

**Comment by mhogomchungu** [comment]
The ```-f``` part is not necessary so the FAQ is correct. It did not work in some versions of Media Downloader due to a bug in Media Downloader.

**Comment by trimechee** [comment]
Great ! Thank you :) 👍
