### ISSUE TITLE
[Feature Request] Add-on to download from Imgur links

### ISSUE THREAD

**Issue by Dounial** [mhogomchungu/media-downloader#316]
I was looking for a add-on or extension to downlaod Imgur links (pics & vids) but found none so I thought I am gonna ask here for it as a feature request.

**Comment by mhogomchungu** [comment]
[Gallery-dl](https://github.com/mikf/gallery-dl) should be able to download media from imgur.

Install [gallery-dl](https://github.com/mhogomchungu/media-downloader/wiki/Extensions#4-gallery-dl) extension and checks if it works for that website or not.
