### ISSUE TITLE
Firewall

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#317]
Hello, I looked in the list of programs authorized by the Windows 10 firewall and Media-downloader is not there, I'm talking about that because it seems essential important that Media-downloader and yt-dlp  used by Media- downloader are authorized in the firewall, because I read in the page of this media player which uses yt-dlp :

Make sure that antivirus or firewall doesn't block "yt-dlp" and doesn't block executing external applications!

https://github.com/zaps166/QMPlay2#windows

**Comment by mhogomchungu** [comment]
I do not think there is anything i can do to make MD show up there and the feature will be useless if programs are allowed to add themselves to the list.

**Comment by trimechee** [comment]
We uderstand, thank you :) if we have problems, i think we should add by ourselves Media-Downloader to firewall permissions....
