### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#318]
Hello, I am almost no longer able to download YouTube videos using Media-Downloader and even using other downloaders and donwnloadr websites, i can't download youtube videos and youtube audio except when I use a VPN, I don't really know if this restriction is done by YouTube or my ISP or a yt-dlp bug....
in rare cases, when I use Media-Downloader without VPN, I can download 4 YouTube audio files with a speed limited to 50kb/s then the rest of the downloads are blocked....

and so I found a reliable and fast proxy and I would like to use it only with our beloved Media-Downloader without using it in the network settings of the os or web browser and it will be great please add proxy support for Media-downloader, because the proxy is faster than a free VPN and free VPN displays ads and can be slow and overloaded....

Thanks a lot !

**Comment by mhogomchungu** [comment]
```
--proxy URL                     Use the specified HTTP/HTTPS/SOCKS proxy. To
                                enable SOCKS proxy, specify a proper scheme,
                                e.g. socks5://user:pass@127.0.0.1:1080/.
                                Pass in an empty string (--proxy "") for
                                direct connection
```
yt-dlp has a "--proxy" option and you can set it by:-

1. Adding it in the "Download Options" text field.
2. Adding an entry in the "Engine's Default Options" tab with the entry having the "--proxy" option and then set the entry as default.

**Comment by trimechee** [comment]
Great ! Thank you ! 
so, when i add "--proxy", i should specify also the adresss and the port of the proxy ? for exemale --proxy 1.6.5.4:8080 ? can i add also proxy option as preset ? in engine's default options, i should put "--newline --ignore-config --no-playlist -o %(title).200s-%(id)s.%(ext)s --proxy 2.4.7.9:80 " ?

**Comment by trimechee** [comment]
I think i will enable proxy in the settings of the whole network of the os, so can Media-downlaoder can automatically detect and use the proxy network settings of the OS  when i add proxy to global network of the OS i mean when i add proxy to network setting of internet explorer ?

**Comment by mhogomchungu** [comment]
>so, when i add "--proxy", i should specify also the adresss and the port of the proxy ? for exemale --proxy 1.6.5.4:8080 ? 

Yes.

>can i add also proxy option as preset ?

Yes

> in engine's default options, i should put "--newline --ignore-config --no-playlist -o %(title).200s-%(id)s.%(ext)s --proxy 2.4.7.9:80 " ?

Yes

Options are endless :-)

**Comment by mhogomchungu** [comment]
> I think i will enable proxy in the settings of the whole network of the os, so can Media-downlaoder can automatically detect and use the proxy network settings of the OS when i add proxy to global network of the OS i mean when i add proxy to network setting of internet explorer ?

MD will not detect the proxy setting from the OS and pass it along to yt-dlp, try it and see if yt-dlp will automatically detect and use the setting from the OS.

**Comment by mhogomchungu** [comment]
Next version of Media Downloader will pick up proxy settings from the OS on windows.

![Screenshot_20230924_233801](https://github.com/mhogomchungu/media-downloader/assets/3496115/76642aee-50d8-49ba-87f3-664b3ba15dfa)

**Comment by trimechee** [comment]
Great ! Awesome ! Thank you so much Mr @mhogomchungu ! 💯 🥇 
and I just discovered an interesting thing, I thought that when youtube download in Media-Downloader  freezes and there is no indication about the download progress and speed, I thought there is no download but I notice that even if the youtube download is frozen, I see the file  in the download folder, I'm going to do other tests but that's good news, it seems we no longer need a vpn or proxy to download from youtube....

**Comment by trimechee** [comment]
Oups i made some tests, only one video youtube id downloaded and then, the download freez and i have message erro time out....it seems it become impossible to donwload videos from youtube without proxy or vpn, i don't know if this is worldwide problem ou my ip adress is blackkisted....

**Comment by mhogomchungu** [comment]
New version is out and a window to configure proxy settings looks like below.

https://github.com/mhogomchungu/media-downloader/releases/tag/3.4.0

![Screenshot_20231001_113823](https://github.com/mhogomchungu/media-downloader/assets/3496115/76f316b9-b88c-48b4-a78c-46fc2fe5fa28)

**Comment by trimechee** [comment]
Awesome ! thank you so much for this wonderful important feature :) 🥇 💯 Media-Downloader stills the best of the best and number one of the downloaders !
