### ISSUE TITLE
External applicaiton launcher argument not working

### ISSUE THREAD

**Issue by cinetube** [mhogomchungu/media-downloader#321]
-u [HREF] -a - This argument of external application launcher is not working after update to version 3.4

**Comment by mhogomchungu** [comment]
Its working fine here, are you on linux or windows?

**Comment by mhogomchungu** [comment]
Can you be more specific:-

```-u [HREF]```: This options adds a URL to the application and it works here.
```-a```: This option autodownloads added URL and this one does not work and it looks like it was broken a long time ago.

**Comment by mhogomchungu** [comment]
The ```-a``` now works so if your issue was with this option then the problem is solved.
