### ISSUE TITLE
Full dark mode

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#328]
Hello, I enabled dark mode in our beloved Media-Downloader, and I notice the top bar remains white despite it being the dark mode theme, we hope that Media-Downloader will adopt full dark mode even in the top bar, thank you very much !
![Capture](https://github.com/mhogomchungu/media-downloader/assets/76402212/683f1f85-7a98-4df1-acbc-c22761ceb8b7)

**Comment by mhogomchungu** [comment]
Done

![Screenshot_20231027_191330](https://github.com/mhogomchungu/media-downloader/assets/3496115/0abf3d6a-be8f-4be5-93a1-e9b285843f57)

**Comment by trimechee** [comment]
Sensational ! Thank you so much Mr @mhogomchungu :) 🥇
