### ISSUE TITLE
Mysterious enigmatic disappearance of files downloaded by M-D

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#333]
For months, I have been downloading files using the worstaudio preset and recently -f worstaudio -x, and the files are downloading normally but some files after downloading mysteriously disappear enigmatically inexplicably from the download folder, this happens rarely which is why I didn't open an issue but yesterday I wanted to listen to a show and I see Media-downloader downloading it and finishing the download then I can no longer find the file downloaded via the preset -f worstaudio -x, I even changed it the download folder, I tried with another 3D downloader youtube downloader and I was able to successfully download with the worst audio quality but the downloaded file has the opus format which would explain the bug, apparently Media donwloader has a problem with opus files and automatically deletes them:

here is the video that I tested with preset  -f worstaudio -x
https://www.youtube.com/watch?v=G_H82PI-_DU

**Comment by trimechee** [comment]
in normal use, M-D uses the m4a format for youtube dash audio files, but when it comes to opus audio files, this file deletion bug manifests itself

**Comment by mhogomchungu** [comment]
Media Downloader does not touch downloaded media in any shape or form so it is not possible for this problem to come from Media Downloader.

Can you try again to download the media and when it disappears again, post the contents of the basic downloader tab.

**Comment by trimechee** [comment]
The download succeded but i can't find the downloaded file indownload folder, i will try with another download folder : "[media-downloader] cmd: "C:/Users/Asus/AppData/Roaming/media-downloader/bin/yt-dlp.exe" "--match-filter" "!playlist" "--break-on-reject" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-f" "worstaudio" "-x" "--compat-options" "2022" "--progress-template" "download:[download] {"filename":"%(progress.filename)s","downloaded_bytes":"%(progress.downloaded_bytes)s","ETA":"%(progress.eta)s","total_bytes_estimate":"%(progress.total_bytes_estimate)s","total_bytes":"%(progress.total_bytes)s","speed":"%(progress.speed)s","fragment_index":"%(progress.fragment_index)s","fragment_count":"%(progress.fragment_count)s"}" "https://www.youtube.com/watch?v=G_H82PI-_DU"
[youtube] Extracting URL: https://www.youtube.com/watch?v=G_H82PI-_DU
[youtube] G_H82PI-_DU: Downloading webpage
[youtube] G_H82PI-_DU: Downloading ios player API JSON
[media-downloader] Download Cancelled
[media-downloader] cmd: "C:/Users/Asus/AppData/Roaming/media-downloader/bin/yt-dlp.exe" "--match-filter" "!playlist" "--break-on-reject" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-f" "worstaudio" "-x" "--compat-options" "2022" "--progress-template" "download:[download] {"filename":"%(progress.filename)s","downloaded_bytes":"%(progress.downloaded_bytes)s","ETA":"%(progress.eta)s","total_bytes_estimate":"%(progress.total_bytes_estimate)s","total_bytes":"%(progress.total_bytes)s","speed":"%(progress.speed)s","fragment_index":"%(progress.fragment_index)s","fragment_count":"%(progress.fragment_count)s"}" "https://www.youtube.com/watch?v=G_H82PI-_DU"
[youtube] Extracting URL: https://www.youtube.com/watch?v=G_H82PI-_DU
[youtube] G_H82PI-_DU: Downloading webpage
[youtube] G_H82PI-_DU: Downloading ios player API JSON
[youtube] G_H82PI-_DU: Downloading android player API JSON
[youtube] G_H82PI-_DU: Downloading m3u8 information
[info] G_H82PI-_DU: Downloading 1 format(s): 233
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 328
[download] Destination:     -G_H82PI-_DU.mp4
[download] 10,41 Mio / 10,41 Mio (100%) at 112,91 Kio/s, ETA NA
[ExtractAudio] Destination:     -G_H82PI-_DU.m4a
[media-downloader] Download Completed Successfully
[media-downloader] cmd: "C:/Users/Asus/AppData/Roaming/media-downloader/bin/yt-dlp.exe" "--match-filter" "!playlist" "--break-on-reject" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-f" "worstaudio" "-x" "--compat-options" "2022" "--progress-template" "download:[download] {"filename":"%(progress.filename)s","downloaded_bytes":"%(progress.downloaded_bytes)s","ETA":"%(progress.eta)s","total_bytes_estimate":"%(progress.total_bytes_estimate)s","total_bytes":"%(progress.total_bytes)s","speed":"%(progress.speed)s","fragment_index":"%(progress.fragment_index)s","fragment_count":"%(progress.fragment_count)s"}" "https://www.youtube.com/watch?v=G_H82PI-_DU"
[youtube] Extracting URL: https://www.youtube.com/watch?v=G_H82PI-_DU
[youtube] G_H82PI-_DU: Downloading webpage
[youtube] G_H82PI-_DU: Downloading ios player API JSON
[youtube] G_H82PI-_DU: Downloading android player API JSON
[youtube] G_H82PI-_DU: Downloading m3u8 information
[info] G_H82PI-_DU: Downloading 1 format(s): 233
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 328
[download] Destination:     -G_H82PI-_DU.mp4
[download] 10,41 Mio / 10,41 Mio (100%) at 134,39 Kio/s, ETA NA
[ExtractAudio] Destination:     -G_H82PI-_DU.m4a
[media-downloader] Download Completed Successfully"

**Comment by trimechee** [comment]
I tried to download by choosing another download folder, I find the downloaded file again but I notice it has an m4a extension, when the problem occurred, and when I tried with 3Dyoutubedownloader choosing the worst quality audio, the downloaded file had the opus extension....maybe yutube added other audio formats to this video which solved the problem.....well thank you for your help, I am closing the issue :)



"[media-downloader] cmd: "C:/Users/Asus/AppData/Roaming/media-downloader/bin/yt-dlp.exe" "--match-filter" "!playlist" "--break-on-reject" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-f" "worstaudio" "-x" "--compat-options" "2022" "--progress-template" "download:[download] {"filename":"%(progress.filename)s","downloaded_bytes":"%(progress.downloaded_bytes)s","ETA":"%(progress.eta)s","total_bytes_estimate":"%(progress.total_bytes_estimate)s","total_bytes":"%(progress.total_bytes)s","speed":"%(progress.speed)s","fragment_index":"%(progress.fragment_index)s","fragment_count":"%(progress.fragment_count)s"}" "https://www.youtube.com/watch?v=G_H82PI-_DU"
[youtube] Extracting URL: https://www.youtube.com/watch?v=G_H82PI-_DU
[youtube] G_H82PI-_DU: Downloading webpage
[youtube] G_H82PI-_DU: Downloading ios player API JSON
[youtube] G_H82PI-_DU: Downloading android player API JSON
[youtube] G_H82PI-_DU: Downloading m3u8 information
[info] G_H82PI-_DU: Downloading 1 format(s): 233
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 328
[download] Destination:     -G_H82PI-_DU.mp4
[download] 10,41 Mio / 10,41 Mio (100%) at 140,02 Kio/s, ETA NA
[ExtractAudio] Destination:     -G_H82PI-_DU.m4a
[media-downloader] Download Completed Successfully"
