### ISSUE TITLE
HTTP ERROR 404

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#335]
Hello, i try to download this video with preset -f worstaudio -x : 

https://www.youtube.com/watch?v=UDrjAyfSF_E

but MD says to me "unable to donwload video data, HTTP ERROR 404 not found"

**Comment by mhogomchungu** [comment]
I think this is a problem with youtube giving download entries for options that do not exist and you can work around the issue by downloading best audio or manually choosing other lower quality audio only options that work(i tried two options and they both failed)
