### ISSUE TITLE
FFmpeg version

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#336]
Hello, thank you so much for this nw amazing version ! 🥇 

I just updated to the new version via native auto updater of Media-Downloader, and i have these message in startup : "[media-downloader] Checking installed version of ffmpeg
[media-downloader] Found version: n5.0-5-g426b7f48d9-20220308"

but i see in changelog of our beloved M-D : "Changelog:-
      [Windows]
      - Update bundled version of ffmpeg to version 6.0."

 so the native auto updater of M-D can't update ffmpeg to version 6 ?

**Comment by mhogomchungu** [comment]
I have updated changelog and added the following entry:
```
All Windows users are required to manually update to at least 
this version. There are some incompatible changes and updating 
Media Downloader from within Media Downloader will not apply 
those changes.The incompatible changes will make it possible in
the future to seamlessly update ffmpeg and Qt to version 6.
```
