### ISSUE TITLE
Pure Black theme instead of dark gray mode

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#338]
Hello, Dark mode allows you to reduce blue light which can tire our eyes at night, save battery power... and even if the majority of sites and apps offer a dark mode, I noticed it's not really pure black theme but it's more dark gray theme, I like the pure full black mode theme which looks like the high contrast theme, so in the addon extension for web browser "dark reader", I even modified the contrast option for put it at maximum in order to have a real black theme on Twitter and many other sites.....

so we would like please for more visual comfort a pure black theme for our beloved Media-Downloader because the dark theme used is not a pure black mode but it's a dark gray theme, the black mode is only present in the top bar which is truly black color....

  Thanks a lot !

**Comment by mhogomchungu** [comment]
1. Go to ```data/themes``` folder located inside ```App Data Path```(this path is displayed in the UI in basic downloader tab on startup).
2. Make a copy of the "Dark.json" file with your copy having a word "dark" in it.
3. Modify your copy to have UI with colors you want and modify it by changing the entry for "darkColor" to "0,0,0,0".
4. Start MD, go to "configure->general options" and the "dark theme" option should have an entry for your copy, select it and restart MD.

**Comment by mhogomchungu** [comment]
I am glad the UI is the you prefer it to be. It is not possible to give everybody a UI with colors they prefer and that is why i specifically make it possible to change the colors.
