### ISSUE TITLE
FFprobe error codec

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#339]
Hello, it is impossible to download this video with preset " -f bestaudio -x"  : 

https://www.youtube.com/watch?v=POHip_aQNm8

M-D says to me : "Error postprocessing ,warning unable to obtain file audio codec with ffprobe"

**Comment by mhogomchungu** [comment]
I can not reproduce this

![Screenshot_20231103_232746](https://github.com/mhogomchungu/media-downloader/assets/3496115/699907ff-d75b-4140-8175-9e8a87b308a7)
![Screenshot_20231103_233213](https://github.com/mhogomchungu/media-downloader/assets/3496115/30460cbd-d97e-4029-9606-1969613aab69)

**Comment by mhogomchungu** [comment]
Downloder a portable version of an earlier version of MD that use version 5 of ffmpeg and test it fails the same or not in that version.
