### ISSUE TITLE
[Feature Requests] Features asked through email conversation

### ISSUE THREAD

**Issue by mhogomchungu** [mhogomchungu/media-downloader#341]
1: Include yt-dlp in the download. Just in-case anything happens to the github page, it would be nice to have a version included as a backup.

2: Allow presets to be imported/exported within the gui, rather than manually having to navigate to AppData\Roaming\media-downloader\data.

3: Allow multiple playlists to be added to the 'Playlist Downloader' tab.

**Comment by richardstevenhack** [comment]
With regard to 2 above, I was on a Windows machine the other day (I usually am on Linux) and wanted to set the Default Options to incorporate some adjustment of the output file name (to remove the 5id%.) 

I found that if I either set up a new Default Download Options as provided for using the GUI OR if I directly edited the file in AppData in Notepad++, in both cases Media Downloader (or probably python) complained about not recognizing the "%" symbol unless I double-quoted it like "%%". In that case, it just output "%(title).%(ext)" and not the actual video title and extension. I don't have the Windows machine up at the moment so I can't show you the error message just now.

All that to say that it would be nice to have a way to directly edit the Default Download Options and change them to suit the user - and presumably a way to back them up in case the user screws them up which it is easy to do if one isn't totally familiar with the half million yt-dlp parameters.  :-)

**Comment by mhogomchungu** [comment]
Responding to number 3. It is possible to add multiple urls to the playlist downloader tab by separating them with either a new line character or a space character. Space character was required before version 4.1.0 and version 4.1.0 accepts both.

**Comment by mhogomchungu** [comment]
Wish number one from the original post is now implemented and will be available with the next version.

When the application starts, it prints in the basic downloader tab the location of the folder where all settings are stored to make it easy to go there and manually manipulate them like restoring them, backing them up and manually editing them.

The UI also has buttons to reset most options to their defaults.

@richardstevenhack, it is possible to edit download options from within the UI.

Closing this one as complete.
