### ISSUE TITLE
"Show media options" screen is grayed out

### ISSUE THREAD

**Issue by zinalili** [mhogomchungu/media-downloader#343]
In Batchdownloader: if Video1 is being downloaded, I can't select format for Video2: the list of formats is grayed out and I can't go back. to the list of videos until the video in progress is finished.

**Comment by mhogomchungu** [comment]
You want to "Options" button is grayed out when a download is in progress?

**Comment by zinalili** [comment]
![01](https://github.com/mhogomchungu/media-downloader/assets/13087157/7247434e-596d-4896-af37-9f26dc416490)
![02](https://github.com/mhogomchungu/media-downloader/assets/13087157/e3e63279-d11c-42db-ac67-38b602df6d4c)
![03](https://github.com/mhogomchungu/media-downloader/assets/13087157/1d992092-e39f-4666-bc65-91dd2c601d54)
Add a few files to the list in Batch Downloader.
Start downloading videos and click "Show media options" on one of the other videos.
You get the screen of format selection but everything is grayed out and buttons as well. You can't go back to the list of videos.

**Comment by zinalili** [comment]
> You want to "Options" button is grayed out when a download is in progress?

that'll work

**Comment by mhogomchungu** [comment]
Just checked and this is already fixed but i do not remember when.

When downloading, the cancel button of "Show media options" UI element remain active so its now possible to close the UI element.
