### ISSUE TITLE
Aria2c update

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#345]
Hello, I was very stupid to not to have used yt-dlp aria2c for months.... and I wasted my time looking for and activating proxies and using vpns to bypass the throttling because youtube limits the download speed at 45kb/s, but now I use yt-dlp aria2c as my main download engine and I see that aria2c recently received an update and we hope our beloved will use the new version of aria2c soon, thank you very much :)

**Comment by mhogomchungu** [comment]
Thanks for the info.

New version of aria2c will be available with the new version of MD.

**Comment by trimechee** [comment]
Awesome ! Thank you so much ! Media Downloader with its rare unique features and options and ease of use and with its generous developer who helps and advises us is increasingly becoming the best downloader in the history of humanity ! 

Bravoo and well done and thank you so much et we are very grateful Mr @mhogomchungu :) 🥇 💯
