### ISSUE TITLE
Downloading from vod.tvp.pl gives "Failed to download MPD manifest: timed out" error

### ISSUE THREAD

**Issue by AuroraMartell** [mhogomchungu/media-downloader#346]
Whenever I try to download content from [TVP VOD](https://vod.tvp.pl/), I get the following error.

`[tvp:vod] Extracting URL: https://vod.tvp.pl/seriale,18/korona-krolow-jagiellonowie-odcinki,292227/odcinek-80,S01E80,787552
[tvp:vod] 787552: Downloading JSON metadata
[tvp:vod] 787552: Downloading JSON metadata
[tvp:vod] 787552: Downloading m3u8 information
WARNING: [tvp:vod] Failed to download m3u8 information: timed out
[tvp:vod] 787552: Downloading MPD manifest
WARNING: [tvp:vod] Failed to download MPD manifest: timed out
ERROR: [tvp:vod] 787552: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[media-downloader] Download Failed(ErrorCode=1)`

 I've checked that I can download the same content using other tools. 

Could someone look into this?

**Comment by mhogomchungu** [comment]
Worked fine here
```
[media-downloader] cmd: "/home/ink/.local/share/media-downloader/bin/yt-dlp" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-f" "bestvideo[ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best[ext=mp4]/best" "--compat-options" "2022" "--progress-template" "download:[download] {"filename":"%(progress.filename)s","downloaded_bytes":"%(progress.downloaded_bytes)s","ETA":"%(progress.eta)s","total_bytes_estimate":"%(progress.total_bytes_estimate)s","total_bytes":"%(progress.total_bytes)s","speed":"%(progress.speed)s","fragment_index":"%(progress.fragment_index)s","fragment_count":"%(progress.fragment_count)s"}" "https://vod.tvp.pl/seriale,18/korona-krolow-jagiellonowie-odcinki,292227/odcinek-80,S01E80,787552"
[tvp:vod] Extracting URL: https://vod.tvp.pl/seriale,18/korona-krolow-jagiellonowie-odcinki,292227/odcinek-80,S01E80,787552
[tvp:vod] 787552: Downloading JSON metadata
[tvp:vod] 787552: Downloading JSON metadata
[tvp:vod] 787552: Downloading m3u8 information
[tvp:vod] 787552: Downloading MPD manifest
[info] 787552: Downloading 1 format(s): 5397+f8-a1-x3
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 372
[download] Destination: odc. 80 – Królewskie tęsknoty, ukryte skarby, panieńskie łzy-787552.f5397.mp4
[download] Got error: [Errno -3] Temporary failure in name resolution. Retrying (1/10)...
[download] 1.32 MiB / ~2.79 GiB (0.05%) at 225.00 KiB/s, ETA 00:00
[media-downloader] Download Cancelled
```

**Comment by AuroraMartell** [comment]
> Worked fine here
> 
> ```
> [media-downloader] cmd: "/home/ink/.local/share/media-downloader/bin/yt-dlp" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-f" "bestvideo[ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best[ext=mp4]/best" "--compat-options" "2022" "--progress-template" "download:[download] {"filename":"%(progress.filename)s","downloaded_bytes":"%(progress.downloaded_bytes)s","ETA":"%(progress.eta)s","total_bytes_estimate":"%(progress.total_bytes_estimate)s","total_bytes":"%(progress.total_bytes)s","speed":"%(progress.speed)s","fragment_index":"%(progress.fragment_index)s","fragment_count":"%(progress.fragment_count)s"}" "https://vod.tvp.pl/seriale,18/korona-krolow-jagiellonowie-odcinki,292227/odcinek-80,S01E80,787552"
> [tvp:vod] Extracting URL: https://vod.tvp.pl/seriale,18/korona-krolow-jagiellonowie-odcinki,292227/odcinek-80,S01E80,787552
> [tvp:vod] 787552: Downloading JSON metadata
> [tvp:vod] 787552: Downloading JSON metadata
> [tvp:vod] 787552: Downloading m3u8 information
> [tvp:vod] 787552: Downloading MPD manifest
> [info] 787552: Downloading 1 format(s): 5397+f8-a1-x3
> [hlsnative] Downloading m3u8 manifest
> [hlsnative] Total fragments: 372
> [download] Destination: odc. 80 – Królewskie tęsknoty, ukryte skarby, panieńskie łzy-787552.f5397.mp4
> [download] Got error: [Errno -3] Temporary failure in name resolution. Retrying (1/10)...
> [download] 1.32 MiB / ~2.79 GiB (0.05%) at 225.00 KiB/s, ETA 00:00
> [media-downloader] Download Cancelled
> ```

I'll try again, thanks for checking.

**Comment by mhogomchungu** [comment]
Make sure you are first using yt-dlp version "2023.11.16" before trying again.

Closing this one as the problem appears to be local to you.
