### ISSUE TITLE
Lupdate - Please don't use -no-ui-lines

### ISSUE THREAD

**Issue by bovirus** [mhogomchungu/media-downloader#347]
@mhogomchungu 

Please when you use lupdate to update language file to include in command line

-no-ui-lines

to avoid to registre inmn amster language file the changes in ui liens.

This avoid to change the contents of master english langaueg not for rweal contents but just only for UI references.

If you use a tool to check changes in english language file it report some changes when really teh strings are not changed.

Thanks.

**Comment by mhogomchungu** [comment]
Ok, will do that.
