### ISSUE TITLE
Will not update

### ISSUE THREAD

**Issue by disorganised-mess** [mhogomchungu/media-downloader#349]
I've got the repo added to Kubuntu 22.04 and it will not update to version 4.0.0-1 giving error about hashes. It has been two days for me. Has anyone else seen any issue with this?
![Screenshot_20231128_172026](https://github.com/mhogomchungu/media-downloader/assets/15573579/46de5f0b-8bd4-4df8-8f97-24f830e682e5)

**Comment by mhogomchungu** [comment]
I have made a new release and try again.

I rebuild version 4.0.0 to make it work for debian 8 and maybe the rebuild caused the issue.

**Comment by disorganised-mess** [comment]
That fixed it. Thanks for addressing the issue.
