### ISSUE TITLE
[Feature request] Please add support for yt-dlp

### ISSUE THREAD

**Issue by darkshram** [mhogomchungu/media-downloader#35]
[yt-dlp](https://github.com/yt-dlp/yt-dlp) is an actively maintained fork of youtube-dl with additional features and [more video platforms](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md). It has the same dependencies as youtube-dl plus aria2, python3-mutagen and python3-pycryptodom. Has similar command line syntax with [some changes](https://github.com/yt-dlp/yt-dlp#differences-in-default-behavior).

**Comment by mhogomchungu** [comment]
It is already supported and you can add it by installing its extension[1]. Instructions on how to install extensions are here[2].

[1] https://github.com/mhogomchungu/media-downloader/wiki/Extensions#2-yt-dlp

[2] https://github.com/mhogomchungu/media-downloader/wiki/Extensions#how-to-install-extensions
