### ISSUE TITLE
[REQUEST] Add ordering and filter feature in columns

### ISSUE THREAD

**Issue by zhenyaetoya** [mhogomchungu/media-downloader#351]
Hi! 

Very nice to see ordering and filter feature.
![media-downloader_LC2FQVeQm](https://github.com/mhogomchungu/media-downloader/assets/105151341/46885b38-f48f-4a2e-879f-7f57a8a87a60)

Like in Windows explorer, for example.
![image](https://github.com/mhogomchungu/media-downloader/assets/105151341/d904134f-33e4-4c81-bee9-ae6bbb5bec23)

**Comment by zhenyaetoya** [comment]
One more example
![image](https://github.com/mhogomchungu/media-downloader/assets/105151341/12eb9fc7-6d7d-46f3-95d1-3aa3c7a227e7)

**Comment by mhogomchungu** [comment]
This is done.

The first column can do ordering and the second two can do filtering.

![Screenshot_20231214_095737](https://github.com/mhogomchungu/media-downloader/assets/3496115/18b7cbb2-972c-490d-93ac-24e675dd63ac)
![Screenshot_20231214_095801](https://github.com/mhogomchungu/media-downloader/assets/3496115/92cbdcb9-96e2-418d-98bb-dac364b94d50)
![Screenshot_20231214_095825](https://github.com/mhogomchungu/media-downloader/assets/3496115/a777c3bb-5ada-43ba-b0a6-644416779b5a)
