### ISSUE TITLE
[REQUEST] Add active link to project website into "About" section

### ISSUE THREAD

**Issue by zhenyaetoya** [mhogomchungu/media-downloader#352]
Hello.

Add active link to project website into "About" section.

![image](https://github.com/mhogomchungu/media-downloader/assets/105151341/6414b612-d002-464f-8f95-906c8d3b19ca)

**Comment by mhogomchungu** [comment]
Done

![Screenshot_20231216_120113](https://github.com/mhogomchungu/media-downloader/assets/3496115/324d3078-9c25-4327-8fc9-9915353859db)
