### ISSUE TITLE
GPG error with the repository mhogomchungu (media-downloader installation repository)

### ISSUE THREAD

**Issue by BENDER35** [mhogomchungu/media-downloader#353]
Hello, good evening, I am commenting on my problem, I am currently using Ubuntu Mate 22.04, so the problem comes when using the repo update command (I have recently tried the media-downloader), when using apt it gives me a key authentication error , I have passed an apt-key list and the GPG keys that I have (both the ones that mhogomchungu mentions in its media-downloader update and the key that I added) to install media-downloader work correctly, I have passed the second command to update the key , I have used the command to update the wine key but changing it to the repo key of this program and I have also searched for the key in the Ubuntu keyserver and in another and nothing, I cannot update the repo, could you help me solve the problem? @mhogomchungu , if you have changed the repo key, can you tell me what key I put in the apt-key, please?

step screenshot (my main language is Spanish)

![Captura de pantalla -2023-12-15 19-35-14](https://github.com/mhogomchungu/media-downloader/assets/62604047/a3b43152-dd84-4ace-9dfc-6b0f79da8247)

greetings

**Comment by BarbzYHOOL** [comment]
I also have this but I haven"' updated my distrib, so I didn't know if it was related to me or not

**Comment by mhogomchungu** [comment]
Instructions for setting up your system for using media-downloader from suse build system are below:-
```
echo 'deb http://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/home:obs_mhogomchungu.list
curl -fsSL https://download.opensuse.org/repositories/home:obs_mhogomchungu/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_obs_mhogomchungu.gpg > /dev/null
sudo apt update
sudo apt install media-downloader
```

Did you follow all of them?

**Comment by BENDER35** [comment]
> Instructions for setting up your system for using media-downloader from suse build system are below:-
> 
> ```
> echo 'deb http://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/home:obs_mhogomchungu.list
> curl -fsSL https://download.opensuse.org/repositories/home:obs_mhogomchungu/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_obs_mhogomchungu.gpg > /dev/null
> sudo apt update
> sudo apt install media-downloader
> ```
> 
> Did you follow all of them?

Hello mhogomchungu

I have already solved the problem that tells me that the key was expired, it turns out that I had two files in the sources.list.d, one that had the name of your program (media downloader) and another with the name of your repo, that is , which had the duplicate repo and that is what was giving me the error, what I did was comment on the duplicate file (put a hash on it) to deactivate the duplicate repo, then later I did the command to delete the copies and then from the file manager repos in a graphical environment, I activated the repo and clicking on reload and then after updating the repos solved the problem.

Greetings

**Comment by BarbzYHOOL** [comment]
this was the solution `curl -fsSL https://download.opensuse.org/repositories/home:obs_mhogomchungu/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_obs_mhogomchungu.gpg > /dev/null`

**Comment by griha41** [comment]
> this was the solution `curl -fsSL https://download.opensuse.org/repositories/home:obs_mhogomchungu/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_obs_mhogomchungu.gpg > /dev/null`

I'm sorry for disturbing, but I'm curious which version of oS do you using? I'm on 15.5 Leap and no way to run the med dwnldr. Outdated version of Python on the OS (with std reps) if update from 3rd party reps - got huge amount issues with OS.
But I was able to run it through the Wine (the windows version)...

**Comment by BarbzYHOOL** [comment]
ubuntu 22.04
