### ISSUE TITLE
Video codec priority for playlist

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#354]
Hello, i find this issue in another downloader github page..... i copy past the issue, may be it can be added to Media-downloader : 

" With the rise of AV1 encoded videos on youtube i think there should be a "video codec priority" option for playlist download, this will help device that can't decode hardware av1 (most phones/tablets/non-recent gpu|igpu).

How this option should look like in interface: https://codepen.io/dsenneff/pen/JjNPJer/b2bc0298b73dd5605f45828df3b61dd4 "

**Comment by mhogomchungu** [comment]
Default behavior for youtube.com is to prefer avc video codec and users are expected to add their own preset if they want another codec to get first priority.

**Comment by trimechee** [comment]
Instructive ! Thank you so much :) 👍
