### ISSUE TITLE
Doesn't download m3u8 links from skool or luna.loom.com

### ISSUE THREAD

**Issue by wmortume** [mhogomchungu/media-downloader#357]
When I try to download a video from the [skool](https://www.skool.com) website through m3u8 links like this below I get a 403 forbidden error. I'm suspecting the `luna.loom.com` domain blocks links from being downloaded and the video can only be accessed with authentication hence why I'm using m3u8. Is there a way I can circumvent this issue (extensions, cookies, etc.)?

https://luna.loom.com/id/fb582496175e4dbfbf1ffee412b7d74c/rev/6c47c9e95bdf8af0f7f6e4e04b52626b0f6f71dd969665b26fcd09d068c804fd9/resource/hls/mediaplaylist-video-bitrate3200.m3u8

![image](https://github.com/mhogomchungu/media-downloader/assets/36937310/37bd1604-85aa-491d-ae84-a3a215dcea83)

**Comment by mhogomchungu** [comment]
What web browser are you using and you have logged in to the skool website?

In the download options text field, add below options where XYZ is a name of a web browser you are using
```
--cookies-from-browser XYZ
```
Supported web browsers are:- 
```
brave
chrome
chromium
edge
firefox
opera
safari
vivaldi
```

**Comment by wmortume** [comment]
@mhogomchungu I'm using chrome and yes I'm logged in on the skool website. Tried the m3u8 link with the cookies and it's giving me permission denied for the cookies folder. Is there something I'm missing and should I use the video URL instead of m3u8 (both give same error)?

![image](https://github.com/mhogomchungu/media-downloader/assets/36937310/03a3fbd8-23f7-4a2e-8b2d-bf3179e28d7b)

**Comment by mhogomchungu** [comment]
This appears to be a known problem and a possible workaround is to close chrome before trying to download.

More info [here.]( https://www.reddit.com/r/youtubedl/comments/144zy9o/cookies_problem/)

**Comment by wmortume** [comment]
@mhogomchungu I'm still getting the forbidden error but the error description is different. I don't think m38u links are still valid after closing chrome since the link gets changed when refreshing the video. 
![image](https://github.com/mhogomchungu/media-downloader/assets/36937310/4b4f763d-4b5c-426a-9b52-378a60b8951e)

I also tried the video direct link and it's giving me unsupported url error.
![image](https://github.com/mhogomchungu/media-downloader/assets/36937310/d668cc00-28b6-41df-a1de-788805f501b3)

**Comment by mhogomchungu** [comment]
"Unsupported URL" means yt-dlp does not know how to extract media from that website.

This is a problem for yt-dlp and you should open a request with yt-dlp and ask them to support this website.
