### ISSUE TITLE
Credential cookies error fail in facebook 

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#358]
Hello, I tried 2 days ago to download this video from facebook 

https://www.facebook.com/watch/live/?ref=watch_permalink&v=271439382228228

and I even added the preset " --cookies-from-browser " because the error message tells me to add this option but I cannot download this Facebook video of a recorded live, the message from Media-downloader from two days ago told me to enter my credential username password cookies.... I even tried to download with online download websites but it's the same thing, I couldn't download this video.....

I am now trying to download again because it may be a temporary bug but I have this new error error message :

" [media-downloader] cmd: "C:/Users/Asus/AppData/Roaming/media-downloader/bin/yt-dlp.exe" "--match-filter" "!playlist" "--break-on- reject" "--downloader" "aria2c" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "- -newline" "--output-na-placeholder" "NA" "-f" "worstaudio" "-x" "--compat-options" "2022" "https://www.facebook.com/watch/live /?ref=watch_permalink&v=271439382228228"
[facebook] Extracting URL: https://www.facebook.com/watch/live/?ref=watch_permalink&v=271439382228228
[facebook] 271439382228228: Downloading webpage
[facebook] 271439382228228: Downloading webpage
ERROR: [facebook] 271439382228228: Cannot parse data; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q=, filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U
[media-downloader] Download Failed(ErrorCode=1) "

**Comment by mhogomchungu** [comment]
The link gives me an error saying the content is not available. The error message says the following
```
This content isn't available right now
When this happens, it's usually because the owner only shared it with
a small group of people, changed who can see it or it's been deleted.
```

**Comment by trimechee** [comment]
Ahh, I was able to watch this Facebook video but I was not able to download it.....perhaps the video is geoblocked....it's a radio intended for tunisians in france, perhaps the content is only available in France and Tunisia using the Psiphon vpn....
in any case thank you for your help :) the message from Media-Downloader tells me to report this problem to yt-dlp.....so maybe there is a bug....I will try to close the browser when I use the option --cookies-from-browser...

**Comment by trimechee** [comment]
@mhogomchungu Hello, i tried with another new video of this radio , 

https://www.facebook.com/radioawledna/videos/6795550527230026/

i have this message , should i put my facebook username and password in Media-Downloader ? 


" [media-downloader] cmd: "C:/Users/Asus/AppData/Roaming/media-downloader/bin/yt-dlp.exe" "--match-filter" "!playlist" "--break-on-reject" "--downloader" "aria2c" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--newline" "--output-na-placeholder" "NA" "-f" "worstaudio" "-x" "--compat-options" "2022" "https://fb.watch/pbJdYczERO/"
[generic] Extracting URL: https://fb.watch/pbJdYczERO/
[generic] pbJdYczERO: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/watch/?v=6795550527230026&ref=sharing
[facebook] Extracting URL: https://www.facebook.com/watch/?v=6795550527230026&ref=sharing
[facebook] 6795550527230026: Downloading webpage
ERROR: [facebook] 6795550527230026: This video is only available for registered users. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (facebook) to provide account credentials
[media-downloader] Download Failed(ErrorCode=1) "

**Comment by mhogomchungu** [comment]
What web browser are you using?

Add option "--cookies-from-browser ABC" where "ABC" is a browser name you are using and is logged in to facebook.

If you are using chrome web browser then close it first before trying.

Also, make sure you are using the latest version of yt-dlp.

**Comment by trimechee** [comment]
Hello, before doing this, i uninstall M-D and reboot and delete all temporary files of M-D, then i install the new version and i close the browser and.....it works ! i can download this facebook videos ! Thank you many times for the new version :) 🥇

**Comment by drimisssss** [comment]
Hello @mhogomchungu ,  may be these commands can help to fix some problems and may be it is good idea to add them to documentation ou the extension part explanation : 

--disable-features=LockProfileCookieDatabase


Network Service Sandbox 
https://docs.google.com/document/d/1Bk3Z8CUQucd8FP6ISKkT3Q9YYuP43574VIO_kyAISBU/view

--disable-features=NetworkServiceSandbox - will disable the sandbox (default at the moment)

--enable-features=NetworkServiceCodeIntegrity  - will enable code integrity.
