### ISSUE TITLE
why when starting download with options '--newline --ignore-config --no-playlist -o %(channel)s/%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s' media-downloader closes itself automatically

### ISSUE THREAD

**Issue by candrapersada** [mhogomchungu/media-downloader#360]
why when starting download with options 
```
--newline --ignore-config --no-playlist -o %(channel)s/%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s
```
media-downloader closes itself automatically

- windows 10
- media-downloader 4.2.0
- yt-dlp 2023.12.30

**Comment by mhogomchungu** [comment]
1. I can not reproduce.
2. This option make sense only with playlist downloader tab, are you using it there?
3. You have a space character in your -o option, either remove the space character or put the options between quotation characters(").

**Comment by candrapersada** [comment]
> * This option make sense only with playlist downloader tab, are you using it there?

yes



> 3\. You have a space character in your -o option, either remove the space character or put the options between quotation characters(").

I've tried it but it's still the same
`--newline --ignore-config --no-playlist -o %(channel)s/%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s
`
`--newline --ignore-config --no-playlist -o "%(channel)s/%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s"`

**Comment by mhogomchungu** [comment]
Can you give me a URL i can use to test, i can not reproduce the problem.

**Comment by candrapersada** [comment]
https://www.youtube.com/playlist?list=PLXK1CM0vzYKHRV7ceJEtTT8ThpcA9eNhY

**Comment by mhogomchungu** [comment]
Fixed and you can use a version with a fix by downloading the executable from below link

https://github.com/mhogomchungu/media-downloader/releases/download/4.2.0/MediaDownloader-4.2.0-01-09-2024-git.zip

**Comment by mhogomchungu** [comment]
New version is out and it solved this problem

https://github.com/mhogomchungu/media-downloader/releases/tag/4.3.0
