### ISSUE TITLE
Delete temprary files of cancelled video

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#361]
Hello, this movie  has a size of about 1Gb

https://my.mail.ru/mail/vfstream/video/_myvideo/1.html?from=videoplayer

sometimes we cancel the download but the temporary file remains even after restarting M-D and even though the file no longer appears in the M-D list.

Yes we can imagine that M-D keeps the part of the downloaded file to resume the download in the event of an involuntary internet outage but in this case we voluntarily canceled the download and the movie link no longer exists in M-D so M-D should delete the temporary file downloaded, thank you.

**Comment by trimechee** [comment]
Hello, I remember that I tried a torrent software that transforms the torrent into streaming, and when I deleted the temporary file, it deleted the whole folder which contains other files, this traumatized me and alhamdoulilAllah I have not lost any important files....we hope that M-D will carefully check and delete only the downloaded temporary file and not the other files in the folder, thank you.

**Comment by mhogomchungu** [comment]
This ability will be available with the next version.

There is no GUI way to set the option and you will have to go to the settings file and look for the option "DeleteFilesOnCanceledDownload" and set it to true.

**Comment by trimechee** [comment]
Oahhh fantastic ! Many thanks for this important improvement ! 💯 🥇
