### ISSUE TITLE
strange github bug

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#364]
I make new issue with my other new account, but i don't see my issue when i use this account !!! @github ?!!! why ? @mhogomchungu just to check, have you seen my issue made by my other account?

https://github.com/mhogomchungu/media-downloader/issues/363

![image](https://github.com/mhogomchungu/media-downloader/assets/76402212/9cf58432-f8d5-4cb5-8290-613a8f9a02be)

**Comment by mhogomchungu** [comment]
I get a "page not found" error when clicking the link you provided and I do
not see any email notification in my inbox.

**Comment by trimechee** [comment]
It's a serous bug from @github, i will try to repost the issue

**Comment by trimechee** [comment]
![417463677_10222713254076611_7789861026582175061_n](https://github.com/mhogomchungu/media-downloader/assets/76402212/4f445cde-15fe-4235-bd70-f0ddf9c5f252)

**Comment by trimechee** [comment]
![Capture web_17-1-2024_14747_github com](https://github.com/mhogomchungu/media-downloader/assets/76402212/60c78589-e2ff-4dca-8a6b-e7aef82992d3)
