### ISSUE TITLE
Minor - Clicking the row number in the Get List results doesn't change the download options

### ISSUE THREAD

**Issue by ScottRFrost** [mhogomchungu/media-downloader#367]
In the list provided by Get List, it's kind of confusing because clicking the row number doesn't appear to do anything.  Hopefully it's easy to fix!

Video demonstrating the issue:

https://github.com/mhogomchungu/media-downloader/assets/3866418/7891c58c-d81b-453c-bd4e-836a58a41ee6

**Comment by mhogomchungu** [comment]
Fixed in the git version.
