### ISSUE TITLE
Creating a label for download options

### ISSUE THREAD

**Issue by abelokoj-github** [mhogomchungu/media-downloader#368]
I think it will be a great idea if we can have a **single name (label) to replace the commands** when selecting a download option from our previously saved download options.  That way, it can be easy to identify say **"code for downloading a playlist as an audio in .opus format"** as opposed to downloading in in mp3 format. I can easily choose between them without having to look through the commands

**Comment by mhogomchungu** [comment]
Adding an entry in the preset list will give the ability to give the entry
a label.

**Comment by mhogomchungu** [comment]
You can create a label with your preferred options by going to "configure" tab and then "preset options" sub tab.
