### ISSUE TITLE
Make Media-Downloader compatible with "Live-stream-downloader" extension and "hls-downloader' extension and preview video while downloading

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#371]
Hello, afer many researchs, this  is currently the best updated and open source extension for downloading videos : 

https://github.com/chandler-stimson/live-stream-downloader

https://webextension.org/listing/hls-downloader.html

Edit : This video downloader extension was updated recently, i add this extension please and we hope this extension also will be compatible with our so beloved Media-Downloader :) 

https://github.com/puemos/hls-downloader

https://puemos.gitbook.io/hls-downloader/

Our ultimate and final hope please Mr @mhogomchungu is to make our beloved Media-Downloader compatible with the great extension "Live-stream-downloader" i.e. this extension offers us the possibility of copying the url of embed videos , for example the "uqload" video on this site (third video player):

https://french-anime.com/animes-vf/1387-solo-leveling.html

and therefore to avoid the possible interruption of the download and more stability or speed or to save resources because web browser can be heavy, and since Media-Downloader is our default downloader and we even uninstalled idm, fdm..... because our favorite downloader is Media-downloader, we would like please Media-Downlaoder to be able to download the uqload video and videos from other embed platforms when we copy the url link of the uqload video or the url address of another embed video platform found by the "Live-stream-downloader" extension and maybe even add option :  'gather together and assemble audio and video separate stream'  if the video is in dash or hls formats, thank you very much ! 

Ahh i forget, tu make M-D even more and more better and awesome and definitely surpasses and replaces other famous downloaders, we also hope please an option : “automatically close/exit  media-downloader” if the download is completed or fails, thank you very much !

EDIT : I have another request please : when the user goes to do a direct download with a url link of an emebd video, M-D no longer uses yt-dlp because yt-dlp is no longer necessary and uses wget or aira2c for a stable and fast download instead to use the integrated download of the web browser and the number of threads and segments goes to 1 to be able to preview the video so please, it will be great to also add a "preview video" option, thank you !

Edit : i find this tool, may be it can help !

I find this integrator with download manager, may be it can help : 

https://github.com/ugetdm/uget-integrator

and : 

https://github.com/persepolisdm/Persepolis-WebExtension

EDIT : 

https://github.com/filecxx/FileCentipede
https://filecxx.com/en_US/index.html#features

and

EDIT : and :
https://github.com/AminBhst/brisk-browser-extension

and

https://github.com/KikoPlayProject/KikoPlay

I find this integrator with download manager, may be it can help : 

https://github.com/ugetdm/uget-integrator

https://github.com/subhra74/xdm-integration-module
https://github.com/subhra74/xdm-browser-monitor
https://github.com/subhra74/xdm-helper-chrome
https://github.com/subhra74/xdm-firefox-old

EDIT :: 

********
: integration with web browsers :

https://github.com/AminBhst/brisk-browser-extension

https://github.com/ugetdm/uget-integrator

and :

https://github.com/persepolisdm/Persepolis-WebExtension

https://github.com/subhra74/xdm-integration-module
https://github.com/subhra74/xdm-browser-monitor
https://github.com/subhra74/xdm-helper-chrome
https://github.com/subhra74/xdm-firefox-old

https://github.com/ginuerzh/gost/blob/master/README_en.md
https://github.com/kanishka-linux/hlspy
https://curl.se/
https://nodejs.org/en
https://www.electronjs.org/
https://github.com/SeaHOH/ykdl
https://github.com/selsta/hlsdl

**Comment by trimechee** [comment]
I mean when the user goes to do a direct download with a url link of an emebd video, M-D no longer uses yt-dlp because yt-dlp is no longer necessary and uses wget or aira2c for a stable and fast download instead to use the integrated download of the web browser and the number of threads and segments goes to 1 to be able to preview the video so please, it will be great to also add a "preview video" option, thank you !

**Comment by trimechee** [comment]
I find this integrator with download manager, may be it can help : 

https://github.com/ugetdm/uget-integrator

**Comment by mhogomchungu** [comment]
These extensions are designed to work from within a web browser and they use specific APIs that are available in the web browsers they support.

Media Downloader is not a web browser so there is no way it can support these extensions.

**Comment by trimechee** [comment]
Interesting ! Thank you so much for having examinate my request and your precious response :) 💯
