### ISSUE TITLE
Automatically recognize and paste the url address from the clipboard bug

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#375]
Hello, thank you for the new awesome version ! 🥇 💯 

There is a little problem please : Often I have several YouTube videos to download quickly with a preset and I use batch downloader and the "inspect clipboard for url" box is enabled and so when I copy the url addresses of many videos, the videos are automatically added to the M-D waiting list, but with the new version,  M-D no longer recognizes the URL addresses present in the clipboard and we have to manually click on a button to add each video :(

**Comment by mhogomchungu** [comment]
Fixed and new release with a fix is out

https://github.com/mhogomchungu/media-downloader/releases/tag/4.3.1

**Comment by trimechee** [comment]
Awesome ! Thank you so much :)
