### ISSUE TITLE
Show hidden file sizes

### ISSUE THREAD

**Issue by kolbdog3333** [mhogomchungu/media-downloader#379]
I was just wondering if you can make it so on the format list it shows all the file sizes since on some of the format selections some are hidden and it just shows a dash if its a guess file size. Be nice if it would show all files sizes even some are estimates since not a mp4 stream but a m3u8 stream. Since don't want to call the "-F" on yt-dlp be easier to view on here.

**Comment by kolbdog3333** [comment]
Yes since there are other websites other than youtube use format selection for like cartoonetwork, shout-factory, dailymotion excetra, when I do show formats the entire format list is blank on those sites but when I do "-F" on yt-dlp it shows the formats but those 3 are just examples in talking about almost all websites that aren't YouTube.

**Comment by kolbdog3333** [comment]
Here are few links and pictures as well:
https://www.dailymotion.com/video/x8p60dz
https://disneynow.com/shows/bluey/season-03/episode-29-stories/vdka34938149
![Barney 2](https://github.com/mhogomchungu/media-downloader/assets/75857608/95eeb712-cced-4319-ad4a-ebe00b6729cc)
![Barney](https://github.com/mhogomchungu/media-downloader/assets/75857608/84c59aee-3102-4f6f-8d91-e202d675a051)
![Bluey 2](https://github.com/mhogomchungu/media-downloader/assets/75857608/881af209-9452-487b-b946-688a211f775a)
![Bluey](https://github.com/mhogomchungu/media-downloader/assets/75857608/b402e36d-ce28-4ffb-95f8-732b8adb4b82)

**Comment by kolbdog3333** [comment]
As you can see when i do the same videos on yt-dlp it shows the file sizes but on media downloader it doesnt this is for almost all websites that aren't YouTube.

**Comment by kolbdog3333** [comment]
Can you at least make it so it shows the file size estimate the "~" " file sizes even though they aren't exact file sizes since websites besides youtube use "≈" if there is an https video and its an exact size and not an estimate.

**Comment by mhogomchungu** [comment]
Done

You can use this new functionality by switching to git version and instructions on how to do it are here: https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#14-how-do-i-start-updating-from-git-channel-instead-of-release-channel-when-using-windows

![Screenshot_20240218_210920](https://github.com/mhogomchungu/media-downloader/assets/3496115/b0fe7756-9ba7-405e-8fb7-2428b45a8eaf)
![Screenshot_20240218_211216](https://github.com/mhogomchungu/media-downloader/assets/3496115/6382d341-3385-4bf3-b2ba-bc26efed6456)

**Comment by kolbdog3333** [comment]
Doesnt work for every video site since just tested it on video.disney.com Here is video link: https://video.disney.com/watch/steamboat-willie-4ea9de5180b375f7476ada2c
So why did you only do those two sites when its every site thats not youtube you should also do it for websites that don't show the video or audio codec as well.

**Comment by kolbdog3333** [comment]
I also tested it 15 other sites same problem.

**Comment by kolbdog3333** [comment]
Never mind forget those two comments i had to restart it after it downloaded upadate and it worked again
