### ISSUE TITLE
Blank file sizes on Get List for Youtube

### ISSUE THREAD

**Issue by kolbdog3333** [mhogomchungu/media-downloader#380]
It seems when you added the ~  Before the file sizes for other websites it seems that youtube videos are now blank file sizes with the "~" only file size that comes up is the precompiled versions the rest is blank along with most video sizes and audio as well here is a screenshot using a youtube video. 
![Untitled 2](https://github.com/mhogomchungu/media-downloader/assets/75857608/9981d39c-8fa8-4ff9-b7dd-6e626fc8c97d)
![Untitled](https://github.com/mhogomchungu/media-downloader/assets/75857608/50200805-de9d-488e-9987-e6ff404e1fd0)

**Comment by kolbdog3333** [comment]
It still works on other websites fine but now the youtube videos have that bug since it seems by puting the "~" before the file size for estimates I think you accidentally did it for all videos and audios that are correcrt sizes not just the estimates only so i think that is what is causing youtube to have a lot of blank file sizes.

**Comment by mhogomchungu** [comment]
Fixed and file sizes gets their own column for easier reading.

![Screenshot_20240220_063915](https://github.com/mhogomchungu/media-downloader/assets/3496115/614ba31b-7d66-44b8-8dce-e8add02cbd2d)
