### ISSUE TITLE
How to not include the last 12 digits (the id of the youtube video) in the filename itself?

### ISSUE THREAD

**Issue by RevanMardagh** [mhogomchungu/media-downloader#382]
I have tried many ways, and I cannot manage to do it. Would be very glad if someone could help.

**Comment by mhogomchungu** [comment]
https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#3-how-to-make-downloaded-media-not-have-weird-text-in-the-file-name

**Comment by RevanMardagh** [comment]
thanks! :)
