### ISSUE TITLE
Newest git update problem

### ISSUE THREAD

**Issue by kolbdog3333** [mhogomchungu/media-downloader#383]
IT seems the newest update for git release is on a never ending loop. Since once you update it and restart Media Downloader after the git release downloads and it does everything else it starts the download git release process all over again its been like this for 2 days straight since last git release.

**Comment by mhogomchungu** [comment]
You are using Qt6 or Qt5?

**Comment by kolbdog3333** [comment]
The git release updates worked fine until 2 days ago.

**Comment by kolbdog3333** [comment]
I could update it and then restart but i wouldnt get another release until next one but the last update on here was two days ago and that is when the loop update started it would extract after fully downloads then i would let it check for the other updates then close it to restart to apply it. But then it would download the latest git release again after it just downloaded and extractected it been doing it for 2 days straight now.

**Comment by kolbdog3333** [comment]
I've been using the 4.3.1official release on here since then on the portable version i have the other version my installed one set for git release its very annoying since the last git release was two days agao and its still doing the downloadiong and extracting

**Comment by kolbdog3333** [comment]
What mean by post contents on basic downloader? So download an item first on basic after it goes trhought the auto download then close it and resart it sorry not following

**Comment by kolbdog3333** [comment]
Thank you it fixed it.
