### ISSUE TITLE
[REQUEST]: Option to select multiple URLs to download in the "playlist Downloader".

### ISSUE THREAD

**Issue by tnilzon** [mhogomchungu/media-downloader#384]
In the "Playlist Downloader" tab, it would be a great option to be able to select a number of separate Url:s for download (before the download starts). As it is now, you can only select one Url, and right click to download one at a time from the downloaded list. I think it would be desirable to be able to select several individual URLs (for example by holding Ctrl or Shift when clicking on individual URLs), (if you don't wish to download all items in the list).

**Comment by mhogomchungu** [comment]
Done.

You can use a git version from below link you get the functionality now if you are using windows. Uninstall first the version you have installed if you are going to use a version that use an installer.

Using this feature respects the configured number of maximum concurrent downloads.

https://github.com/mhogomchungu/media-downloader-git/releases/tag/0.0.0

**Comment by tnilzon** [comment]
Great, thanks for feefback!HälsningarTomas Nilzon<Sent from my Galaxy>
-------- Original message --------From: mhogomchungu ***@***.***> Date: 3/12/24  13:28  (GMT+01:00) To: mhogomchungu/media-downloader ***@***.***> Cc: Tomas NIlzon ***@***.***>, Author ***@***.***> Subject: Re: [mhogomchungu/media-downloader] [REQUEST]: Option to select multiple URLs to download in the "playlist Downloader". (Issue #384) 
Done.
You can use a git version from below link you get the functionality now if you are using windows. Uninstall first the version you have installed if you are going to use a version that use an installer.
Using this feature respects the configured number of maximum concurrent downloads.
https://github.com/mhogomchungu/media-downloader-git/releases/tag/0.0.0
