### ISSUE TITLE
Media Downloader looses extension svtplay-dl after Windows restart

### ISSUE THREAD

**Issue by tnilzon** [mhogomchungu/media-downloader#385]
After installing Media Downloader, and also adding the extension svtplay-dl, every thing works as expected (Media Downloader finds the svtplay-dl.exe during launch, and downloads works perfectly). But after a Windows restart, Media Downloader does not find the svtplay-dl.exe anymore. Instead, during launch of Media Downloader an error message is displayed:

[media-downloader] Failed to find executable "svtplay-dl.exe"
[media-downloader] Error, executable to backend "svtplay-dl" could not be found.

Media Downloader version: 4.4.0.132001/4.4.0.190749
svtdplay-dl version: 4.69
Windows 11 Pro version: 10.0.2263 B22631

svtplay-dl folder is located in C:\Program Files (x86)\Media Downloader\3rdParty
svtplay-dl.json is located in 'C:\Users\user\AppData\Roaming\media-downloader\engines.v1

**Comment by mhogomchungu** [comment]
Post all the text on the basic downloader tab.

**Comment by tnilzon** [comment]
Think I have found a solution by myself. After adding the path in Windows Environment Variables to the install of svtplay-dl, it looks like it is working.

 

BR
Tomas N

**Comment by mhogomchungu** [comment]
Your solution is wrong.

Look at the circled path in the image below and then go to the equivalent path on your system and inside of it, you will see a folder named "bin". You should put svtplay-dl in the bin folder. All runtime data are found in this "App Data Path".

![Screenshot_20240321_194009](https://github.com/mhogomchungu/media-downloader/assets/3496115/7bbc8e8b-9ab5-4dde-a44b-e43d11a53a39)

**Comment by mhogomchungu** [comment]
You should put svtplay-dl in "C:\Users\user\AppData\Roaming\media-downloader\bin" path.

**Comment by tnilzon** [comment]
Ok, but my solution also works.

But I will correct it according to your advice.

Many thanks!

 

BR
Tomas N

**Comment by tnilzon** [comment]
Thanks!

 

BR
Tomas N

**Comment by mhogomchungu** [comment]
The git version can now auto download and auto update svtplay-dl.

![Screenshot_20240322_211755](https://github.com/mhogomchungu/media-downloader/assets/3496115/c6d14915-2496-4dc7-891c-ad70f52962b5)

**Comment by tnilzon** [comment]
Great news, thanks!BRTomas Nilzon<Sent from my Galaxy>
-------- Original message --------From: mhogomchungu ***@***.***> Date: 3/22/24  19:27  (GMT+01:00) To: mhogomchungu/media-downloader ***@***.***> Cc: Tomas NIlzon ***@***.***>, Author ***@***.***> Subject: Re: [mhogomchungu/media-downloader] Media Downloader looses extension svtplay-dl after Windows restart (Issue #385) 
The git version can now auto download and auto update svtplay-dl.
Screenshot_20240322_211755.png (view on web)
