### ISSUE TITLE
Logout cancelled by media-downloader (KDE Plasma)

### ISSUE THREAD

**Issue by pvint** [mhogomchungu/media-downloader#386]
When restarting or shutting down KDE media-downloader is cancelling the process. It does close, but it is necessary to initiate the logout again to proceed.

![Desktop 1_005](https://github.com/mhogomchungu/media-downloader/assets/608740/9e8e7c74-4003-4af6-b392-4fa9efe0ecc3)

In mainwindow.cpp line 222 void QEvent::ignore() is called:

```
void MainWindow::closeEvent( QCloseEvent * e )
{
	e->ignore() ;

	this->hide() ;

	if( !m_showTrayIcon ){

		this->quitApp() ;
	}
}
```

Changing the `e->ignore()` to `e->accept()` seems to fix the problem without affecting anything, but perhaps I'm not understanding why ignore was used.

**Comment by mhogomchungu** [comment]
Thanks, i have experience this behavior but never looked into it, i have reworked the code and the problem should now be gone.

**Comment by pvint** [comment]
Perfect! Tested and it functions as expected. Thanks!
