### ISSUE TITLE
Add option "download audio only " (i.e. automatically convert the downloaded video into audio or use presets "bestaudio/worstaudio" of yt-dlp  if there are dash audio formats)

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#387]
Hello, sometimes we just need to listen to the audio of a video, to help us fall asleep and so the computer screen turns off at night when we sleep or to send the downloaded audio to our smartphone when we go out for a walk and do sports via, for example:

https://snapdrop.net/
https://node-snapdrop.herokuapp.com/
https://pairdrop.net/
https://www.sharedrop.io/

https://kdeconnect.kde.org/
https://retroshare.cc/index.html

https://kdeconnect.kde.org/
https://github.com/linuxmint/warpinator
https://github.com/danopdev/LNDP-Android
https://github.com/LANDrop
https://landrop.app/#top

Intel® Unison™
https://apps.microsoft.com/detail/9PP9GZM2GN26?hl=en-us&gl=US

https://riftshare.app/
https://github.com/achhabra2/riftshare
https://blog.checkyo.tech/

https://winpinator.swisz.cz/
https://www.airdroid.com/personal/
https://github.com/pdf/kdeconnect-chrome-extension
https://github.com/slowscript/warpinator-windows
https://github.com/slowscript/warpinator-android
https://github.com/slowscript/warp

https://www.bloomoffline.com/
https://f-droid.org/packages/org.cimbar.camerafilecopy/
https://github.com/sz3/cfc
https://cimbar.org/
https://stestagg.github.io/dashcast/
https://github.com/kaangiray26/share
https://share.buzl.uk/

and therefore the space on our smartphone or ssd is limited hence the interest of the "download audio only" option, i.e. on streaming sites there are documentaries with a very large size of 1GB and more whereas we just want to listen to the audio or on youtube or dailymotion where there are documentaries in very high definition and we just like to listen to the audio so we hope for an option in our beloved Media-Downloader to automatically extract the audio from the downloaded video file and the downloaded video file which weighs a lot will be deleted to keep only the audio of the video, 

or use use presets :
"bestaudio" and "worstaudio" of yt-dlp or these presets (if there is bugs because worstaudio preset seems it does not allow us to move within the downloaded file using the progress bar ! )  :

-f worstaudio -x
-f bestaudio -x

thank you!

**Comment by mhogomchungu** [comment]
Options added for other websites to download audio only or audio/video and then extract audio.

**Comment by trimechee** [comment]
Awesome !!! Thank you so much Mr @mhogomchungu :) 🥇 💯
