### ISSUE TITLE
Translation - Pelase don't include in language fiel reference to source lines

### ISSUE THREAD

**Issue by bovirus** [mhogomchungu/media-downloader#388]
@mhogomchungu 

Could you please check the way how to create language file (.ts) to avoid to inlcude in language file reference to source line like

<location filename="../src/mainwindow.ui" line="66"/>
<location filename="../src/mainwindow.ui" line="957"/>

because these info can change also if you don't change really teh content of teh strings (don't add /don't delete new strings).

Please leave on langauge files only string id/original string/translation strings.

Thanks.

**Comment by mhogomchungu** [comment]
Done, i have a script [here](https://github.com/mhogomchungu/media-downloader/blob/main/src/update_translations) that is supposed to do the right thing but i forget sometimes and i use wrong options from command line history. Going the delete the wrong one to make sure i do not use it again.

**Comment by bovirus** [comment]
@mhogomchungu 

Thanks!
I will check on next language update.

**Comment by mhogomchungu** [comment]
A script for updating translations is [here](https://github.com/mhogomchungu/media-downloader/blob/main/src/update_translations).

For reasons i do not know, sometimes references to source files are added to translation files and other times they are removed and i added a command at line 7 to make sure they are never added and this should hopefully solve this problem for good.
