### ISSUE TITLE
Get desktop notification on download completion

### ISSUE THREAD

**Issue by wmortume** [mhogomchungu/media-downloader#393]
It would be helpful to add an option on the configure tab to get a notification from the desktop notification panel when a file has finished downloading. This would be very handy for big files that take time to download.

**Comment by mhogomchungu** [comment]
What operating system are you using?

**Comment by wmortume** [comment]
@mhogomchungu I'm on Windows 11 (64-bit Pro)

**Comment by mhogomchungu** [comment]
The functionality just landed but will require manually changing a config option because there is no room in the UI for more options.

![Screenshot_20240415_185004](https://github.com/mhogomchungu/media-downloader/assets/3496115/78ac3f8b-5005-47fa-a95d-c6f7f4246cf1)

**Comment by wmortume** [comment]
@mhogomchungu Would that be in a json config file and when is it getting released? In the GUI you can add a small checkbox/toggle option for notifications but I guess that could be skipped for another time.

**Comment by mhogomchungu** [comment]
New version is out and changelog has instructions on how to enable this feature

https://github.com/mhogomchungu/media-downloader/releases/tag/4.6.0
