### ISSUE TITLE
Need Authentication

### ISSUE THREAD

**Issue by arjung24** [mhogomchungu/media-downloader#40]
Some sites needs authentication for downloading like vk.com . is it possible to integrate a feature like i will sign in for vk.com for one time inside the app and it will work then anytime i download from vk.com. it will be very helpful feature specially for me.

Thanks

**Comment by mhogomchungu** [comment]
It should be possible to do what you want without specific support for the website from the application.

In the "Options" field, put ```best -u ABC -p DEF``` where ABC is your username and DEF is your password and check and see if it works, if that does not work then a second option is to log in to the website and then get the website cookie and use that instead and we will try thing if the easier and first option fail.

**Comment by arjung24** [comment]
it's working perfectly with first option. thanks a lot.

**Comment by arjung24** [comment]
sorry to ask here but I can't download from hotstar. is there any option so that i can download from this site.

**Comment by mhogomchungu** [comment]
You may need to use a cookie for this website, checkout this link[1] for how to get a cookie file for a website.

[1] https://apple.stackexchange.com/questions/349697/how-to-use-youtube-dl-cookies

**Comment by arjung24** [comment]
But is it possible to download from hotstar outside india??

**Comment by mhogomchungu** [comment]
Sorry for a later reply, i do not know the answer to your question.

If you can make it work outside of media downloader then post here your solution and i will look into adding your solution to the project.

Closing this one since the original problem is solved.
