### ISSUE TITLE
UI thinking about software applications🤔

### ISSUE THREAD

**Issue by SONGjiemo** [mhogomchungu/media-downloader#403]
LOGO
![画板 9 (1)](https://github.com/mhogomchungu/media-downloader/assets/46627639/5406901a-c2c1-4ca6-b717-1a02ba1de593)

1、The default interface after opening the software
![Desktop](https://github.com/mhogomchungu/media-downloader/assets/46627639/d99ac99b-64e5-4924-a297-7009e384282e)
The TBA tabs are, in order, software log, pending download, batch download, download completed and settings. 5 large pages in total
The batch download is YouTube’s list address
2、Software startup log
![log](https://github.com/mhogomchungu/media-downloader/assets/46627639/01221f62-ffcd-4820-9026-ee6630d96c6b)
Add link to YouTube or m3u8 or live stream address
![add](https://github.com/mhogomchungu/media-downloader/assets/46627639/c4b4d475-4187-4eca-802e-8c6e9f03efd5)
3、The software setting interface provides common parameter settings such as adding plug-ins, adjusting the number of download threads, proxy address, default video format and resolution, etc.
![SET](https://github.com/mhogomchungu/media-downloader/assets/46627639/d1ebf3ba-b1c4-41bc-a196-57c737207fc0)

**Comment by SONGjiemo** [comment]
[设计文件 3.zip](https://github.com/mhogomchungu/media-downloader/files/15369152/3.zip)

**Comment by mhogomchungu** [comment]
Making drastic changes to the UI now is not possible.

When looking at the UI, keep in mind the following:-

1. The application is not designed to work with yt-dlp only and with youtube only. Gallery-dl for example is primarily used to download pictures and UI elements that works best with youtube makes no sense to gallery-dl.
3. Having UI changing depending on what program is selected to do actual downloading does not scale because the application supports arbitrary tools that follow a few rules the application want.
4. A core value of the application is to make it possible for a user to do anything from within the application they can do when using the terminal and this necessitates those text fields to set configure whatever program a user want to use to do the actual downloading.

**Comment by SONGjiemo** [comment]
> Making drastic changes to the UI now is not possible.
> 
> When looking at the UI, keep in mind the following:-
> 
> 1. The application is not designed to work with yt-dlp only and with youtube only. Gallery-dl for example is primarily used to download pictures and UI elements that works best with youtube makes no sense to gallery-dl.
> 2. Having UI changing depending on what program is selected to do actual downloading does not scale because the application supports arbitrary tools that follow a few rules the application want.
> 3. A core value of the application is to make it possible for a user to do anything from within the application they can do when using the terminal and this necessitates those text fields to set configure whatever program a user want to use to do the actual downloading.

Hello, the role I am giving yt-dlp automatically. But my interface is based on other software, which is also an interface that specializes in downloading YouTube videos. As for what you said, don't make big changes.
My thoughts are as follows:
1. Your first interface
![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/a41949d4-e4d2-4e92-abd9-4469acedef87)
That's the interface
![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/fa7bd2cf-da36-463b-ae0d-b3bf7086ffd6)

2、My Downloads screen and Download List screen
![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/4ee5c659-6f96-42e1-8eee-908151810719)
That's the interface
![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/504673c8-7ee0-4029-b8e2-24fc24ac2f6d)

3、Settings interface
![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/f06a59d7-e079-4e49-a258-2167a09081fe)
That is
![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/2a33cbf0-3ea7-44c6-9438-31abb30f5a10)

Summary.
In fact, it's based on your stuff and makes a beautified cover. If some parts are not convenient to modify. Yes, you don't have to modify it. That is, the overall interface can be modified according to my layout. Just a reference

IF YOU CAN, I PROVIDE THE LOGO. Hope you can use it.

**Comment by mhogomchungu** [comment]
This tool is matured now and it is not possible to make big UI changes.
