### ISSUE TITLE
Switch to nightly yt-dlp?

### ISSUE THREAD

**Issue by kolbdog323** [mhogomchungu/media-downloader#405]
Is there way you can switch to nightly yt-dlp build its more up to date then the normal the regular one.

**Comment by mhogomchungu** [comment]
1. Go to a folder on your system that is shown in the same place in the image below.
2. Go to ```engines.v1``` subfolder.
3. Open```yt-dlp.json``` text file with a text editor.
4. Replace ```DownloadUrl``` value with "https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest".
5. Restart Media Downloader.

![Screenshot_20240522_085048](https://github.com/mhogomchungu/media-downloader/assets/3496115/db644d22-b5d7-4001-a0d0-e02fc91e59c7)
