### ISSUE TITLE
All-New (awesome!) MacOS version cannot be opened (possibly: corrupted download maybe?)

### ISSUE THREAD

**Issue by ThiccOwl** [mhogomchungu/media-downloader#406]
Hiya!

Please let me prefix this, by saying: I am an ABSOLUTE AMATEUR! I am super new to anything FOSS or GitHub and so on... I am really really trying to just read-up and research on whatever I can, in an (futile?) attempt to NOT ask dumb questions and annoy everyone with them! However once in a while I am just stumped, and cannot for the life of me figure out a solution on my own, no matter how hard I try or read-up everything trying to find an answer... Like here right now:

I feel as if maybe, the '.dmg' file for the all-new (awesome!) MacOS version of 'media-downloader' might maybe be 'broken' or 'corrupted' possibly?

Because no matter what I try or how I try it, I always keep getting displayed the same error by the MacOS system:

"MediaDownloader.app is damaged and can't be opened. You should eject the disk"

(I also tried to attach a screenshot of this, just in case...)

So I tried downloading the '.dmg' file here in GitHub in a different browser, as I thought maybe the file got corrupted by/during the download or something, but still nothing sadly...

Now, maybe I found a lil error/bug here, but the way more likely explanation is that I am doing some really really dumb amateur mistake here! If that should be indeed the case, then I can just really apologize! But would of course still be thankful for any and all help maybe thrown my way!

Thank you so so much!
And, again, I apologize for any and all mistakes made by Me here!

All the Best!

![ScreenshotGitHub01](https://github.com/mhogomchungu/media-downloader/assets/105682582/6b3ec9a5-a281-4c7b-a09b-72a08b1240d3)

**Comment by mhogomchungu** [comment]
A bit of googling landed  me here: https://www.reddit.com/r/macsysadmin/comments/13vu7f3/app_is_damaged_and_cant_be_opened_error_on_ventura/

The solution here is for me ti sign the binary but  can not do that.

A work around is for you to run the "xattr" command to make your system not complain about the bundle not being signed.

**Comment by mhogomchungu** [comment]
I have added a sentence next to MacOS link that says the bundle is not notarized and to expect the error you are getting and with a suggestion to search the internet on how to install not notarized bundles.
