### ISSUE TITLE
Best Audio Only (MP3) is not really "the best"

### ISSUE THREAD

**Issue by AdKiller** [mhogomchungu/media-downloader#407]
I use this command line and get higher Average MP3 Bitrate than your program. So the Best Audio in your program is not really "the best."

yt-dlp.exe --extract-audio --audio-quality 0 --audio-format mp3 -o "%%(title)s %%(id)s.%%(ext)s" "%input%"

But other than that, it seems like a great tool.

**Comment by mhogomchungu** [comment]
Next version will add ```--audio-quality 0``` option, thanks for informing me that it was missing.
