### ISSUE TITLE
Location of plugins/Connecting already installed plugins

### ISSUE THREAD

**Issue by Vladimir-russian** [mhogomchungu/media-downloader#411]
Hello all,

I have been using YTDLP and Gallery-dl separately for most of the download. I never knew about this repository but i think this is simply a best idea

 **I already have Gallery-dl and ytdlp installed. How do I direct media-downloader to use these already installed applications ? where do I find the Json or exe file for already-installed repositories?**

**Comment by mhogomchungu** [comment]
What operating system are you using?

Start the application, go to "basic downloader" and look for "App Data Path" folder path. All application data are in that folder. Extension's binaries are in "bin" subfolder and extension's json files are in "engines.v1" subfolder.

Media Downloader uses its own private copies plugin's binaries to make it possible to download and auto update them.

Instructions of how to install gallery-dl extension is here: https://github.com/mhogomchungu/media-downloader/wiki/Extensions#4-gallery-dl

Yt-dlp extension is already installed.

**Comment by Vladimir-russian** [comment]
> What operating system are you using?
> 
> Start the application, go to "basic downloader" and look for "App Data Path" folder path. All application data are in that folder. Extension's binaries are in "bin" subfolder and extension's json files are in "engines.v1" subfolder.
> 
> Media Downloader uses its own private copies plugin's binaries to make it possible to download and auto update them.
> 
> Instructions of how to install gallery-dl extension is here: https://github.com/mhogomchungu/media-downloader/wiki/Extensions#4-gallery-dl
> 
> Yt-dlp extension is already installed.

I am using windows

I have already installed Gallery-dl and I was hoping to use this installed version. Reason is I have already done a lot of setup/rules etc and I have archive file where I keep record of all downloads. I want Media downloader to use same gallery-dl so archive/records can be updated.

**Comment by Vladimir-russian** [comment]
If it is not possible to connect both,
how do I setup a rule/condition/set that whenever mediadownloader runs and it used gallery dl, it should update a particular sqlitte file at specific location?

**Comment by mhogomchungu** [comment]
It is not possible for Media Downloader to use galley-dl or any other programs it depends that is located outside of its internal folder.

Why not delete the version of gallery-dl you downloaded and then reconfigure your setup to use this version?

**Comment by Vladimir-russian** [comment]
What if I create links to already downloaded GL version and place it in that internal folder ?

My biggest problem is that I have a config file with lots of options setup . How would I use that file with Media-downlader version of GL ?

**Comment by mhogomchungu** [comment]
Gallery-dl has a "--config" option you can use to tell it where the config file is.

In Media Downloader:-
1. Go to "Configure" tab and then go to "Engine's Default Option" subtab.
2. At the "Engine's Name" menu, select "gallery-dl".
3. At the "Options to add" text field, add ```--config "ABC"``` where ```ABC``` is a full path to where you put the config file. Quotes are necessary if the path has a space character in it.
4. Click "Add".
5. Right click the added entry and then select "Set As Default".

Continue to use Media Downloader with gallery-dl and it should not start using the config file from where you prefer to put it.

**Comment by Vladimir-russian** [comment]
Thank you . So if path is like this C:\Users\XXX\AppData\Roaming\gallery-dl

I should enter below command  ?

-config C:\Users\XXX\AppData\Roaming\gallery-dl (without quotes)

**Comment by mhogomchungu** [comment]
Option to enter should be
```
--config C:\Users\XXX\AppData\Roaming\gallery-dl.conf
```
The last component of the path should be the name of gallery-dl configuration file.

**Comment by mhogomchungu** [comment]
Closing this one as "fixed" but feel free to post if suggestion above is not working for you.
