### ISSUE TITLE
Filenames

### ISSUE THREAD

**Issue by outlaw420** [mhogomchungu/media-downloader#42]
Is it possible to change the default filename for downloaded videos? 

Instead of:
some youtube video 2021-[youtube ID]

I'd like:
some youtube video 2021

There's probably a ytdl command for this but I'm not sure how to make it work

**Comment by mhogomchungu** [comment]
https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#3-how-to-make-downloaded-media-not-have-weird-text-in-the-file-name

**Comment by outlaw420** [comment]
Thanks, that worked. I suppose the batch downloader isn't able to parse multiple links at once (iirc youtube-dl GUI can do this)? It seems to be possible with a text file but that method is slower.

**Comment by mhogomchungu** [comment]
No, it can not, each link has to be added separately to allow concurrent downloading for each link.

Basic downloader accepts multiple links and it passes them along to youtube-dl and youtube-dl will download each link sequentially and in the order they were provided.

**Comment by mhogomchungu** [comment]
Closing this one as "fixed".
