### ISSUE TITLE
For reference, suggestions of new cli softwares download engines similar to N_m3u8DL-CLI for perhaps possible support in the future if there is bug or censorship of some m3u8 cli downloaders, and suggestions of some extensions addons which can give ideas for add some features or new platforms

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#424]
Hello, here a final reference issue to make suggestions of best tools that can help to improve downloading and support of new platforms, thank you !

https://github.com/chandler-stimson/live-stream-downloader

https://github.com/puemos/hls-downloader

https://github.com/sebaro/ViewTube
https://github.com/sebaro/SaveTube

https://github.com/xifangczy/URLProtocol

https://github.com/andy-portmen/open-in-vlc/

https://github.com/ray-lothian/Easy-Video-Downloader
https://webextension.org/listing/easy-video-downloader.html

https://github.com/54ac/stream-detector

https://github.com/inbasic/bulk-media-downloader
https://github.com/inbasic/turbo-download-manager-v2

https://github.com/woodruffw/ff2mpv
3DYD Youtube Source
https://ys.3dyd.com/

https://github.com/iawia002/lux

https://github.com/soimort/you-get

https://github.com/AminBhst/brisk-browser-extension

https://github.com/zaidka/cliget

https://github.com/kanishka-linux/hlspy

https://github.com/selsta/hlsdl

https://github.com/aclap-dev/vdhcoapp

https://github.com/CoolnsX/hls_downloader

https://sites.google.com/site/linkgopher/

https://github.com/emarsden/dash-mpd-cli

https://github.com/nilaoda/N_m3u8DL-CLI
https://github.com/nilaoda/N_m3u8DL-RE
https://github.com/globocom/m3u8

EDIT : and also

https://github.com/agalwood/Motrix

https://github.com/mhogomchungu/media-downloader
https://github.com/mhogomchungu/media-downloader/wiki/Extensions

https://github.com/giantpinkrobots/varia

https://github.com/filecxx/FileCentipede
https://filecxx.com/en_US/index.html#features

edit : and :
https://github.com/aandrew-me/ytDownloader
https://ytdn.netlify.app/

https://github.com/kannagi0303/yt-dlp-gui

https://github.com/ytdl-official/unlock

https://github.com/setvisible/ArrowDL
https://www.arrow-dl.com/

https://github.com/giantpinkrobots/varia
https://giantpinkrobots.github.io/varia/

https://github.com/ErrorFlynn/ytdlp-interface

https://github.com/database64128/youtube-dl-wpf
https://cube64128.xyz/

https://github.com/Maxstupo/ydl-ui

https://github.com/jeanslack/Videomass
https://jeanslack.github.io/Videomass/

https://oleksis.github.io/youtube-dl-gui/
https://github.com/oleksis/youtube-dl-gui

https://github.com/KurtBestor/Hitomi-Downloader

https://github.com/KikoPlayProject/KikoPlay
https://kikoplay.fun/

https://curl.se/

https://nodejs.org/en

https://www.electronjs.org/

https://github.com/SeaHOH/ykdl

https://github.com/CoolnsX/dra-cla

https://github.com/nilaoda/BBDown

Video m3u8 Sniffer - Find HLS Streaming URLs
M3U8 finder and HLS player
http://sigmafxdx.com/m3u8Sniffer/

https://github.com/CoolnsX/hls_downloader
https://coolnsx.github.io/

scripts and tools :

https://github.com/Momo707577045/m3u8-downloader
https://github.com/Momo707577045/media-source-extract
https://github.com/Momo707577045/tinypng-script-with-cache
http://blog.luckly-mjw.cn/tool-show/m3u8-downloader/index-en.html
https://segmentfault.com/a/1190000025182822

Native HLS playback
by Gaetan Hervouet
https://github.com/ghouet/chrome-hls
Native MPEG-Dash + HLS Playback
by David Cavar
https://github.com/Palethorn/native-adaptive-streaming
https://cavar.net/

https://github.com/pystardust/ani-cli
https://github.com/justfoolingaround/animdl

https://github.com/spencerwooo/onedrive-vercel-index
https://github.com/alist-org/alist

https://github.com/helloxz/ccaa

edit : integration with web browsers :

https://github.com/AminBhst/brisk-browser-extension

https://github.com/ugetdm/uget-integrator

and :

https://github.com/persepolisdm/Persepolis-WebExtension

https://github.com/filecxx/FileCentipede

https://github.com/subhra74/xdm-integration-module
https://github.com/subhra74/xdm-browser-monitor
https://github.com/subhra74/xdm-helper-chrome
https://github.com/subhra74/xdm-firefox-old

https://github.com/ginuerzh/gost/blob/master/README_en.md
https://github.com/kanishka-linux/hlspy
https://curl.se/
https://nodejs.org/en
https://www.electronjs.org/
https://github.com/SeaHOH/ykdl
https://github.com/selsta/hlsdl

https://github.com/iamtalhaasghar/yewtube
https://github.com/mps-youtube/yewtube/issues/1191
https://iamtalhaasghar.github.io/yewtube/

https://github.com/otisdog8/termitube

https://erickutcher.github.io/#HTTP_Downloader

https://github.com/nilaoda/BBDown

https://github.com/the1812/Bilibili-Evolved

https://github.com/kengwang/BiliDuang

https://github.com/MotooriKashin/Bilibili-Old

https://github.com/sodaling/FastestBilibiliDownloader

https://github.com/pystardust/ytfzf
https://github.com/justfoolingaround/fast-yt-search

https://github.com/anasty17/mirror-leech-telegram-bot
https://github.com/junedkh/jmdkh-mltb

**Comment by mhogomchungu** [comment]
It is not possible to support everything that is out there.

This list is too long and i can not go over each and every entry and evaluate it for inclusion.
