### ISSUE TITLE
[Feature Request] Flatpak/Discover version

### ISSUE THREAD

**Issue by Dounial** [mhogomchungu/media-downloader#430]
I can't install it on my steam deck (runs on arch btw) and would therefore prefer a Flatpak/Discover version if possible, are there any thoughts made on this yet? (I'm having trouble with compiling but will make a extra issue for that.)

More platforms/installation-options would mean better compatibility and more users :)

**Comment by mhogomchungu** [comment]
Package from aur[1] does not work for you?

Will look into it, i use a distribution that do not use systemd and it looks like flatbak nolonger requires systemd.

[1] https://aur.archlinux.org/packages/media-downloader

**Comment by Dounial** [comment]
> Package from aur[1] does not work for you?

No, it might be because I use a steam deck as desktop-PC  but I did configure everything appropriate and followed the README.md but it won't work - even if steam deck runs on arch linux

**Comment by mhogomchungu** [comment]
I use a distribution that does not use systemd and i just discovered today that flatpak no longer requires systemd.

I installed it from source and successfully managed to install and run krita.

I guess support flatpak is now possible, will look into it.

![Screenshot_20240803_213049](https://github.com/user-attachments/assets/1d6f201e-8ad9-4ef0-985d-244112fbc75c)

**Comment by mhogomchungu** [comment]
Flatpack version is below, please try it and tell me if you see any issues with.

https://github.com/mhogomchungu/media-downloader/releases/download/4.9.0/MediaDownloader-4.9.0.flatpak

**Comment by Dounial** [comment]
I am impressed, installation was super easy and now it simply works and purrs like a kitten :D Thank you for the really fast and working implementation, I really appreciate your work!

**Comment by mhogomchungu** [comment]
I have made changes to the flatpak and i suggest you uninstall the one you have and then install the updated one.

**Comment by mhogomchungu** [comment]
Update.

Media Downloader has passed all requirements to be added to fluthub and is just waiting to be included.

https://github.com/flathub/flathub/pulls?q=is%3Apr+is%3Aopen+label%3Aready

**Comment by mhogomchungu** [comment]
The project is now on [flutbub](https://flathub.org/apps/io.github.mhogomchungu.media-downloader).

Uninstall the one you have and install the one from fluthub.
