### ISSUE TITLE
Not downloaded in the desired location.

### ISSUE THREAD

**Issue by FloatingLizard** [mhogomchungu/media-downloader#433]
Hello,

  If I change the download location only a Youtube video will be saved in the desired location.  If they are "shorts" they end up in the default location regardless of the desired location that was chosen:
/home/XXXXX/.var/app/io.github.mhogomchungu.media-downloader/data

Cheers

**Comment by mhogomchungu** [comment]
Do you have a link a can use to test?

**Comment by jpalcantara** [comment]
Let me test after a restart first.

**Comment by jpalcantara** [comment]
Yes I needed to restart, it does indeed go to the intended location.  This software is much better than the one I have seen. 
Thanks.

**Comment by mhogomchungu** [comment]
1. Close Media Downloader.

2. Delete "/home/XXXXX/.var/app/io.github.mhogomchungu.media-downloader"
folder.

3. Start Media Downloader.

4. Check if the problem is still there or not.

**Comment by mhogomchungu** [comment]
Also report the version you are using.

**Comment by mhogomchungu** [comment]
Close for lack of activity
