### ISSUE TITLE
 [Feature Request] add a text file 

### ISSUE THREAD

**Issue by jpalcantara** [mhogomchungu/media-downloader#434]
Anyway we could attach a text file that contains all the URL to be downloaded, rather than pasting each URL to the field for Batch download?

**Comment by mhogomchungu** [comment]
It is already possible, right click the empy area in the batch downloader tab and then select "Get List From File".

![Screenshot_20240809_213134](https://github.com/user-attachments/assets/a030f32b-324a-40c9-a686-e5dc4b8e4f70)

**Comment by jpalcantara** [comment]
Working that is great!
