### ISSUE TITLE
O'Rielly

### ISSUE THREAD

**Issue by IVII1** [mhogomchungu/media-downloader#435]
Why are all O'Riellly videos limited to the first 1 min when downloaded? The duration is shown properly but only the first minute of each video is downloaded. Some extentions download entire vidoes but dont support batch downloading, so i would like so see whats the issue here so i can keep using this app

**Comment by larsen0815** [comment]
Please provide an example of such a video.

**Comment by mhogomchungu** [comment]
Safaribooks project is in hiatus and your problem will not be solved anytime soon. Best to look for alternatives.
