### ISSUE TITLE
[REQUEST] Add icons for dark themes

### ISSUE THREAD

**Issue by PavelDobCZ23** [mhogomchungu/media-downloader#438]
I am using media downloader on Fedora Linux 40(from official repos) with KDE Plasma and I have a dark application theme set globally.
Custom icons in the app, which only come in their dark form, are illegible when using a dark theme.
Icons in the red circle in the screenshot below are an example of this problem in the app.
Dark theme compatible icons should be shipped with the app and applied when dark theme is in use.
I also tried using the dark themes provided by the app directly, and they had the same problem.

![image](https://github.com/user-attachments/assets/ac89b395-cb4c-4452-a47e-da9a16631858)

**Comment by averagePedestrian** [comment]
I came here to suggest the same thing.

**Comment by mhogomchungu** [comment]
Do you have an example of how icons should look like when using a dark theme?

**Comment by PavelDobCZ23** [comment]
> Do you have an example of how icons should look like when using a dark theme?

I would imagine simply use white colour instead of black, when dark theme is detected, or a setting the user can configure.

**Comment by mhogomchungu** [comment]
Done.

Icons are now blue if a dark theme is configured in the app to be used.

![Screenshot_20240818_180116](https://github.com/user-attachments/assets/2e286d5b-11f1-46de-b20c-cbc7de7bbf92)

**Comment by mhogomchungu** [comment]
New version is out and it has support for this feature request.

https://github.com/mhogomchungu/media-downloader/releases/tag/5.0.1

**Comment by PavelDobCZ23** [comment]
> New version is out and it has support for this feature request.
> 
> [`5.0.1` (release)](https://github.com/mhogomchungu/media-downloader/releases/tag/5.0.1)

I am glad support has been added for this, but it only works with the custom themes of the app itself. When "Normal" theme is being used, and it's in dark colours, the app isn't aware of it, and the icons are still black. Could there be a toggle for the icon colours, in the configuration of the app?

**Comment by mhogomchungu** [comment]
Git version now changes icons based on the UI theme in use so it should work as you expect it to.

**Comment by averagePedestrian** [comment]
@mhogomchungu The colour chosen for the icons is difficult to see on LCD monitors due to their inherently low contrast ratio. Could you either choose colours with higher contrast for better visibility or make the icon colours user-configurable?

**Comment by mhogomchungu** [comment]
If you can do better than the icons i provide, can you donate your icons to the project so that others can use them by default?
