### ISSUE TITLE
[Feature Request] Embed Chapter Information in Downloaded Videos

### ISSUE THREAD

**Issue by averagePedestrian** [mhogomchungu/media-downloader#439]
Currently, Media Downloader lacks the capability to embed chapter information when downloading YouTube videos using the basic downloader tab. This feature would significantly enhance the overall functionality for users who value preserving video structure. Therefore, I would like to request the addition of an option in the user interface for enabling or disabling chapter embedding while downloading videos from supported sites.

**Comment by mhogomchungu** [comment]
Different people want different options from different supported backends and its not possible to have UI setting for every possible combination of backends and their options.

To solve the above problem, each tab in the app that deals with downloading has a text field named ```download options``` that give users options to add custom options to make a backend they are using do what they want.

The option to add to get the behavior you want is ```--embed-chapters```.

If you always want the above options to always be set then follow [these](https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#4-how-do-i-make-downloaded-media-be-in-a-subfolder-with-a-name-equal-to-the-playlist-name) instructions but at step 4, add the following text instead.

```
--embed-chapters --newline --ignore-config --no-playlist -o %(title).200s-%(id)s.%(ext)s
```
