### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by qwerty59b** [mhogomchungu/media-downloader#441]
1 could you add the option to rename because as I show in the image below the video takes me a strange name when downloading but if I had the option I would put e.g. throne of seal 112 and that's it.

2 another suggestion I have is to add an option to pause the download and continue it at another time from the % where it left off.

![imagen](https://github.com/user-attachments/assets/c6f0a9a1-3ac9-44a5-b8dd-bd8b30f37e3f)

**Comment by mhogomchungu** [comment]
First request is done and the option to rename already downloaded media is visible in the image 1 below.

Second request. You get this behavior when using default yt-dlp downloader. With it, downloaded data is saved in a temporary file and then moved to a destination file when the download is complete. If you cancel the download, the downloaded data remains in the temporary files and restarting the download will reuse the temporary files and you will resume downloading from the data you already downloaded. ffmpeg downloader does not seem to do this as it discards downloaded data and starts from the beginning and i think this is a limitation of ffmpeg and there is nothing i can do in Media Downloader.

Closing this one as finished.

![Screenshot_20240826_221234](https://github.com/user-attachments/assets/8c7476c0-34c0-4579-b27f-692f27b7ac37)
