### ISSUE TITLE
Show Comments issue.

### ISSUE THREAD

**Issue by Vilmodao** [mhogomchungu/media-downloader#442]
I'm not sure, but I think at some time the comment viewer function stopped working. For a while it seems like the process is going on, but it ends up with a blank page all the time. Maybe youtube changed something, or maybe I'm doing something wrong, but this method used to work for me before.

![screenshot_2024_08_30_at_00_00_52](https://github.com/user-attachments/assets/2eb4cf57-573a-419f-b842-5653fb5ec4cb)

This is MediaDownloader-5.0.1 on Windows 8.1

**Comment by mhogomchungu** [comment]
Are you sure you are using the latest version of yt-dlp?

One of the recent versions of yt-dlp fixed the problem.

**Comment by Vilmodao** [comment]
Oh, that really solved the problem.
I'm using the portable version and didn't even realize that any additional components were being used. 
But on closer look it became clear that MediaDownloader was using the old version of yt-dlp which is stored in ...AppData\Roaming\media-downloader\bin\.
I just deleted this old version and MediaDownloader downloaded the new one.
Thank you.

**Comment by mhogomchungu** [comment]
It is possible to force yt-dlp update by taking steps as shown below:-

![Screenshot_20240830_080205](https://github.com/user-attachments/assets/7b1633b2-56a7-4481-be15-98b34a7c3023)
