### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by dimurra** [mhogomchungu/media-downloader#447]
How to register work in media-downloader through individual proxies (with login and the password)?

**Comment by mhogomchungu** [comment]
1. Go to "configure" tab.
2. Go to "proxy settings" sub tab.
3. Click "Use manually specified proxy configuration".
4. Enter proxy configuration in the below text field.

Example options are shown in the above UI and others examples are below

1. socks5://user:pass@127.0.0.1:1080.
2. user:pass@127.0.0.1:1080.

**Comment by dimurra** [comment]
Many thanks, everything turned out. It is good to add these examples and to the program, and that is examples but without login and the password there.

**Comment by mhogomchungu** [comment]
Thanks for the advice.
