### ISSUE TITLE
Feature Request - Automatically Save to subfolders

### ISSUE THREAD

**Issue by Smackdab69** [mhogomchungu/media-downloader#452]
Is there any way to have Media Download, including yt-dl, automatically save downloaded content to a subfolder instead of just the folder defined in the config?

For example, if I download an entire yt channel, have it save to "Videos/ChannelA"

**Comment by mhogomchungu** [comment]
https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#4-how-do-i-make-downloaded-media-be-in-a-subfolder-with-a-name-equal-to-the-playlist-name

At Step 4 in the above link, add the following line instead.

```
-o --newline --ignore-config --no-playlist -o Videos/%(channel)s/%(title).200s-%(id)s.%(ext)s
```

**Comment by larsen0815** [comment]
The previous comment would always add the channel name, afaiu. Would be nice to have an option "Download playlists and channels into separate subfolders". That way, subfolders would not be used for single videos, but only for playlists/channels.

**Comment by mhogomchungu** [comment]
The UI is already too complicated and with too many options and adding new options should require a very high bar of need.

The UI already allows you to manipulate the -o option to make yt-dlp download files in whatever folder structure you want and i think this is good enough.
