### ISSUE TITLE
Oversized font and weird button colors

### ISSUE THREAD

**Issue by wmortume** [mhogomchungu/media-downloader#456]
I noticed after some recent updates the font is oversized and the purple button colors don't blend in, how can I fix this?
![image](https://github.com/user-attachments/assets/97760bde-1904-494f-ab5b-c9bdc63657b0)

**Comment by mhogomchungu** [comment]
I did not change anything about fonts.

I changed icon colors because somebody said old ones do not show well in dark theme.

**Comment by wmortume** [comment]
Rebooting my pc fixed it. Think it was happening because I had temporarily set a larger monitor (tv) as my primary display.

**Comment by Korb** [comment]
> weird button colors

Media Downloader 5.2.2 (2025-02-08)
Qt Version: 6.8.1
Microsoft Windows 10.0.19045.5487

Same:

![Image](https://github.com/user-attachments/assets/477a745c-6189-4b63-8371-38e8c8b85c5f)

> Foreground: #301FA3
> Background: #000000
> Contrast ratio: 1.851:1
> 1.4.11 Non-text Contrast (AA)
> ❌ Fail for UI components and graphical objects

> Foreground: #2837D2
> Background: #000000
> Contrast ratio: 2.567:1
> 1.4.11 Non-text Contrast (AA)
> ❌ Fail for UI components and graphical objects
