### ISSUE TITLE
Feature request - Ability to highlight and manipulate multiple entries in Playlist Downloader

### ISSUE THREAD

**Issue by Jatie1** [mhogomchungu/media-downloader#459]
In Playlist Downloader, you can't shift + click to highlight many entries, you can only ctrl click to 1 by 1 highlight each entry. And then if you want to right click -> remove multiple entries, you can't, it just removes the last entry even if there are multiple highlighted.

Requesting an easy way to highlight many entries with shift + click and also the various functionalities in the right click panel to work properly on those entries.

The page in question when you ctrl click on a few entries:
![image](https://github.com/user-attachments/assets/69b2814f-8a58-49cd-810a-366762d8a488)

**Comment by mhogomchungu** [comment]
It is possible to highlight multiple entries and download only those highlighted.

Not being able to delete all highlighted entries is a bug caused by me not thinking to implement it.
