### ISSUE TITLE
Can't download video

### ISSUE THREAD

**Issue by namyu25** [mhogomchungu/media-downloader#461]
Recently I tried to download a video that's unavailable in my country (all countries actually) and I can't, I downloaded other videos from the same channel months ago that are unavailable in the same way, is it because of a change from an update or on youtube's end?

**Comment by namyu25** [comment]
This is the error: Video unavailable. This video contains content from [channel name]. It is not available in your country.
[media-downloader] Download Failed(ErrorCode=1)
As I said this happens on other videos from the same channel that are also unavailable but I was able to download them months ago, they were also unavailable then.

**Comment by mhogomchungu** [comment]
Access to those videos are blocked in your country. 

Try accessing them through a VPN.

**Comment by namyu25** [comment]
As I said I checked with a website and found that they're unavailable worldwide, so a vpn is useless (even tho I tried). Is there any reason you can think of why I was able to download them in the past? (again, they were unavailable then too)

**Comment by mhogomchungu** [comment]
This is not a problem with Media Downloader and hence there is nothing i can do within MD to help you.
