### ISSUE TITLE
Disaster : yt-dlp dropping support for Python 3.8, our beloved Media-downloader will no longer support windows 7 32 bits os ? or M-D will use alterantive yt-dlp made by Mr Nicolaasjan  for 32 bits version ? 

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#465]
Hello, I am sad to discover this Announcement: Dropping support for Python 3.8

This will increase the minimum required Windows version to Windows 8; the yt-dlp release executables will no longer support Windows 7 or Windows Server 2008 R2.

Users on Windows 7 and Windows Server 2008 R2 will need to consider alternative options such as @nicolaasjan['s unofficial builds](https://github.com/nicolaasjan/yt-dlp/releases) if upgrading your operating system is not possible.

https://github.com/yt-dlp/yt-dlp/issues/10086

is our beloved Media-downloader going to drop the 32-bit version for windows 7 os? we hope that windows7 os will continue to be supported please!
I use windows 7 and probably many people still have old laptops that are still functional, thank you!

**Comment by mhogomchungu** [comment]
Media Downloader now uses yt_dlp from "Nicolaasjan" when running in Windows7.

**Comment by nicolaasjan** [comment]
Note that my build is **64bit**...
Direct link:
`https://github.com/nicolaasjan/yt-dlp/releases/latest/download/yt-dlp_win7_Py3.12.exe`

**Comment by mhogomchungu** [comment]
@nicolaasjan, Media Downloader now points to your "yt-dlp_win7_Py3.12.exe" when running in 64 bit Windows. What about 32 bit users of Windows7 like the OP here?

If you are to provide only a single binary then it makes more sense to offer a 32 bit only since it works also in 64 bit windows7.

**Comment by nicolaasjan** [comment]
> @nicolaasjan, Media Downloader now points to your "yt-dlp_win7_Py3.12.exe" when running in 64 bit Windows. What about 32 bit users of Windows7 like the OP here?
> 
> If you are to provide only a single binary then it makes more sense to offer a 32 bit only since it works also in 64 bit windows7.

They could use my **Python 3.9** build for Windows XP.
(custom Python 3.9 build from @cmalex from the MSFN forum)
Will work on Vista and Windows 7 as well. :)

```
[debug] Command-line config: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version local@2024.10.16 [fbc66e3ab] (win_x86_exe)
[debug] Python 3.9.13 (CPython AMD64 32bit) - Windows-7-6.1.7601-SP1 (OpenSSL 3.1.0-dev )
[debug] exe versions: ffmpeg git-2024-10-06-6871fd3-ffmpeg-windows-build-helpers (fdk,setts), ffprobe git-2024-10-06-6871fd3-ffmpeg-windows-build-helpers
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
```
(does not include `curl-cffi`, because that won't install on Windows XP)

Direct link:
`https://github.com/nicolaasjan/yt-dlp/releases/latest/download/yt-dlp_x86_Windows-XP.zip`

Has to be extracted though.
I can't offer it as an `.exe` file with another name, since that will break a lot of links already present on the internet...

**Comment by nicolaasjan** [comment]
Or I'll have to replace my 64bit Python on Windows 7 with the 32bit one...
@adang1345 offers these Windows 7 compatible installers.

**Comment by nicolaasjan** [comment]
> @nicolaasjan, Media Downloader now points to your "yt-dlp_win7_Py3.12.exe" when running in 64 bit Windows. What about 32 bit users of Windows7 like the OP here?
> 
> If you are to provide only a single binary then it makes more sense to offer a 32 bit only since it works also in 64 bit windows7.

Done. :)
I've installed the 32bit Python 3.12 from adang as well.

Uploaded to GitHub.
Direct link:
`https://github.com/nicolaasjan/yt-dlp/releases/latest/download/yt-dlp_win7_Py3.12_x86.exe`

**Comment by mhogomchungu** [comment]
@nicolaasjan 

I think i found a bug with your builds, as of right now, the latest version you provide is [this one](https://github.com/nicolaasjan/yt-dlp/releases/tag/2024.10.20.172859).

The github page says the latest version is "2024.10.20.172859" but the binary says the version is "2024.10.20". These two versions do not agree and causes Media Downloader to go to an endless updating loop.

**Comment by bashonly** [comment]
> The github page says the latest version is "2024.10.20.172859" but the binary says the version is "2024.10.20". These two versions do not agree and causes Media Downloader to go to an endless updating loop.

@nicolaasjan Before building the binary you can run this to apply the proper version/repo info:

```
python devscripts/update-version.py -c "nicolaasjan/yt-dlp" -r "nicolaasjan/yt-dlp" "2024.10.20.172859"
```

This is also necessary if you intend on enabling the updater as I suggested here: https://github.com/yt-dlp/yt-dlp/issues/10086#issuecomment-2424279489

I'll edit that comment to include this info

**Comment by nicolaasjan** [comment]
> @nicolaasjan
> 
> I think i found a bug with your builds, as of right now, the latest version you provide is [this one](https://github.com/nicolaasjan/yt-dlp/releases/tag/2024.10.20.172859).
> 
> The github page says the latest version is "2024.10.20.172859" but the binary says the version is "2024.10.20". These two versions do not agree and causes Media Downloader to go to an endless updating loop.

@mhogomchungu
Could you test the new version in my [Releases](https://github.com/nicolaasjan/yt-dlp/releases)?
(names of the Win7 versions are changed)

**Comment by mhogomchungu** [comment]
@nicolaasjan 

It works now and below is output when running for the first time under windows7(simulated since i do not have windows7)
```
[media-downloader] Running In Portable Mode
[media-downloader] Download Path: C:/projects/build-md/yt
[media-downloader] App Data Path: C:/projects/build-md/local
[media-downloader] *************************************************************
[media-downloader] Checking installed version of Media Downloader
[media-downloader] Found version: 5.1.0
[media-downloader] Start Downloading yt-dlp ... ... ...
[media-downloader] Downloading: https://github.com/nicolaasjan/yt-dlp/releases/download/2024.10.21.150458/yt-dlp_win7_x86.exe
[media-downloader] Destination: C:/projects/build-md/local/bin/yt-dlp_win7_x86.exe.tmp
[media-downloader] Downloading yt-dlp: 16.05 MiB / 16.05 MiB (100.00%)
[media-downloader] Download complete
[media-downloader] Renaming file to: C:/projects/build-md/local/bin/yt-dlp_win7_x86.exe
[media-downloader] Checking installed version of yt-dlp
[media-downloader] Found version: 2024.10.21.150458
[media-downloader] Checking installed version of aria2c
[media-downloader] Found version: 1.37.0
[media-downloader] Checking installed version of wget
[media-downloader] Found version: 1.21.3
[media-downloader] Checking installed version of bsdtar
[media-downloader] Found version: 3.6.1
[media-downloader] Checking installed version of ffmpeg
[media-downloader] Found version: n6.0-36-gc5039e158d-20231023

**Comment by mhogomchungu** [comment]
> Mr @mhogomchungu, it seems to me that I read that one of the developers of yt-dlp advises us to use the beta versions in-between releases of yt-dlp because bugs appear and the beta version of yt-dlp quickly fixes the problems, perhaps to distinguish itself from competitors and for better efficiency in the face of bug problems, Media-Downloader should integrate an option "download the beta version in-between releases of yt-dlp in case of bugs with the stable version of yt-dlp", thank you very much !

Media Downloader has a generic way to support different programs through a json config file and an example config file for yt-dlp look a like is [this](https://github.com/mhogomchungu/media-downloader/blob/main/extensions/yt-dlp.json)

The proper way to support win7 binaries of yt-dlp is to have another extension that changes "DownloadUrl", "Name" and exe name fields but i decided to "hijack" default "yt-dlp" extensions in code for windows7 users to give them a smooth transition  to nicolaasjan repository.

You can easily change to any yt-dlp repository by changing the "downloadUrl" and this is how i prefer it as it gives maximum flexibility 

A simple UI option will allow switching repository channels(nightly/master/release) but will not allow switching to a different repository.

**Comment by nicolaasjan** [comment]
> tomorrow if you get tired of compiling yt-dlp windows 7/xp or, we hope not, your computer breaks down, does that mean the total and definitive disappearance of yt-dlp? and we have to dig into our savings to buy a new modern laptop?

You could also buy a relatively cheap refurbished laptop/desktop.
Also, someone can to learn how to compile it themself. 😉

Alternative for older PC's: Install a lightweight Linux distro.
Modern versions have Python ≥3.10 installed by default and can run the `yt-dlp` executable.

> and I admit I thought you were compiling yt-dlp because you have a widows xp computer but you informed us that you use a virtual machine and you have a modern intel i3, so what motivates you to generously compile yt dlp? people asked you to do this and it's to help others who are still using old laptops/OS ?

It's an i5. 😉
My motivation? I know how it is to be poor.

**Comment by nicolaasjan** [comment]
> linux is not officially supported by asus

I have an Asus motherboard as well and Linux Mint runs fine.
As long as you don't have the newest hardware, driver compatibility is very good on Linux out of the box.

Linux security is great.
I'm running it for about 18 years now and haven't had any malware issues.
Most issues arise on _unpatched_ servers.
Good article:
https://easylinuxtipsproject.blogspot.com/p/security.html

> If you only install software from the secured official "software store" (software repositories) of your Linux distribution, then that's a very effective barrier against malware. More than that, there are no Linux viruses or rootkits "in the wild" for end users like yourself. (The exception is viruses targeted at Linux web servers, but securing web servers is quite a different cup of tea.)
