### ISSUE TITLE
[Bug] Error when downloading with option "Best Available Audio Only+Thumbnail" - Flatpak

### ISSUE THREAD

**Issue by PavelDobCZ23** [mhogomchungu/media-downloader#466]
**Description**

Using the option "Best Available Audio Only+Thumbnail" to download a video fails with a python error caused by a missing module.
The specific error is `ERROR: Postprocessing: module mutagen was not found. Please install using python3 -m pip install mutagen`.
The issue is happening with the Flatpak build.

**Steps to reproduce**
- Find some youtube video and get its URL
- Enter it into the "Enter URL:" field of "Basic Downloader" tab.
- Set the download options to "-f bestaudio --extract-audio --audio-quality 0 --embed-thumbnail" or select "Best Available Audio Only+Thumbnail" from the "Options" dropdown menu.

**System Information**
- OS: Fedora 40
- DE: KDE Plasma 6.2
- Version: 5.1.0
- Platform: Flatpak

**Logs**

```
[media-downloader] cmd: "/home/pavel/.var/app/io.github.mhogomchungu.media-downloader/data/media-downloader/bin/yt-dlp" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-P" "/home/pavel/Downloads/Media Downloader" "-f" "bestaudio" "--extract-audio" "--audio-quality" "0" "--embed-thumbnail" "--compat-options" "2022" "--progress-template" "download:[download] downloaded_bytes:%(progress.downloaded_bytes)s ETA:%(progress.eta)s total_bytes_estimate:%(progress.total_bytes_estimate)s total_bytes:%(progress.total_bytes)s progress.speed:%(progress.speed)s filename:%(progress.filename)s" "https://www.youtube.com/watch?v=mb_P6xtu1Ek"
[youtube] Extracting URL: https://www.youtube.com/watch?v=mb_P6xtu1Ek
[youtube] mb_P6xtu1Ek: Downloading webpage
[youtube] mb_P6xtu1Ek: Downloading ios player API JSON
[youtube] mb_P6xtu1Ek: Downloading mweb player API JSON
[youtube] mb_P6xtu1Ek: Downloading m3u8 information
[info] mb_P6xtu1Ek: Downloading 1 format(s): 251
[info] Downloading video thumbnail 38 ...
[info] Writing video thumbnail 38 to: /home/pavel/Downloads/Media Downloader/Human-mb_P6xtu1Ek.webp
[download] Destination: /home/pavel/Downloads/Media Downloader/Human-mb_P6xtu1Ek.webm
[download] 3.13 MiB / 3.13 MiB (100%) at 10.02 MiB/s, ETA NA
[ExtractAudio] Destination: /home/pavel/Downloads/Media Downloader/Human-mb_P6xtu1Ek.opus
[ThumbnailsConvertor] Converting thumbnail "/home/pavel/Downloads/Media Downloader/Human-mb_P6xtu1Ek.webp" to png
ERROR: Postprocessing: module mutagen was not found. Please install using `python3 -m pip install mutagen`
[media-downloader] Download Failed(ErrorCode=1)
```

**Comment by mhogomchungu** [comment]
A flatpak update should show up within a few hours from now and the update should work since it bundles mutagen.

**Comment by Blitz0070** [comment]
Still getting exact same issue as described in this ticket currently. Same steps to reproduce except my environment is on Linux Mint 22 on DE Cinnamon.

**Comment by mhogomchungu** [comment]
Post the output of the following command
```
flatpak list -d | grep media-downloader

```

**Comment by mhogomchungu** [comment]
It should now work as expected with the next update that will show up within a day or two.

**Comment by mhogomchungu** [comment]
Update is available now, can you confirm that it works?
