### ISSUE TITLE
Safaribooks plugin stuck at login

### ISSUE THREAD

**Issue by abhatt014** [mhogomchungu/media-downloader#468]
Hi Team
Safaribooks plugin is stuck at login
![image](https://github.com/user-attachments/assets/91843a08-ce61-4b4a-a475-da682761be98)

**Comment by mhogomchungu** [comment]
[Upstream](https://github.com/lorenzodifuccia/safaribooks) is no longer actively working on this project so its issues will most likely not get fixed any time soon.

Best to look for alternatives.
