### ISSUE TITLE
Add GUI graphical interface for Vot-cli : the rare amazing revolutionary CLI software which allows to download audio from translated video donwload dubbing video voiceover , subtitles reader  with beautiful rare natural voices of Yandex !

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#469]
Hello, I find this rare CLI tool exceptional based on the revolutionary extension Voice-over-translation which allows us to translate video with neuronal AI of yandex and dubbing voiceover translated video read subtital with natural voices of yandex and convert subtitles to speech with tts reader speech synthesizer of subtitles useful to learn languages ​​or for visually impaired viewers with rare feature of natural voices of this surprising open source rare CLI tool vot-cli and extension Voice-over-translation !!

https://github.com/ilyhalight/voice-over-translation

so vot-cli the CLI tool is derived from the extension Voice over translation :

https://github.com/FOSWLY/vot-cli/blob/main/README-EN.md

https://github.com/FOSWLY/vot-cli

so we hope please, to make things easier, a graphical interface of this small script that allows us to download an audio translation from Yandex via the terminal ! Thank you so much :)

**Comment by mhogomchungu** [comment]
This is a web browser extension and it can not work with Media Downloader.

Media Downloader works with stand alone CLI tools that are script friendly.
