### ISSUE TITLE
Add these new rare plugins to yt-dlp 

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#471]
Hello, i discover new plugins that can enhance yt-dlp and make it more powerful, it will be great to integrate some of these rare awesome plugins please, thankyou !

https://github.com/yt-dlp/yt-dlp-wiki/blob/master/Plugins.md
https://github.com/seproDev/yt-dlp-ChromeCookieUnlock
https://github.com/un-def/dl-plus
https://github.com/pratikpatel8982/yt-dlp-hianime
https://github.com/pratikpatel8982/yt-dlp-mp4decrypt
https://github.com/ytdl-patched/ytdl-patched
https://github.com/yt-dlp/yt-dlp/wiki/Forks
https://github.com/kemuvx/hianime-dl
https://github.com/pratikpatel8982/AnimeDownloader

**Comment by mhogomchungu** [comment]
All  these are not popular enough to be worth supporting.
