### ISSUE TITLE
Question marks instead of the Russian letters at downloading.

### ISSUE THREAD

**Issue by dimurra** [mhogomchungu/media-downloader#473]
Hello, question such: at addition of references from the youtube of the name of video in Russian are displayed normally but as soon as loading (in media downloader begins - the Russian letters are displayed by question marks). The downloaded file in the folder where was loaded displayed normally. Whether it is possible as that to win.

**Comment by mhogomchungu** [comment]
1. Post a link I can use to test.

2. What operating system are you using.

**Comment by dimurra** [comment]
1. https://www.youtube.com/watch?v=ArZyJmsHCDM

2. Win 7x64

**Comment by mhogomchungu** [comment]
1. Go to "Configure" tab.
2. Go to "General Options" sub tab.
3. At the "Text Encoding" text field, add "utf-8".
4. Click "Save",
5. Try to download something and see if it makes a difference.

**Comment by dimurra** [comment]
Many thanks, everything turned out.
