### ISSUE TITLE
Add StartupWMClass to .desktop file in flathub version

### ISSUE THREAD

**Issue by iWisp360** [mhogomchungu/media-downloader#474]
Media Downloader from Flathub doesn't show any icon, just generic Wayland one.

To fix this a StartupWMClass has to be set in the .desktop file.

**Comment by mhogomchungu** [comment]
Can you post a screenshot that shows the problem?

**Comment by iWisp360** [comment]
> Can you post a screenshot that shows the problem?

![Screenshot_20241102_134745](https://github.com/user-attachments/assets/d3def4d1-47d1-4f21-a895-190e9917b251)

**Comment by mhogomchungu** [comment]
I already made the change but something is wrong with flathub infrastructure and it prevents the build from being published.

https://github.com/flathub/io.github.mhogomchungu.media-downloader/pull/7
