### ISSUE TITLE
Make revert to old version of yt-dlp possible

### ISSUE THREAD

**Issue by gs-foto** [mhogomchungu/media-downloader#476]
Since yt-dlp has deprecated Python3.8 I can't download anything with media-downloader.
It would be helpful to revert to an older version, or to use an older external yt-dlp on my system.

**Comment by mhogomchungu** [comment]
What operating system are you using?

**Comment by gs-foto** [comment]
Oh, sorry. I'm on Ubuntu 20.04. I have python 3.8.10 installed.

**Comment by mhogomchungu** [comment]
Can't you install a newer version of python in our system?

If yes, then install a newer version and tell media-downloader to use your newer version by following instructions as provided [here](https://github.com/mhogomchungu/media-downloader/issues/249).

**Comment by gs-foto** [comment]
My system was victim of a failed sys-update, and as a result my python is rather fragile and I'm reluctant to update it until I'm ready to install a completely new system on a new drive.
But that's not your problem. 
If it's not worth it to other users to make a reversion possible (and it probably isn't), we can call this closed and I'll live with a cli yt-dlp until I can install a new system.
After all, this really is not your problem.
Thanks for your time.

**Comment by gs-foto** [comment]
Thank you very much. That should work for me.

**Comment by gs-foto** [comment]
Just dropping in to say it worked perfectly. Thanks again.
