### ISSUE TITLE
Error message after update to the new version in my windows 7 os 32 bits

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#477]
Hi, when installing the new exceptional version of Media-Downloader on my windows 7 os 32 bits, I get a warning message that 'there is something missing and the error message asks me to reinstall the program....

" [media-downloader] Exit Code: -1
[media-downloader] Exit Status: Normal Exit
[media-downloader] Std Out: [PYI-1032:ERROR] Failed to load Python DLL 'C:\Users\ADMINI~1.ASU\AppData\Local\Temp\_MEI58402\python310.dll'.
LoadLibrary: Le module sp�cifi� est introuvable. "

so I uninstall M-D and I will download the new version and do new install hoping that this error message will not appear anymore, and I will do download tests to check that yt dlp works fine...and I will inform you of the result soon.....

we should install python ? because i use yt-dlp windows 7 32 bits made by Mr Nicolaasjan with potplayer without installing python and i have no problem, everything is fine with potpyaer, mpc be mpc hc that use yt-dlp 32 bits windows 7 of Mr Nicolaasjan......

**Comment by mhogomchungu** [comment]
1. Go to "Configure" tab.
2. Go to General Options" sub tab.
3. Click "Update Plugin" button and then select "yt-dlp".
4. Post all output on the "basic downloader" tab.
