### ISSUE TITLE
Update of yt-dlp-aria2c

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#478]
Hi, sometimes downloading via yt-dlp is throttled so using yt-dlp-aria2c extension solves this problem to speed up downloading speed, and so I wonder, since we manually add yt-dlp-aria2c extension, do we have to re-download and re-install the capital vital extension yt-dlp-aria2c  from time to time to manually update " yt-dlp-aria2c " extension ? or Media-Downloader will automatically update yt-dlp-aria2c extension ?

**Comment by mhogomchungu** [comment]
No need to update the extension, it should just always work after it is installed.
