### ISSUE TITLE
Great news! The Stream Detector extension project will be relaunched soon with new improvements and we hope 100% compatibility with this extension already supported by Media-Dwnaloder to fix cookies issues with yt-dlp and we hope please Stream Detector will be officially added to the catalog of extensions supported by Media-Downloader !

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#482]
Hello, I have already talked about the Stream Detector extension with Mr Mhogomchungu:

https://github.com/54ac/stream-detector

and Mr Mhogomchungu had the great kindness, class, generosity to add support for this extension despite the fact that this extension is currently on hold and not updated temporarily!

Stream detector extension IS vital because it have the rare ability to export cookies to yt-dlp because currently yt-dlp command --cookies-from-browser chrome is having problems because chrome is strengthening security and canceling the import of cookies and The Stream Detector is the only downloader in the world that allows us to export cookies to yt-dlp which allows to fix many problems !!

and so the developer of Stream detector has just informed me of this sensational news:

 "It still works, or at least I still use it quite often, so it doesn't really seem to need updates - but I do plan on rewriting it soon using a more modern approach which should allow me to make it a bit more user friendly and easier to work on."

so we hope please Mr @mhogomchungu for complete compatibility with the future awesome  new version of Stream Detector please! Thank you!

and we also hope Stream Detector extension will be officially added to the catalog of the extensions supported by Media-Downloader to further highlight the rare support of this vital extension by our amaing Media-Donwloader! Thanks :)

**Comment by mhogomchungu** [comment]
Lets revisit this when it get active again and newer version work differently from current version.
