### ISSUE TITLE
Add support of hianime-dl

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#484]
Hi, i find this rare tool to download easily some anime videos without the need to search and detect the hidden url videos of embedded streaming videos..... some anime are too old and may be free of rights so it will be great please to add gui and  support of this tool because we can't watch streaming videos in heavy web browsers because playback lag freeze in web browser  because my eee pc is too weak and old , thanks ! 

https://github.com/kemuvx/hianime-dl

**Comment by mhogomchungu** [comment]
This one seems too young, too inactive, it has no release yet and does seem to have users.

It does not meet a bar to be supported.

**Comment by trimechee** [comment]
Yes but it is a promising project, because we will no longer need an extension to detect the streams, this hianime-dl project can become even more interesting if it supports other platforms like vidmoly, seeanime website.....hianime seems to be a good site but I do not understand spoken English well, I asked the developer to add specific support for other streaming sites....but hianime has vostfr videos i.e. Japanese or English dubbed videos with embedded French or Arabic subtitles....

I don't know, if I add this hianime-dl project to media -downoader as I added aria2cyt-dlp, wget, ffmpag yt-dlp... will it work? I think there is a plugin to add as for aria2cyt-dlp so that media -donwloader can use this downloader engine?


i will tell to the developer, if he more updated his project, maybe the famous media -downloader can support him and add GUI....
