### ISSUE TITLE
Set .desktop filename

### ISSUE THREAD

**Issue by mak448a** [mhogomchungu/media-downloader#486]
The icon under wayland is the placeholder "w" icon. Could you fix this?
There's an easy fix that KDE's website shows.
https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

Here's what I did for my Python app:
```python
app = QApplication(sys.argv)
app.setDesktopFileName("io.github.mak448a.Qtcord")
```
This isn't C++ code, but I just left it here for reference.

**Comment by mhogomchungu** [comment]
1. What distribution are you using? 
2. What is the name of the media downloader's executable?

**Comment by mak448a** [comment]
1. Flatpak.
2. `/var/lib/flatpak/app/io.github.mhogomchungu.media-downloader/x86_64/stable/c42d3b51b386a2daccd6799addf96319d33af4d0601f531238f8f04ab5e4c59b/export/bin/io.github.mhogomchungu.media-downloader`

**Comment by mhogomchungu** [comment]
New build is available now for updating, did the new build make a difference?

**Comment by mak448a** [comment]
Thanks! It works! @mhogomchungu
