### ISSUE TITLE
Program won't download file to correct download path until the program has been closed and opened again

### ISSUE THREAD

**Issue by han-tykje** [mhogomchungu/media-downloader#487]
So say I have the folder Download1 as the download path, and want to change it to Download2.

I change the download path in the settings menu from Download1 to Download2 and press "save", and get a new URL from Youtube and then download the video.

The video will still be downloaded to folder Download1 even though I set Download2 as the download path.

The problem can be fixed by closing the program and opening it again. Downloading the same URL again will now download the video to the correct folder, Download2.

This is on Windows 10
Version is MediaDownloaderQt6-5.2.0 (but this bug was also on 5.12.0)

**Comment by mhogomchungu** [comment]
This is fixed now.
