### ISSUE TITLE
Add support of cliget extension to avoid youtube cookies problems 

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#488]
Hi, i see that the extension cliget is compatible with aria2c, wget used by Media-Downloader and we hope please add support of cliget extension to avoid youtube cookies problems , thanks !

https://github.com/zaidka/cliget

**Comment by mhogomchungu** [comment]
This is a firefox extension, it does not work outside of firefox and it can not with inside Media Downloader.
