### ISSUE TITLE
Add support of the very new vital awesome life saver N_m3u8DL-RE for windows 7 32 bits version

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#489]
Hi, our old windows 7 os laptops can be weak and sometimes impossible to watch streaming videos without lags freeze, the solution is to download hence the vital importance of our beloved Media-Downloader which allows us to download, thank you!! 💯 🥇

some streaming streams have separate audio only and video only streams like in a media player on the voiranime site, I tried the Cat-catch extension to download the stream and Cat-catch uses its famous online service ffmeg online to merge audio and video streams but Cat-catch's ffmpeg online now shows me an error message and the developer tells me my cpu is probably too old to support ffmpeg online instructions:

https://ffmpeg.bmmmd.com/

Cat-catch says webassembly imposes a technical file size limit of 2 GB and therefore the web browser apparently cannot download video files larger than 2 GB, and the developer of cat catch recommends using an external parser N_m3u8DL-RE supported by cat catch when there are problems with ffmpeg online....

the great N_m3u8DL-RE is apparently an online tool command and I don't know much about how to manipulate commands..... and also N_m3u8DL-RE was compatible only with windows 10 or windows 11 os, i ask the developer of N_m3u8DL-RE to make a 32-bit version for my windows 7 os and the great Mr Nilaoda makes our dream come true :

https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/11954691686#artifacts
https://github.com/nilaoda/N_m3u8DL-RE/issues/425#event-15382894720
https://github.com/nilaoda/N_m3u8DL-RE/pull/494

and the great Mr Adei also compiles for me a version of N_m3u8DL-RE for windows 7 os 32 bits:

https://github.com/adeii/Qt6Win7/releases/download/Test652/N_m3u8DL-RE-x86-Win7.7z

https://github.com/adeii/Qt6Win7/releases/tag/Test652

it seems that the great N_m3u8DL-RE has a GUI !!! :

https://github.com/nilaoda/N_m3u8DL-RE-SimpleG

so the dream please is to use Cat catch with the great Media-downloader of the great Mr Mhogomchungu who we hope M-D will add support and a GUI for the N_m3u8DL-RE commands to make it easier for us to download embed streaming videos and merge complicated complex videos, thank you!

**Comment by mhogomchungu** [comment]
This tools asks questions and you have to answer them by moving the cursor around.

Its output has texts with colors, progress bars with spinning wheels!

It is not designed to be scripted.
