### ISSUE TITLE
Error in safaribooks plugin

### ISSUE THREAD

**Issue by rivman** [mhogomchungu/media-downloader#49]
Hello,
Thank you for providing this wonderful tool for Windows users.
I have some error while using safaribooks plugin:

`[-] Logging into Safari Books Online...
                                                                 
[#] Unhandled Exception: 'next' (type: KeyError)
                                                                 
[!] Aborting...`

I tried to put username/password in json file at ...AppData\Roaming\media-downloader\engines.v1\safaribooks.js and also in config Engine default options > Safaribooks > --creed "username@domain.com:password"

Is there any way to use it ? I hope to achieve book images download since the  safaribook (https://github.com/lorenzodifuccia/safaribooks) don't download them (using linux on a raspberypi).

Many thanks for any insights.

**Comment by mhogomchungu** [comment]
Are you using linux or windows?

**Comment by mhogomchungu** [comment]
1. Start media downloader.
2. Go to configure tab.
3. Go to general options.
4. Click update engines and then select "safaribooks" to update it and it should to version 0.0.3 and the problem should go away. Make sure you have active internet connection before executing this step.
