### ISSUE TITLE
Add support of this vital plugin : yt-dlp-mp4decrypt

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#490]
Hi, i find this capital vital important plugin for yt-dlp that use command line : 

https://github.com/pratikpatel8982/yt-dlp-mp4decrypt
https://www.bento4.com/documentation/mp4decrypt/
https://github.com/axiomatic-systems/Bento4/tree/master/Source/C%2B%2B/Apps/Mp4Decrypt

"This is a plugin for yt-dlp that enables decryption of encrypted audio and video files using the mp4decrypt command-line tool. The files will be decrypted instantly after download and will replace the encrypted files."

the dream please  is add suport for this command line plugin to support more videos and protocol and sites and make M-D even more universal downloader for all types of streaming videos, thanks !

**Comment by larsen0815** [comment]
Where do you find encrypted videos?

**Comment by mhogomchungu** [comment]
This one does not seem to be popular and it does not have any release yet, not worth supporting.
