### ISSUE TITLE
Support command line anime downloaders

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#491]
Hi, i use weak old eee pc and i have weak internet connexion and i can't watch anime streaming video because it lag jerks, there is free anime websites that brodacst old animes ..... these site are available in the web  so wa can watch them but streaming lag jerk, so  we hope our beloved Media-Downloader will be able to download from these sites by adding GUI support for these command line anime donwloaders tools , thanks ! 

https://github.com/CoolnsX/dra-cla

https://github.com/Benexl/FastAnime

https://github.com/lanlinju/Animius

https://github.com/670848654/MoviesBox
https://github.com/670848654/SakuraAnime

https://github.com/open-ani/animeko

https://github.com/pratikpatel8982/yt-dlp-hianime
https://github.com/pratikpatel8982/yt-dlp-mp4decrypt

https://github.com/pystardust/ani-cli

https://github.com/kemuvx/hianime-dl

https://github.com/pratikpatel8982/AnimeDownloader

https://github.com/LifeActor/ykdl

https://github.com/Lagradost/cloudstream-3
https://github.com/saikou-app/saikou

https://github.com/ytdl-patched/ytdl-patched
https://github.com/yt-dlp/yt-dlp/wiki/Forks

**Comment by mhogomchungu** [comment]
It is not possible to support anything that is out there.

Adding support is not free and has to be limited to tools that are sufficiently popular and not too different from the ones that are already support.

The first one on your list has no release, how can i support something that has no fixed target?

Second one seems to have its own UI on the terminal and i do not think its output is suitable for a GUI frontend

Third and fourth ones looks like are  in chinese, i can not read chinese.

List is too long and i do not think they are worth supporting.

**Comment by trimechee** [comment]
We understand, thanks :)
