### ISSUE TITLE
Downloading extremely slow on WiFi, but perfect on Ethernet connection 

### ISSUE THREAD

**Issue by shvedes** [mhogomchungu/media-downloader#492]
The title speaks by itself.
If i try to download any youtube video on Ethernet connection, it connects to servers and downloading needed webpage, API JSONs and video itself very quickly, but on WiFi, any requests to server are very, very slow. Sometimes i need 2-3 mins just to get stuff mentioned above, and up to 5-10 mins to download a video, which is 20 secs or so. 
I'm surely can confirm that i don't have problems with WiFi connection, since any app, that require a good connection is works flawlessly

I'm using Arch Linux with NetworkManager, 6.12.1-1-cachyos-rt-bore kernel and no custom network settings.

Edit: i don't use any specific flags for downloading; just pasting link and pressing on download button

**Comment by mhogomchungu** [comment]
This is strange but the problem is not caused by Media Downloader and there is nothing i can do to fix it.

Run yt-dlp from the terminal and you will get the same behavior.
