### ISSUE TITLE
Difficulties using LUX in media downloader.

### ISSUE THREAD

**Issue by NoobieHarb** [mhogomchungu/media-downloader#493]
Hi.

I have been trying to use the LUX plugin, to download videos from VIMEO, but I haven't been able to do so.

[media-downloader] cmd: "/home/jose/.var/app/io.github.mhogomchungu.media-downloader/data/media-downloader/bin/lux" "https://vimeo.com/groups/35mmandrisdamburs/videos/495047641"
panic: runtime error: index out of range [1] with length 0
goroutine 1 [running]:
github.com/iawia002/lux/extractors/vimeo.(*extractor).Extract(0xc000143628?, {0x7ffe3f5ef41b, 0x3b}, {0x0, {0x0, 0x0}, 0x1, 0x0, 0xa, {0x0, ...}, ...})
	/home/runner/work/lux/lux/extractors/vimeo/vimeo.go:62 +0x7c8
github.com/iawia002/lux/extractors.Extract({0x7ffe3f5ef41b?, 0x2?}, {0x0, {0x0, 0x0}, 0x1, 0x0, 0xa, {0x0, 0x0}, ...})
	/home/runner/work/lux/lux/extractors/extractors.go:54 +0x351
github.com/iawia002/lux/app.download(0xc000120500, {0x7ffe3f5ef41b, 0x3b})
	/home/runner/work/lux/lux/app/app.go:275 +0x2e8
github.com/iawia002/lux/app.New.func1(0xc000120500)
	/home/runner/work/lux/lux/app/app.go:252 +0x691
github.com/urfave/cli/v2.(*App).RunContext(0xc0000ec4e0, {0x107bc40, 0x19c8e80}, {0xc00003e080, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322 +0x928
github.com/urfave/cli/v2.(*App).Run(0x70?, {0xc00003e080?, 0x7f399e0b9b08?, 0x10000000010?})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224 +0x2f
main.main()
	/home/runner/work/lux/lux/main.go:13 +0x39
[media-downloader] Download Failed(ErrorCode=2)
----
![Captura de pantalla de 2024-12-04 21-46-52](https://github.com/user-attachments/assets/d3eac0fd-9810-4694-a269-b87ca42e3eb0)
---
What should be done to make the plugin work?
-
Thanks in advance.

**Comment by mhogomchungu** [comment]
Nothing i can do in Media Downloader and i have reported the issue with lux [here](https://github.com/iawia002/lux/issues/1392).

yt-dlp works with this link so you can use it while you are waiting for lux to fix the problem.

![Screenshot_20241205_073350](https://github.com/user-attachments/assets/40787395-5ef9-466a-9448-beb21bc3f774)

**Comment by darklight9630-arch** [comment]
Hi, Mr. @mhogomchungu, how are you? I no longer see "lux" in the "extensions" section of Media Downloader. Has support for "lux" been discontinued in M-D ?

https://github.com/iawia002/lux

We hope Mr. @iawia002 will help fix the issue please. Using "lux" without a graphical interface can be difficult for non-experts, and we hope for some help to better integrate "lux" into Media Downloader!

**Comment by mhogomchungu** [comment]
Yes Lux support is disabled because its been two years since it was last released i do not think it currently work with any website.

If you are using it then with what website?

**Comment by darklight9630-arch** [comment]
Indeed, I realized it afterward; the last stable version was two years ago. But what leaves room for hope is that the developer remains active and merges pull requests, even though the last merged pull request dates back eight months:

https://github.com/iawia002/lux/pull/1434#pullrequestreview-3615085890

If Lux fixes the problem with Vimeo, which is a well-known site, and releases a new stable version, then maybe Mr. Mhogomchungu will reintroduce Lux!
