### ISSUE TITLE
I find new updated forks of famous Vxkex that fix bugs, add features and support of new softwares for windows 7,  so we hope please support of windows 7 will continue please, does Vxkex let us use MediaDownloaderQt6-5.2.0.setup.exe in our windows 7 os 32 bits ?  

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#497]
Hi, the great project Vxkex that allows windows 7 os to use windows 10/11 os software has been removed from github, some say microsoft fears this project so they banned it from github...

So today I find new rare projects of Vxkex that add updates features, fix bugs, add support for new softwares !! may be these new updated forks can help the great Media-Downloader to keep support of our windows 7 os 32 bits please ! and obviously I think wndows 7 os users will be happy  to install Vxkex which is very easy to use and without risk for the os! 

 Thanks and huge thanks and gratitude to Mr @mhogomchungu for the rare heroic generous support of windows 7 OS 32 bts :) 💯 🥇

https://github.com/i486/VxKex/issues/36 (YuZhouRen86 fork updated)

https://github.com/Aqua-Vision/MgKex (fork updated)

https://github.com/i486/VxKex (clone of original project)

and also : 

extended kernel by Mr dotexe1337
http://www.dotexe.cf/extended/
https://web.archive.org/web/20241006001741/https://www.dotexe.cf/extended/
https://github.com/kernel-extenders/nt61

windows 7 os improve usuablility 32 bits (use with caution, prudence)
https://github.com/winrevive/win7-sp2
https://sp2.winrevive.xyz/

Same request to great Mr @nicolaasjan please who generously and heroically offers us yt-dlp versions for windows 7 os 32 bits, thank you very much! 💯 🥇 if compiling yt-dlp becomes difficult or impossible on windows 7 os 32 bits,may be these new forks of famous Vxkex can help :) 💯 🥇

I have question to great Mr @mhogomchungu please, do you think Vxkex let us use MediaDownloaderQt6-5.2.0.setup.exe in our windows 7 os 32 bits? Will there be a conflict and bugs  if we use and install in the same time Media-Downloader for Windows 7 and Media-Downloader for Windows 10 in our Windows 7 OS at the same time using Vxkex?

**Comment by mhogomchungu** [comment]
Why do you want to run Qt6 build on your windows7 computer? What is wrong with the Qt5 build that officially works with windows7?

**Comment by trimechee** [comment]
Mr @mhogomchungu , sorry there is a misunderstanding, i didn't say i want to use media-downloader qt6 in my windows 7 os, i don't need it because the version of media-downloader for windows 7 os 32 bits works perfectly without problems, i said, because i saw and you saw the complex technical discussion when i asked mr @nicolaasjan to compile yt-dlp for me for my windows 7 os 32 bits because mr nicolaasjan compiles yt-dlp for 64 bits, there was a very complex technical discussion between mr nicolaasjan and a yt-dlp developer and a complex compilation so that mr nicolaasjan could offer me the 32 bits version of yt-dlp, so developing software for 32 bits os seems more difficult and complex than 64 bits os and my point is to say if compiling media-downloader for windows os 32 bit becomes too complex difficult impossible for windows 7 , maybe Vxkex can solve the problem and I think users of media-downloader for windows 7 os are ready to use vxkex if it becomes necessary to enjoy media downloader on our windows 7 os 32 bits, Mr @adeii who compiles 64 bits software for windows 7 generously compiles special versions compatible with my windws 7 os 32 bits and he sometimes recommends to use vxkex for some programs to work, like for mpc qt......

https://github.com/adeii/Qt6Win7

**Comment by trimechee** [comment]
and this is the real Vxkex, it was updated in october and fix serious bugs with windows 7 os 32 bits..... : 


https://github.com/i486/VxKex

**Comment by mhogomchungu** [comment]
I have no plans of dropping Qt5 support so there is no need to worry about Media Downloader not working in 32 bit windows7.

**Comment by trimechee** [comment]
Great !!! Thanks you so much :) 💯 🥇
