### ISSUE TITLE
Which extension to use for downloading video from sites that isn't YouTube, Facebook, Twitch? 

### ISSUE THREAD

**Issue by leryeo** [mhogomchungu/media-downloader#499]
Say if it is an obscure website and the default yt-dlp extension doesn't work, which extension should I use that will have the greatest likelihood of being able to download the video?

**Comment by mhogomchungu** [comment]
Rest of supported extensions have a list of website they support well and if the website you want to download from is not on their list then the chance of things working are not very high.
