### ISSUE TITLE
Feature: Add "Open URL in browser" to context menu (Batch)

### ISSUE THREAD

**Issue by larsen0815** [mhogomchungu/media-downloader#501]
Sometimes, it would be useful to be able to directly open a video from the Batch list in the browser, e.g. when a video fails to download.

Adding an option "Open URL in browser" to the context menu in Batch list would help.

**Comment by mhogomchungu** [comment]
There is already an option to copy the URL.

The menu is already too long and i do not think this feature is important enough to add it to the list.
