### ISSUE TITLE
Feature: Automatically start download (Batch)

### ISSUE THREAD

**Issue by larsen0815** [mhogomchungu/media-downloader#502]
Automatically start to download when a link is copied into the Batch list (via clipboard monitoring).

That way, I could choose some of the newest videos in my YouTube subscriptions, and while I do so copying the URLs, the videos would already be downloaded.

**Comment by mhogomchungu** [comment]
This is already possible but the option to enable it is not visible in the UI.

When the program start, look at the "basic downloader" tab and then go to the "App Data Path" folder, the settings file is in the "settings" sub folder.

Close Media Downloader.

Open the settings file and then set "AutoDownloadWhenAddedInBatchDownloader" value to "true".

Start Media Downloader.
