### ISSUE TITLE
Improve handling of "Requested format is not available"

### ISSUE THREAD

**Issue by larsen0815** [mhogomchungu/media-downloader#503]
I choose to prefer a resolution of 480p. This one video only has higher and lower resolutions, so the download failed:

```
[media-downloader] cmd: "C:/1temp/MediaDownloader-5.2.0/local/bin/yt-dlp.exe" "--match-filter" "!playlist" "--break-on-reject" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-P" "C:/1temp/MediaDownloader-5.2.0/Downloads" "-f" "bestvideo[height=480][ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/bestvideo[height=480]+bestaudio" "--compat-options" "2022" "--progress-template" "download:[download] downloaded_bytes:%(progress.downloaded_bytes)s ETA:%(progress.eta)s total_bytes_estimate:%(progress.total_bytes_estimate)s total_bytes:%(progress.total_bytes)s progress.speed:%(progress.speed)s filename:%(progress.filename)s" "https://www.youtube.com/watch?v=mF5MULA7_j8"
[youtube] Extracting URL: https://www.youtube.com/watch?v=mF5MULA7_j8
[youtube] mF5MULA7_j8: Downloading webpage
[youtube] mF5MULA7_j8: Downloading ios player API JSON
[youtube] mF5MULA7_j8: Downloading mweb player API JSON
[youtube] mF5MULA7_j8: Downloading m3u8 information
ERROR: [youtube] mF5MULA7_j8: Requested format is not available. Use --list-formats for a list of available formats
[media-downloader] Download Failed(ErrorCode=1)
```

If the preferred video resolution is not available, automatically choosing the next best value (higher or lower configurable via options) would be nice.

Is this something Media Downloader can do or should I (mayba additionally) add a feature request with yt-dlp?

**Comment by mhogomchungu** [comment]
Personally, when i request a media with certain properties, i like to get what i asked for or a failure notice so that i can adjust my request.

If you want resolution of "480 or lower" then add ``-S res:480,+codec:avc:m4a``` option in the "Download options" text field.

You can go to "configure tab" and then "preset options" and then delete all the options that are there and then add your own using above template and only change the 480 number.
