### ISSUE TITLE
Add support of media player number 1 in the world : Potplayer please

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#504]
Hi, i install many media playersin my eee pc but potplayer is my favorite media player by default, potplayer has internal youtuber support and can be integrated with 3D youtube source plugin which add yt-dlp support to potplayer, but sadly 3D youtube source plugin doesn't 't work anymore with the latest potplayer version , and i need to play mail ru videos because my favorite anime site put many videos in this famous russian site that has rare quality 360p ideal for my weak old cpu and weak connectivity!

 so i try with life saver our beloved Media-downloader that has great rare feature to send and play streams wit media players, i see in the list of right click: vlc, kmplayer, windows media player, foobar2000....but i don 't see potplayer in the list of media players, and we hope please integration and addition of potplayer to the list of the media player supported by vital great Media-downloader, thanks!

**Comment by mhogomchungu** [comment]
It does not show up in Media Downloader because and it does not add itself properly to Windows registry.

Added as a special condition and these are usually bad to have.

![Screenshot_20241228_234040](https://github.com/user-attachments/assets/9db99feb-cf3e-4b15-aed8-4f4964e35e01)

**Comment by trimechee** [comment]
Thanks so much !! 💯 🥇
