### ISSUE TITLE
Does feature of media-downloader : "play with media player" add referer, user agen string, cookies.....when media -downloader send streams to media player ?

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#505]
Hi, I couldn't playback some m3u8 streams detected by Openin--vlc extension which made new commits by adding referer, user agent string.....same for the preview feature of Cat-Catch extension which can preview video with potplayer or vlc, Cat-Catch added a new call protocol PotplayerFix :
potplayer://${url} ${referer|exists:'/referer="*"'}

and we can send encrypted hls video streams detected by Cat-Catch to potplayer in chromium and firefox (preview with vlc is experiencing preview issues with the new chromium 131 kernel and I informed vlc),

https://github.com/xifangczy/cat-catch
https://github.com/xifangczy/URLProtocol

https://github.com/andy-portmen/open-in-vlc/

so we want to know please if Media-dwnloader adds all that to the media player when it sends the video to the media player? because adding referer, user aget string... allows us to fix some playbck problems...

if not, hopefully media-downloader will add referer, use agent string....to the media stream sent to media players please.

does Media -donwloader also send cookies to the media player?

some users complain that youtube throttles bitrates when using external media player and yt-dlp has to import youtube cookies in some cases to fix this problem, we hope please media-donwloader will  import youtube cookies and then, media -downloader can send youtube stream to media player to playback youtube videos without throttle, thanks !

i tried to play twitter videos because videos on twitter are very heavy and lag freeze even lowest quality in my old laptop, i tried with Mpc-qt, Mpc-be, Mpc-hc, smplayer, potplayer with 3DYD Youtube Source plugin, qmplay2...all these players fail to play twitter videos and have message that i should add cookies commands like --cookies-from-browser firefox....

i am not expert, i tired to add --cookies-from-browser firefox to the yt-dlp engines of these media players but no video playback :(

the last chance is Media-dwonlaoder, maybe add optional option "add cookies to stream send to media players" to fix probelm of playback protected restricted videos, thanks !

maybe my discoveries can help to make this dream true of support cookies and send them to media players please ! 

https://mpv.io/manual/stable/#options-ytdl-raw-options :

--ytdl-raw-options=username=user,password=pass

authentification options
https://github.com/ytdl-org/youtube-dl/blob/master/README.md#authentication-options

also i find these commands, may be they can help to import cookies from browsers and my be good idea to add them to FAQ :

cookies yt-dlp command line arguments :

--cookies-from-browser firefox ( firefox does not lock the export of cookies to yt dlp unlike chrome, some users said we should disconnect from our youtube account if this doesn't work and try again )

chrome --disable-features=LockProfileCookieDatabase --disable-features=NetworkServiceSandbox

yt-dlp cookies imports
https://github.com/coletdjnz/yt-dlp-youtube-oauth2
https://github.com/coletdjnz/yt-dlp-get-pot
https://github.com/seproDev/yt-dlp-ChromeCookieUnlock

https://github.com/54ac/stream-detector (can export cookies to exteranl tool)

https://github.com/zaidka/cliget (can export cookies to exteranl tool)

https://github.com/einKnie/video-detector

https://github.com/fnxweb/neo-diggler (can export cookies to external tool)

Extract the video URL from the current page.
Video URL Extractor
https://addons.mozilla.org/fr/firefox/addon/video_url_extractor/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
[jonathan.racaud@outlook.com](mailto:jonathan.racaud@outlook.com)

https://github.com/ytdl-patched/ytdl-patched
https://github.com/pratikpatel8982/yt-dlp-mp4decrypt
https://github.com/pratikpatel8982/yt-dlp-hianime

https://github.com/rotemdan/ExportCookies

also

i find new secret great methods and tricks to add cookies to media player to skip youtube throttle :

https://github.com/akiirui/userscript/tree/play-with-mpv
https://greasyfork.org/en/scripts/416271-play-with-mpv

yt dlp ytdlp yt-dlp format selection
worst / worst* /worstvideo / worstaudio /worstaudio*/worstvideo*/bestvideo/ bestaudio/
https://github.com/yt-dlp/yt-dlp/blob/master/README.md#format-selection

Try Pass cookies
For advanced users to view member-only videos.

Because userscript no permissions to access full cookies (like HttpOnly cookies), then manually export cookies only.

Open settings, Switch Try Pass Cookies to Yes.
Export cookies file manually (Chromium, Firefox)

https://github.com/hrdl-github/cookies-txt
https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/

https://github.com/kairi003/Get-cookies.txt-Locally
[kairi.satellite@gmail.com](mailto:kairi.satellite@gmail.com)

https://github.com/ReeganExE/open-cookies.txt
https://chromewebstore.google.com/detail/open-cookiestxt/gdocmgbfkjnnpapoeobnolbbkoibbcif

Cookies must be export to these path:

Linux:

$HOME/.config/mpv-handler/cookies/
Windows:

(mpv-hander.exe parent folder)\cookies
Cookies file name must be following this format:

[www.youtube.com.txt](http://www.youtube.com.txt/) (https://www.youtube.com/watch?v=BUOmDL1L4XU)

**Comment by trimechee** [comment]
EDIT : update, i forget to post my discoveries that may help to fix cookies problems.... i edit my first post  : 

so maybe my discoveries can help to make this dream true of support cookies and send them to media players please !

https://mpv.io/manual/stable/#options-ytdl-raw-options :

--ytdl-raw-options=username=user,password=pass

authentification options
https://github.com/ytdl-org/youtube-dl/blob/master/README.md#authentication-options

also i find these commands, may be they can help to import cookies from browsers and my be good idea to add them to FAQ :

cookies yt-dlp command line arguments :

--cookies-from-browser firefox ( firefox does not lock the export of cookies to yt dlp unlike chrome, some users said we should disconnect from our youtube account if this doesn't work and try again )

chrome --disable-features=LockProfileCookieDatabase --disable-features=NetworkServiceSandbox

yt-dlp cookies imports
https://github.com/coletdjnz/yt-dlp-youtube-oauth2
https://github.com/coletdjnz/yt-dlp-get-pot
https://github.com/seproDev/yt-dlp-ChromeCookieUnlock

https://github.com/54ac/stream-detector (can export cookies to exteranl tool)

https://github.com/zaidka/cliget (can export cookies to exteranl tool)

https://github.com/einKnie/video-detector

https://github.com/fnxweb/neo-diggler (can export cookies to external tool)

Extract the video URL from the current page.
Video URL Extractor
https://addons.mozilla.org/fr/firefox/addon/video_url_extractor/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
[jonathan.racaud@outlook.com](mailto:jonathan.racaud@outlook.com)

https://github.com/ytdl-patched/ytdl-patched
https://github.com/pratikpatel8982/yt-dlp-mp4decrypt
https://github.com/pratikpatel8982/yt-dlp-hianime

https://github.com/rotemdan/ExportCookies

also

i find new secret great methods and tricks to add cookies to media player to skip youtube throttle :

https://github.com/akiirui/userscript/tree/play-with-mpv
https://greasyfork.org/en/scripts/416271-play-with-mpv

yt dlp ytdlp yt-dlp format selection
worst / worst* /worstvideo / worstaudio /worstaudio*/worstvideo*/bestvideo/ bestaudio/
https://github.com/yt-dlp/yt-dlp/blob/master/README.md#format-selection

Try Pass cookies
For advanced users to view member-only videos.

Because userscript no permissions to access full cookies (like HttpOnly cookies), then manually export cookies only.

Open settings, Switch Try Pass Cookies to Yes.
Export cookies file manually (Chromium, Firefox)

https://github.com/hrdl-github/cookies-txt
https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/

https://github.com/kairi003/Get-cookies.txt-Locally
[kairi.satellite@gmail.com](mailto:kairi.satellite@gmail.com)

https://github.com/ReeganExE/open-cookies.txt
https://chromewebstore.google.com/detail/open-cookiestxt/gdocmgbfkjnnpapoeobnolbbkoibbcif

Cookies must be export to these path:

Linux:

$HOME/.config/mpv-handler/cookies/
Windows:

(mpv-hander.exe parent folder)\cookies
Cookies file name must be following this format:

[www.youtube.com.txt](http://www.youtube.com.txt/) (https://www.youtube.com/watch?v=BUOmDL1L4XU)

**Comment by mhogomchungu** [comment]
No, it does not and its not possible to support these options. Media Downloads calls the media player and gives it only the Url that points to a media to be played.

A single output entry given by yt-dlp look like below. The Url entry is the entry Media Downloader passes to external media players and some other options are displayed in the UI.

It is not possible to send referrer  because yt-dlp does not give it.

It is possible to send user-agent because that information is available but different player will accept it in different ways and i can not anticipate how each and every player will accept it.
```
    {
      "asr" : 48000,
      "filesize" : 426095,
      "format_id" : "251",
      "format_note" : "medium",
      "source_preference" : -1,
      "fps" : null,
      "audio_channels" : 2,
      "height" : null,
      "quality" : 3.0,
      "has_drm" : false,
      "tbr" : 119.685,
      "filesize_approx" : 426093,
      "url" : "https://rr1---sn-8vq5jvhu1-q5gl.googlevideo.com/videoplayback?expire=1735492404&ei=1C5xZ6XpFIe9mLAP9NSbqQw&ip=197.250.225.203&id=o-ABjJ1qcWyMWEuVebovB55X6optNO4h79DAlGLZFO2a8s&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1735470804%2C&mh=P6&mm=31%2C29&mn=sn-8vq5jvhu1-q5gl%2Csn-hc57en76&ms=au%2Crdu&mv=m&mvi=1&pl=22&rms=au%2Cau&initcwndbps=247500&bui=AfMhrI91Ey8gQD2Id7xloDI2cLookMpJVUWgZiL_PyIqjUuuFQGHpGMJVwvI2M04ex-UM9_VYZoIMcut&spc=x-caUGA8-0N4ysOr1xmdDToik5o1JTYd3_rC_lEKTedJOvk3UA&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=426095&dur=28.481&lmt=1735445264517678&mt=1735470307&fvip=6&keepalive=yes&fexp=51326932%2C51335594%2C51371294&c=IOS&txp=6308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAKIoiPeNs5OSJ5CJoqtXpBJ_eFRynLXlYqwuTWcLDQw8AiEAjic1L77-aaBBPvWZWgcfxWur4n44VWOZn5oOqqDJe50%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIgFfPVLSaXgs4A8h5dCRNSo57qEQmue9ymmem-fBcT08oCIQDS2zs9TtjA8AU0iBegkDCfzcX5D9fX5j046TytSClsLQ%3D%3D",
      "width" : null,
      "language" : "en",
      "language_preference" : -1,
      "preference" : null,
      "ext" : "webm",
      "vcodec" : "none",
      "acodec" : "opus",
      "dynamic_range" : null,
      "container" : "webm_dash",
      "downloader_options" : {
        "http_chunk_size" : 10485760
      },
      "protocol" : "https",
      "audio_ext" : "webm",
      "video_ext" : "none",
      "vbr" : 0,
      "abr" : 119.685,
      "resolution" : "audio only",
      "aspect_ratio" : null,
      "http_headers" : {
        "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
        "Accept" : "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language" : "en-us,en;q=0.5",
        "Sec-Fetch-Mode" : "navigate"
      },
      "format" : "251 - audio only (medium)"
    }
```

**Comment by trimechee** [comment]
Interesting ! Thanks so much Mr Mhogomchungu for these important explanations :) 💯 🥇

it seems to me that 3D youtube source plugin has option to add custom user agent to media player compatibles like potplayer and mpc hc....alos mpc be has option to add custom user agent.... but it seems to me that it is not the same thing, indeed it is up to web browser extensions to add such data....
