### ISSUE TITLE
Why is the macOS build arm64 only? 

### ISSUE THREAD

**Issue by b0gdanw** [mhogomchungu/media-downloader#507]
The macOS build MediaDownloader-5.2.0.dmg is arm64 only (Apple Silicon).
(file /Applications/MediaDownloader.app/Contents/MacOS/MediaDownloader returns Mach-O 64-bit executable arm64)

Media-downloader 5.2.0 can be successfully build from source for macOS 12.7 Intel (x86_64)

Building a Universal macOS Binary
https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by mhogomchungu** [comment]
I do not have a macOS to build or test them and github build them for me.

The build file i use is [here](https://github.com/mhogomchungu/media-downloader/blob/main/.github/workflows/publishMacOsRelease.yml).

A list of supported Qt versions and architecture can be found [here](https://ddalcino.github.io/aqt-list-server/). From this website, you can see that for 32bit build for macOS, the best i can do is with Qt5 and using "wasm_32" architecture. The "wasm_32" thing makes no sense to me.

**Comment by b0gdanw** [comment]
I am not asking about x32 apps, they haven’t been supported on macOS since 2019 (macOS Catalina).
I am talking about x64 binaries for Intel Macs (x86_64).
I think -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" needs to be added.

**Comment by mhogomchungu** [comment]
Try this git build and see if it makes a difference

https://github.com/mhogomchungu/media-downloader-git/releases/download/0.0.0/MediaDownloaderQt6.git.dmg

Output of the configure steps looks like below
```
cmake -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_INSTALL_PREFIX=/Users/runner/work/media-downloader-git/media-downloader-git/MediaDownloader -DSOURCE_PATH=/Users/runner/work/media-downloader-git/media-downloader-git/MAC/ -DCMAKE_VERBOSE_MAKEFILE=FALSE -DCMAKE_BUILD_TYPE=RELEASE -S /Users/runner/work/media-downloader-git/media-downloader-git/MAC/ -B /Users/runner/work/media-downloader-git/media-downloader-git/MAC/build6
-- The CXX compiler identification is AppleClang [15](https://github.com/mhogomchungu/media-downloader-git/actions/runs/12538961556/job/34964629346#step:4:16).0.0.15000309
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Building With Qt6
-- Found OpenGL: /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/System/Library/Frameworks/OpenGL.framework
-- Found WrapOpenGL: TRUE
-- Configuring done (3.6s)
-- Generating done (0.1s)
-- Build files have been written to: /Users/runner/work/media-downloader-git/media-downloader-git/MAC/build6
```

I have added the option you said but i see no change in file size and i am not sure if it works or not

**Comment by b0gdanw** [comment]
It worked! it’s Universal now, for Intel and ARM Macs.
```
lipo -archs /Volumes/MediaDownloader/MediaDownloader.app/Contents/MacOS/MediaDownloader
x86_64 arm64
```

There is another problem, it’s set to be for macOS 14.0 and above.
It can be compiled successfully for macOS 11.5 and above.
I think **_runs-on: macos-latest_** can be changed into  **_runs-on: macos-11_** in publishMacOsRelease.yml

**Comment by mhogomchungu** [comment]
Earliest supported version is 12 and a list of all supported versions can be found here: https://github.com/actions/runner-images/tree/main/images/macos

Below link should now point to a version that was build with macos 12.

https://github.com/mhogomchungu/media-downloader-git/releases/download/0.0.0/MediaDownloaderQt6.git.dmg

**Comment by mhogomchungu** [comment]
```
The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15. For more details, see https://github.com/actions/runner-images/issues/10721
```

It fails to build with macos-12, so the earlies possible is version 13.

**Comment by b0gdanw** [comment]
Thank you for trying and for the explanation. 
It’s probably best to revert to **_macos-latest_**.
Please consider including the supported versions as **_“macOS 14.0 or later”_** in the README file.

**Comment by mhogomchungu** [comment]
Done.

But, if a build system is important then it is better to explicitly set it so that i know what build works with what system. I have set build system to be version 13 and README will say "version 13 or later" when a new version is out. Now it says "version 14 or later".
