### ISSUE TITLE
Eve after cancellation Aria2c continues to download in background 

### ISSUE THREAD

**Issue by cinetube** [mhogomchungu/media-downloader#58]
Engine causing issue - yt-dlp-aria2c

While downloading videos when I press "cancel" button the downloads seems to be paused but it doesn't. Actually aria2c continues to download the videos in the background even after I have cancelled/paused the download. 

Please resolve this issue.

**Comment by mhogomchungu** [comment]
I have reuploaded windows executable with a fix, can you redownload version 1.8.0 and confirm that the problem is gone?
