### ISSUE TITLE
File renaming not allowing spaces in filenames

### ISSUE THREAD

**Issue by protectedprofile** [mhogomchungu/media-downloader#71]
File renaming is not working in media-downloader, at least when using yt-dlp, if there are spaces in the file name.

For ex.
Under youtube-dl, this has been working perfectly

-o '/home/username/Downloads/Video/%(uploader)s - %(title)s.%(ext)s'

with media-download, using yt-dlp, I am forced to use this without any spaces

--newline --ignore-config --no-playlist -o %(uploader)s/%(uploader)s-%(title)s.%(ext)s

**Comment by mhogomchungu** [comment]
You have to use double quotes to protect spaces and below line should work:-
```
-o "home/username/Downloads/Video/%(uploader)s - %(title)s.%(ext)s"
```
Media Downloader uses QProcess::splitCommand to split the options in lists and the documentation for the command is here[1].

[1] https://doc.qt.io/qt-5/qprocess.html#splitCommand
