### ISSUE TITLE
How to add url using External Application Button Firefox addon?

### ISSUE THREAD

**Issue by cinetube** [mhogomchungu/media-downloader#72]
How to add url using External Application Button Firefox addon?

What arguments I need to use to add url automatically on the Batch Downloader section. 

<img width="868" alt="Screenshot 2021-11-03 201420" src="https://user-images.githubusercontent.com/23441775/140077054-55463a28-9f2e-4ef1-858f-61a81fd379e8.png">

**Comment by mhogomchungu** [comment]
```-u [HREF]```

**Comment by cinetube** [comment]
@mhogomchungu  Thanks
