### ISSUE TITLE
HDR download support

### ISSUE THREAD

**Issue by indicator0** [mhogomchungu/media-downloader#79]
Hi, with media-downloader 2.0.0, no HDR versions of selected video can be parsed and downloaded. But I am sure that HDR version is available on the ytb website. Is there anything need to be configured to make it work? SDR versions are OK to download.

**Comment by mhogomchungu** [comment]
what does HDR and SDR mean.

Can you post a link i can use to test

**Comment by mhogomchungu** [comment]
1. Copy link to batch downloader tab: https://www.youtube.com/watch?v=tO01J-M3g0U
2. Right click the link entry and then select "Show Media Options".
3. On your keyboard, press CTRL key and then click entry with format code 701 and then then click entry with formt code 140.
4. Click "Set"
5. You will be taken back to batch downloader tab with "Download Options" set to 701+140
6. Click "Download"

Above steps will cause you to download the video with the highest available video quality of 3840x2160(4K UHDTV) resolution.

You can add the "701+140" option to preset list for easier access and will add it to the list by default shortly.

**Comment by indicator0** [comment]
> 1. Copy link to batch downloader tab: https://www.youtube.com/watch?v=tO01J-M3g0U
> 2. Right click the link entry and then select "Show Media Options".
> 3. On your keyboard, press CTRL key and then click entry with format code 701 and then then click entry with formt code 140.
> 4. Click "Set"
> 5. You will be taken back to batch downloader tab with "Download Options" set to 701+140
> 6. Click "Download"
> 
> Above steps will cause you to download the video with the highest available video quality of 3840x2160(4K UHDTV) resolution.
> 
> You can add the "701+140" option to preset list for easier access and will add it to the list by default shortly.

Yes it works now! Thanks for your help. 'Get List' results cannot explicitly shows whether this video is HDR or SDR, but I can see it in text parsing result.
