### ISSUE TITLE
media-downloader flatpak at flathub?

### ISSUE THREAD

**Issue by fastrizwaan** [mhogomchungu/media-downloader#81]
Hi,

Flathub gives discoverability to your app. Please consider flatpaking it.

https://github.com/flathub/org.flatpak.qtdemo
https://github.com/flathub/info.smplayer.SMPlayer/blob/master/info.smplayer.SMPlayer.yml

Thanks.

**Comment by sbstn87** [comment]
I would use flatpak if I were to choose between flatpak and AppImage.

**Comment by mhogomchungu** [comment]
Flatpak version is tracked below, please test the package mentioned there and contribute there. 

https://github.com/mhogomchungu/media-downloader/issues/430

**Comment by mhogomchungu** [comment]
The project is now on [flathub](https://flathub.org/apps/io.github.mhogomchungu.media-downloader).
