### ISSUE TITLE
possible to have setting to choose to open at previous tab?

### ISSUE THREAD

**Issue by linuxgirl22** [mhogomchungu/media-downloader#82]
Hi and thanks for all your great work! May I ask if it's possible to have a setting to 'choose to open at previously used tab'? I always use the Batch tab, and now media-downloader opens at the Basic tab.

**Comment by mhogomchungu** [comment]
1. Go to "Configure" tab.
2. Go to "General Options" subtab.
3. Uncheck "Show version info when starting".
4. Go to "Batch Downloader" tab.
5. Restart.

**Comment by linuxgirl22** [comment]
Thanks @mhogomchungu! :-)
