### ISSUE TITLE
[feature request] Add support for youtube-dl forks

### ISSUE THREAD

**Issue by pukkandan** [mhogomchungu/media-downloader#9]
Add support for youtube-dl forks like [yt-dlp](https://github.com/yt-dlp/yt-dlp), [animelover1984/youtube-dl](https://github.com/animelover1984/youtube-dl), [youtube-dlc](https://github.com/blackjack4494/yt-dlc) etc.

Preferably, instead of adding each fork individually, give the user the option to use a binary of their choice. All these forks are compatible with youtube-dl's switches and config files - so only the executable files need to be changed

**Comment by pukkandan** [comment]
There is one thing. [yt-dlp](https://github.com/yt-dlp/yt-dlp) has a different output for the `--list-formats` as compared to the others, so if you are parsing the `-F` output, make sure to pass an additional `--list-formats-old` to get the formats in old layout

**Comment by mhogomchungu** [comment]
This is already possible. media-downloader is designed to support multiple "engines" and these engines are configured using json based configuration files and their default location in linux is ```$HOME_PATH/.local/share/media-downloader/engines.v1/``` and the default location on Windows is ```$HOME_PATH/AppData/Roaming/media-downloader/engines.v1/```

The contents of youtube-dl config file here in my linux system is like below and you set it to use your fork with your preffered default options simply by changing the contents of this config file.

My future plan is to allow users to add their own "engines" simply by providing these configuration files.

```
{
    "BackendPath": "/home/ink/.local/share/media-downloader/bin",
    "BatchFileArgument": "-a",
    "CanDownloadPlaylist": true,
    "CommandName": "youtube-dl",
    "DefaultDownLoadCmdOptions": [
        "--newline",
        "--ignore-config",
        "--no-playlist",
        "--newline"
    ],
    "DefaultListCmdOptions": [
        "-F"
    ],
    "DownloadUrl": "https://api.github.com/repos/ytdl-org/youtube-dl/releases/latest",
    "Name": "youtube-dl",
    "OptionsArgument": "-f",
    "UsePrivateExecutable": false,
    "VersionArgument": "--version",
    "VersionStringLine": 0,
    "VersionStringPosition": 0
}
```

**Comment by mhogomchungu** [comment]
This is done in the git version and the functionality is seen in below images.

1. Build media downloader from git.
2. Create a file and name it ```yt-dlp.json``` and in it, add below json data.
3. Start media downloader, click the configure tab and then "Add a Plugin" tab and add the ```yt-dlp.json``` file.
4. Restart media downloader and your extension will be on the list and it be the new default.

A new release with the official support will be out on April 1st,2021 and there will be a page where people can know and download the extension.

Contents of ```yt-dlp.json``` file
```
{
    "BackendPath": "${BackendPath}",
    "BatchFileArgument": "-a",
    "CanDownloadPlaylist": true,
    "CommandName": "yt-dlp",
    "DefaultDownLoadCmdOptions": [
        "--newline",
        "--ignore-config",
        "--no-playlist"
    ],
    "DefaultListCmdOptions": [
        "-F",
        "--list-formats-old"
    ],
    "DownloadUrl": "https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest",
    "LikeYoutubeDl":true,
    "Name": "yt-dlp",
    "OptionsArgument": "-f",
    "UsePrivateExecutable": true,
    "VersionArgument": "--version",
    "VersionStringLine": 0,
    "VersionStringPosition": 0
}
```
![Screenshot_20210307_114041](https://user-images.githubusercontent.com/3496115/110234625-9042e300-7f3c-11eb-9b68-46d654f8833c.png)
![Screenshot_20210307_114231](https://user-images.githubusercontent.com/3496115/110234626-92a53d00-7f3c-11eb-883a-2fb3c1912daa.png)
