### ISSUE TITLE
Suggestion: Allow monitoring clipboard for media URLs

### ISSUE THREAD

**Issue by Futureknows** [mhogomchungu/media-downloader#90]
UGET and other download managers feature a clipboard monitoring function that automatically adds downloadable media URLs to the queue. This would be a very useful feature in media-downloader.

**Comment by mhogomchungu** [comment]
Done

**Comment by mhogomchungu** [comment]
The option is off by default for now and you will have to change a config option to enable it and will look into having a GUI way to enable it.

If you want the feature now and you are using linux then:-
1. Update from git.
2. Run the app atleast once.
3. Go to the app config file and then look for the option "MonitorClipboardContents" and change its value to "true". The config file in linux is at "~/.config/media-downloader/".

**Comment by mhogomchungu** [comment]
My preferred way to add links to media downloader is documented here: https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#7-how-do-i-create-a-context-menu-on-chrome-or-firefox-to-open-links-in-media-downloader

**Comment by mhogomchungu** [comment]
The git version has a GUI way to toogle this functionality on or off.

![Screenshot_20220327_074954](https://user-images.githubusercontent.com/3496115/160267289-86670f6d-1abb-4b71-aaef-29652f76b6e6.png)

**Comment by mhogomchungu** [comment]
New version is out with the GUI way to enable/disable requested feature: https://github.com/mhogomchungu/media-downloader/releases/tag/2.3.0
