### ISSUE TITLE
libc6 dependency problem

### ISSUE THREAD

**Issue by linuxgirl22** [mhogomchungu/media-downloader#92]
Hello, I've just moved to MX xfce. Media-downloader isn't in the deb-based repos; I understand there's a flatpak, but I don't use those. Found a newer (2.1.1) and older (1.9.0-1) deb file. The former can't run due to libc6 dependency. The latter needed aria2 installing, which is in the repo, but I'm having various problems with downloads. On previous distro, the Default setting would pick up whichever e.g. 480 format would download just by pressing Default, which was awesome ... I realise that my choice to move from Bookworm back to Bullseye-based has thrown a spanner into the works a bit, but I'd appreciate any advice. Thanks.

**Comment by mhogomchungu** [comment]
If you are using amd64, then downloading this[1] debian package.

If you are using x86, then install this[2] debian package.

[1] https://download.opensuse.org/repositories/home:/obs_mhogomchungu/Debian_11/amd64/media-downloader_2.2.0-1_amd64.deb

[2] https://download.opensuse.org/repositories/home:/obs_mhogomchungu/Debian_11/i386/media-downloader_2.2.0-1_i386.deb

**Comment by linuxgirl22** [comment]
Thank you very much! :-)

**Comment by mhogomchungu** [comment]
You are welcome
