### ISSUE TITLE
No longer showing audio/video bitrates in Get List

### ISSUE THREAD

**Issue by githottub** [mhogomchungu/media-downloader#93]
In the previous version I was using (1.5? I think) when using Get List, the note column would show the separate audio and video bitrates. This was really helpful for various reasons. Obviously to choose your preferred version but I also found it vital in getting vidoes from NHK due to some file versions will occasionally be corrupt and it was possible to immediately identify that by looking at the bitrates. But after upgrading to version 2.2, it is no longer showing the individual audio and video bitrates in Get List. Can you please return this functionality? Thank you!!!

**Comment by mhogomchungu** [comment]
Below image shows video entries have both tbr and vbr and audio has only tbr so the only thing to add is abr for audio.

![Screenshot_20220127_133342](https://user-images.githubusercontent.com/3496115/151341932-a492fe23-3a00-41f4-99df-8a538883a6f6.png)

**Comment by mhogomchungu** [comment]
Audio file now also show abr as seen in the image below.

Closing this one and please comment if i did not understand the issue and its still present.
![Screenshot_20220127_135140](https://user-images.githubusercontent.com/3496115/151345000-4bb6329d-937d-4d4e-80c0-83141d7083f3.png)

**Comment by mhogomchungu** [comment]
If you are using windows, then binaries with the fix can be downloaded from here[1] and here[2]

[1] https://github.com/mhogomchungu/media-downloader/releases/download/2.2.0/MediaDownloader-dev-jan-29-2022.setup.exe

[2] https://github.com/mhogomchungu/media-downloader/releases/download/2.2.0/MediaDownloader-dev-jan-29-2022.zip

**Comment by githottub** [comment]
Thanks for trying to fix this but I guess the problem is dependant on the video source and therefore remains even in the new version. I'm including a screenshot of what's shown for: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2061495/
![Screenshot](https://user-images.githubusercontent.com/47539527/151717428-e15f47e4-f7d8-49bd-8a75-621320b00f68.png)
As you can see, it shows nothing for the audio codec and although it does show the video bitrate, it doesn't show the codec. Hope this helps troubleshoot the problem. Thanks again!

**Comment by mhogomchungu** [comment]
The UI does not show a lot of options because they are not available for that url, running yt-dlp directly gives the following output.

```
[ink@localhost ~]$ yt-dlp -F https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2061495/
[NhkVod] 2061-495: Downloading JSON metadata
[Piksel] nw_vod_v_en_2061_495_20220124013000_01_1642957439: Downloading webpage
[Piksel] nw_vod_v_en_2061_495_20220124013000_01_1642957439: Downloading JSON metadata
[Piksel] nw_vod_v_en_2061_495_20220124013000_01_1642957439: Downloading JSON metadata
[Piksel] k8j6p8dc: Downloading m3u8 information
[Piksel] k8j6p8dc: Downloading SMIL file
[info] Available formats for k8j6p8dc:
ID         EXT RESOLUTION │   FILESIZE    TBR PROTO  │ VCODEC     VBR ACODEC   ABR
───────────────────────────────────────────────────────────────────────────────────
http-382   mp4 320x180    │   74.61MiB   382k http   │ unknown   255k unknown 127k
hls-391    mp4 unknown    │              391k m3u8_n │ unknown   391k unknown   0k
http-391   mp4 320x?      │              391k http   │ unknown   391k unknown   0k
http-662   mp4 640x360    │  128.65MiB   662k http   │ unknown   535k unknown 127k
hls-677    mp4 unknown    │              677k m3u8_n │ unknown   677k unknown   0k
http-677   mp4 640x?      │              677k http   │ unknown   677k unknown   0k
http-1243  mp4 1280x720   │  240.60MiB  1243k http   │ unknown  1116k unknown 127k
hls-1272   mp4 unknown    │             1272k m3u8_n │ unknown  1272k unknown   0k
http-1272  mp4 1280x?     │             1272k http   │ unknown  1272k unknown   0k
http-2126  mp4 1280x720   │  411.13MiB  2126k http   │ unknown  1999k unknown 127k
http-2177  mp4 1280x?     │             2177k http   │ unknown  2177k unknown   0k
http-10266 mp4 1920x1080  │    1.98GiB 10266k http   │ unknown 10266k unknown   0k
[ink@localhost ~]$ 

```

**Comment by githottub** [comment]
OK. I guess maybe why I was seeing a difference between versions of Media Downloader is because the old one was using the original youtube-dl engine and the new one is using the dlp engine?? Anyway, is it possible you can also get the latest version to show the audio bitrate in the Get List like it used to? It really is very helpful. The above video is a good example - see how the 1920x1080 variant shows 0k for the audio bitrate whereas the other resolutions show 127k... by seeing that in Get List it makes it possible to know the 1080 one is corrupt and won't play. I have confirmed this several times because it periodically happens with videos from this source and everytime one shows 0k for the audio bitrate, the downloaded file won't play. 

Thank you for your help!!!

**Comment by mhogomchungu** [comment]
With yt-dlp, earlier version were taking the output as seen above and show it in the UI. The problem with this approach is that yt-dlp developer discourages using CLI outputs because they are unstable and they change without notice and i have observed about 3 changes with this output.

Newer versions of media downloader uses the recommended way and the received json based output can be seen when you right click on the "Url to download" area and choose "Show Log Window".

I have made changes and the UI now looks like above and it should now be easier to see what entry has 0K value and what entry have a different value, if a value is not present then thats because yt-dlp did not produce it.

To get the build with the fix, go here[1] and download a version with "MediaDownloader-dev-Feb-01-2022" in its name.

[1] https://github.com/mhogomchungu/media-downloader/releases/tag/2.2.0

![Screenshot_20220201_193919](https://user-images.githubusercontent.com/3496115/152011460-a7ade6de-1cfe-4d70-8b07-3f60b45b3095.png)

**Comment by githottub** [comment]
Thank you!

**Comment by mhogomchungu** [comment]
New version is out: https://github.com/mhogomchungu/media-downloader/releases/tag/2.2.1
