### ISSUE TITLE
Fix the GUI

### ISSUE THREAD

**Issue by wvxwxvw** [mhogomchungu/media-downloader#98]
Windows 7 x64 sp1, with all updates, without any patches and decorations,  
the standard zoom level is 100%,  
the most standard screen is FullHD.  
  
Due to the fact that the interface elements overlap each other, the program looks bad. For example, you have a highlight of the input fields at focus. Now let's see how it looks on your standard and first dark theme:
![2022 01 27_210133](https://user-images.githubusercontent.com/13194155/151417583-c48631b6-1714-4101-8cc4-5f25b20d5a4b.png)
![2022 01 27_210324](https://user-images.githubusercontent.com/13194155/151417590-68b4415e-efce-4ce0-b0fd-6d971aceff49.png)
As you can see, the backlight is stupidly overlapped by neighboring fields and is visible only on one or two sides.  
And this is just one example, there are still a lot of problems due to this short arrangement of elements. Especially on dark themes.  
  
The first request: Please separate the fields and buttons away from each other, as is done in all standard interfaces.  
  
Now about the design themes:  
I have only the standard and first dark themes working. The rest look really bad. But that's not the point. I prefer to use dark themes, but your first dark theme cannot be used because it is high contrast.  
  
The second request: Please duplicate the first dark theme by changing the dark colors in the duplicate to more gray, and the text color, for example, to 'silver'. And let this become the fifth topic, since perhaps someone needs a high-contrast one, too, for example, those who have bad eyesight.

**Comment by mhogomchungu** [comment]
I use KDE plasma and the UI looks fine. Will look into adding more space between elements.

Will look into have the first dark theme configurable

![Screenshot_20220128_093627](https://user-images.githubusercontent.com/3496115/151501450-a44099ec-531a-4eec-8042-73c8354acca3.png)

**Comment by mhogomchungu** [comment]
The git version now make it possible to customize the dark theme and the default config file looks like below

```
{
    "QPalette::AlternateBase": {
        "GlobalColor": "darkColor"
    },
    "QPalette::Base": {
        "rgba": [
            18,
            18,
            18,
            255
        ]
    },
    "QPalette::BrightText": {
        "Qt::GlobalColor": "Qt::red"
    },
    "QPalette::Button": {
        "GlobalColor": "darkColor"
    },
    "QPalette::ButtonText": {
        "Qt::GlobalColor": "Qt::white"
    },
    "QPalette::Disabled,QPalette::ButtonText": {
        "GlobalColor": "disabledColor"
    },
    "QPalette::Disabled,QPalette::HighlightedText": {
        "GlobalColor": "disabledColor"
    },
    "QPalette::Disabled,QPalette::Text": {
        "GlobalColor": "disabledColor"
    },
    "QPalette::Highlight": {
        "rgba": [
            42,
            130,
            218,
            255
        ]
    },
    "QPalette::HighlightedText": {
        "Qt::GlobalColor": "Qt::black"
    },
    "QPalette::Link": {
        "rgba": [
            42,
            130,
            218,
            255
        ]
    },
    "QPalette::Text": {
        "Qt::GlobalColor": "Qt::white"
    },
    "QPalette::ToolTipBase": {
        "Qt::GlobalColor": "Qt::white"
    },
    "QPalette::ToolTipText": {
        "Qt::GlobalColor": "Qt::white"
    },
    "QPalette::Window": {
        "GlobalColor": "darkColor"
    },
    "QPalette::WindowText": {
        "Qt::GlobalColor": "Qt::white"
    },
    "QToolTipStyleSheet": "QToolTip { color: #ffffff; background-color: #2a82da; border: 1px solid white; }",
    "darkColor": {
        "rgba": [
            45,
            45,
            45,
            255
        ]
    },
    "disabledColor": {
        "rgba": [
            127,
            127,
            127,
            255
        ]
    }
}

```

**Comment by mhogomchungu** [comment]
This is how the window now look in windows10 with gray(rgba: 171,183,183,255) as background color and silver(rgba: 192,192,192,255) as text color.

![Screenshot_20220128_201525](https://user-images.githubusercontent.com/3496115/151591965-1b70a166-93bc-4651-8333-f97fd1cba755.png)

**Comment by wvxwxvw** [comment]
I understood you. Excellent. If this is implemented by a configuration file, then it's even better. Am this git version available for download?

**Comment by mhogomchungu** [comment]
You use portable version or the one with an installer?

**Comment by wvxwxvw** [comment]
I usually prefer portable programs, and this one no exception.

**Comment by mhogomchungu** [comment]
Download this[1] git version and then do the following.

1. Go to configure tab and then select "Dark" theme and then restart.
2. On restart, the UI will contain the default dark theme.
3. Click the button next to the right side of the theme selection combo box.
4. In the dialog window that will show up, make a duplicate of the "Dark.json" file and then make your changes in the duplicate file. You can name this duplicate "Gray.json".
5. Restart the app and then go to the theme selection list and select your duplicate.
6. Restart.
7. Start using your duplicate with your custom options.

ps:
1. A list of Qt::GlobalColor is here[2].
2. You can replace those Qt::GlobalColor with "rgba" json array for a better control of colors.
3. You can google for rgba values for colors that you want to use and this[3] link seems to be a good start for gray values



[1] https://github.com/mhogomchungu/media-downloader/releases/download/2.2.0/MediaDownloader-dev-jan-29-2022.zip

[2] https://doc.qt.io/qt-5/qcolor.html#predefined-colors

[3] http://www.flatuicolorpicker.com/grey-rgba-color-model/

**Comment by wvxwxvw** [comment]
OK, thanks, I'm waiting for the implementation in the final. Here's what came out, if you're interested:
![2022 01 30_005543](https://user-images.githubusercontent.com/13194155/151678845-4a9a4b58-52a3-492a-b093-9e32335157e8.png)
```
{
    "QPalette::AlternateBase": {
        "GlobalColor": "darkColor"
    },
    "QPalette::Base": {
        "rgba": [
            41,
            42,
            43,
            255
        ]
    },
    "QPalette::BrightText": {
        "Qt::GlobalColor": "Qt::yellow"
    },
    "QPalette::Button": {
        "GlobalColor": "darkColor"
    },
    "QPalette::ButtonText": {
        "Qt::GlobalColor": "Qt::lightGray"
    },
    "QPalette::Disabled,QPalette::ButtonText": {
        "GlobalColor": "disabledColor"
    },
    "QPalette::Disabled,QPalette::HighlightedText": {
        "GlobalColor": "disabledColor"
    },
    "QPalette::Disabled,QPalette::Text": {
        "GlobalColor": "disabledColor"
    },
    "QPalette::Highlight": {
        "rgba": [
            27,
            129,
            231,
            255
        ]
    },
    "QPalette::HighlightedText": {
        "Qt::GlobalColor": "Qt::white"
    },
    "QPalette::Link": {
        "rgba": [
            77,
            148,
            209,
            255
        ]
    },
    "QPalette::Text": {
        "Qt::GlobalColor": "Qt::lightGray"
    },
    "QPalette::ToolTipBase": {
        "GlobalColor": "darkColor"
    },
    "QPalette::ToolTipText": {
        "Qt::GlobalColor": "Qt::lightGray"
    },
    "QPalette::Window": {
        "GlobalColor": "darkColor"
    },
    "QPalette::WindowText": {
        "Qt::GlobalColor": "Qt::lightGray"
    },
    "QToolTipStyleSheet": "QToolTip { color: Gainsboro; background-color: #292A2B; border: 1px solid DimGray; }",
    "darkColor": {
        "rgba": [
            45,
            45,
            45,
            255
        ]
    },
    "disabledColor": {
        "rgba": [
            127,
            127,
            127,
            255
        ]
    }
}
```
  
And immediately, so as not to breed topics:
![2022 01 30_010626](https://user-images.githubusercontent.com/13194155/151679071-e2c523e8-922e-4535-9e59-84cf43b2936f.png)

**Comment by mhogomchungu** [comment]
Your last image did not come from the git version i posted above because what i see with the posted version is in images below.

![Screenshot_20220130_083827](https://user-images.githubusercontent.com/3496115/151688111-383c4b54-f4d2-4eef-95e6-5edff2c8e6c9.png)


![Screenshot_20220130_083547](https://user-images.githubusercontent.com/3496115/151688069-f1f02cef-c270-450f-9386-7cda43dcde00.png)

**Comment by wvxwxvw** [comment]
What does git have to do with it? The hint of the Add button is not from her, but from the next button, I specially circled it in red and still stuck the arrow.

**Comment by mhogomchungu** [comment]
:-)

You should have mentioned the issue is with the tooltip text, the button no longer has the text now, thanks.

**Comment by mhogomchungu** [comment]
New version is out: https://github.com/mhogomchungu/media-downloader/releases/tag/2.2.1

**Comment by wvxwxvw** [comment]
@mhogomchungu 
Great, now the dark theme can be used "right out of the box". Thank you.
